Repository facebook/react-native-website, pull requests merged in 2019-06, with the labels that each got.

#989 Update docs for AppState module
  docs/appstate.md
Labels: Partner, p: callstack

#1008 June Open Source Update Blog Post
  website/blog/2019-06-12-react-native-open-source-update.md
Labels: Partner, RN Team, p: Facebook

#771 Update docs to reference ability to retry headless JS tasks
  docs/headless-js-android.md
Labels: :clock1: Waiting on PR

#1040 Fix up new optimizing flatlist doc
  docs/optimizing-flatlist-configuration.md
Labels: Partner, RN Team, p: Facebook
