Repository facebook/react-native-website, pull requests merged in 2019-02, with the labels that each got.

#115 Update scrollview.md to reflect duration argument
  docs/scrollview.md
Labels: Waiting on PR :clock1:

#755 Text/TextInput: Android now supports `maxFontSizeMultiplier` prop
  docs/text.md
  docs/textinput.md
Labels: Wait on future Release

#337 Update scrollview.md with disableScrollViewPanResponder prop
  docs/scrollview.md
Labels: :clock1: Waiting on PR

#343 iOS supports needsOffscreenAlphaCompositing
  docs/view.md
Labels: :clock1: Waiting on PR

#473 Updating AppRegistry.md to add documentation for new methods
  docs/appregistry.md
Labels: :clock1: Waiting on PR

#655 Accessibility Escape
  docs/accessibility.md
  docs/view.md
Labels: :clock1: Waiting on PR

#720 android, textInput: Add doc for `importantForAutofill`.
  docs/textinput.md
Labels: :clock1: Waiting on PR
