Repository facebook/react-native-website, pull requests merged in 2019-12, with the labels that each got.

#1490 Fix Android Oreo version wording in Text docs
  docs/text.md
  website/versioned_docs/version-0.60/text.md
Labels: Partner, RN Team, p: Facebook

#1496 Restructuring Guides IA and adding new sidebar to Docs
  website/i18n/en.json
  website/sidebars.json
  website/static/css/toc.css
Labels: Partner, p: Facebook

#1505 Bump Docusaurus version to 1.14.3
  website/package.json
  website/yarn.lock
Labels: Partner, RN Team, p: Facebook

#1347 modal.md - add translucent statusbar option
  docs/modal.md
Labels: Wait on future Release

#1295 Updated docs to reflect exceptions when using the Linking API in Simulator
  docs/linking.md
Labels: Wait on future Release

#1240 fix: Snack samples from progress things
  docs/progressbarandroid.md
  docs/progressviewios.md
Labels: Partner, p: callstack

#1528 Removing references to next pages
  docs/handling-touches.md
Labels: Partner, p: Facebook
