Repository facebook/react-native-website, pull requests merged in 2019-05, with the labels that each got.

#905 Remove references to Nuclide in Getting Started
  docs/getting-started.md
Labels: contributor

#904 Blog post for F8 video + podcast.
  website/blog/2019-05-01-react-native-at-f8-and-podcast.md
  website/blog/assets/eli-at-f8.png
Labels: p: facebook, partner, rn team

#921 Remove Contributing section, redirect to GitHub repository
  docs/building-from-source.md
  docs/contributing.md
  docs/maintainers.md
  docs/publishing.md
  docs/testing.md
  website/i18n/en.json
  website/sidebars.json
  website/static/docs/building-from-source.html
  website/static/docs/contributing.html
  website/static/docs/maintainers.html
  website/static/docs/publishing-forks.html
  website/static/docs/testing.html
  website/static/docs/understanding-cli.html
  website/versionedDocsBlacklist.json
  website/versioned_docs/version-0.5/building-from-source.md
  website/versioned_docs/version-0.5/contributing.md
  website/versioned_docs/version-0.5/maintainers.md
  website/versioned_docs/version-0.5/testing.md
  website/versioned_docs/version-0.5/understanding-cli.md
  website/versioned_sidebars/version-0.10-sidebars.json
  website/versioned_sidebars/version-0.11-sidebars.json
  website/versioned_sidebars/version-0.12-sidebars.json
  website/versioned_sidebars/version-0.13-sidebars.json
  website/versioned_sidebars/version-0.14-sidebars.json
  website/versioned_sidebars/version-0.15-sidebars.json
  website/versioned_sidebars/version-0.18-sidebars.json
  website/versioned_sidebars/version-0.19-sidebars.json
  website/versioned_sidebars/version-0.20-sidebars.json
  website/versioned_sidebars/version-0.22-sidebars.json
  website/versioned_sidebars/version-0.24-sidebars.json
  website/versioned_sidebars/version-0.26-sidebars.json
  website/versioned_sidebars/version-0.28-sidebars.json
  website/versioned_sidebars/version-0.29-sidebars.json
  website/versioned_sidebars/version-0.32-sidebars.json
  website/versioned_sidebars/version-0.33-sidebars.json
  website/versioned_sidebars/version-0.36-sidebars.json
  website/versioned_sidebars/version-0.37-sidebars.json
  website/versioned_sidebars/version-0.44-sidebars.json
  website/versioned_sidebars/version-0.46-sidebars.json
  website/versioned_sidebars/version-0.48-sidebars.json
  website/versioned_sidebars/version-0.5-sidebars.json
  website/versioned_sidebars/version-0.50-sidebars.json
  website/versioned_sidebars/version-0.52-sidebars.json
  website/versioned_sidebars/version-0.53-sidebars.json
  website/versioned_sidebars/version-0.54-sidebars.json
  website/versioned_sidebars/version-0.55-sidebars.json
  website/versioned_sidebars/version-0.56-sidebars.json
  website/versioned_sidebars/version-0.57-sidebars.json
  website/versioned_sidebars/version-0.59-sidebars.json
  website/versioned_sidebars/version-0.6-sidebars.json
Labels: Partner, RN Team, p: Facebook

#924 Removed outdated documentation.
  docs/backandroid.md
  docs/imagestore.md
  docs/listview.md
  docs/listviewdatasource.md
  docs/maskedviewios.md
  docs/snapshotviewios.md
  docs/vibrationios.md
  website/i18n/en.json
  website/sidebars.json
Labels: Partner, RN Team, p: Facebook

#926 Add link to Contributor Guide in website footer
  website/core/Footer.js
Labels: Partner, RN Team, p: Facebook

#930 Remove more outdated docs.
  docs/geolocation.md
  docs/navigator.md
  docs/netinfo.md
  docs/webview.md
  website/sidebars.json
Labels: Partner, RN Team, p: Facebook

#932 Emphasize non-Oracle OpenJDK distributions in Getting Started guide
  CONTRIBUTING.md
  docs/getting-started.md
Labels: sony

#934 Update Docusaurus to 1.9.0
  docs/animations.md
  docs/debugging.md
  docs/getting-started.md
  docs/more-resources.md
  website/package.json
  website/pages/en/versions.js
  website/siteConfig.js
  website/versioned_docs/version-0.58/geolocation.md
  website/versioned_docs/version-0.58/listview.md
  website/yarn.lock
Labels: Partner, p: Facebook

#936 Remove the "Guidelines for Text".
  CONTRIBUTING.md
Labels: Partner, RN Team, p: Facebook

#952 [Infra] Add 0.59/Linking to en.json
  website/i18n/en.json
Labels: Partner, RN Team, p: Facebook

#951 [Help] Add React Native Show
  website/pages/en/help.js
Labels: Partner, RN Team, p: Facebook

#953 [Formatting] Run prettier
  docs/datepickerios.md
  docs/flatlist.md
  docs/linking.md
  docs/navigation.md
  docs/state.md
  docs/view.md
  website/versioned_docs/version-0.59/linking.md
Labels: Partner, RN Team, p: Facebook

#962 Split up Docs and API
  website/i18n/en.json
  website/sidebars.json
  website/siteConfig.js
  website/versioned_sidebars/version-0.59-sidebars.json
Labels: Partner, p: Facebook

#967 Cut 0.60 docs version
  website/siteConfig.js
  website/versioned_docs/version-0.60/accessibility.md
  website/versioned_docs/version-0.60/accessibilityinfo.md
  website/versioned_docs/version-0.60/actionsheetios.md
  website/versioned_docs/version-0.60/activityindicator.md
  website/versioned_docs/version-0.60/alert.md
  website/versioned_docs/version-0.60/animations.md
  website/versioned_docs/version-0.60/appregistry.md
  website/versioned_docs/version-0.60/backhandler.md
  website/versioned_docs/version-0.60/communication-android.md
  website/versioned_docs/version-0.60/components-and-apis.md
  website/versioned_docs/version-0.60/datepickerios.md
  website/versioned_docs/version-0.60/debugging.md
  website/versioned_docs/version-0.60/direct-manipulation.md
  website/versioned_docs/version-0.60/easing.md
  website/versioned_docs/version-0.60/flatlist.md
  website/versioned_docs/version-0.60/getting-started.md
  website/versioned_docs/version-0.60/image.md
  website/versioned_docs/version-0.60/imagepickerios.md
  website/versioned_docs/version-0.60/layout-props.md
  website/versioned_docs/version-0.60/layoutanimation.md
  website/versioned_docs/version-0.60/modal.md
  website/versioned_docs/version-0.60/more-resources.md
  website/versioned_docs/version-0.60/native-modules-android.md
  website/versioned_docs/version-0.60/navigation.md
  website/versioned_docs/version-0.60/performance.md
  website/versioned_docs/version-0.60/pushnotificationios.md
  website/versioned_docs/version-0.60/scrollview.md
  website/versioned_docs/version-0.60/sectionlist.md
  website/versioned_docs/version-0.60/signed-apk-android.md
  website/versioned_docs/version-0.60/state.md
  website/versioned_docs/version-0.60/statusbar.md
  website/versioned_docs/version-0.60/switch.md
  website/versioned_docs/version-0.60/systrace.md
  website/versioned_docs/version-0.60/text.md
  website/versioned_docs/version-0.60/textinput.md
  website/versioned_docs/version-0.60/timers.md
  website/versioned_docs/version-0.60/touchablewithoutfeedback.md
  website/versioned_docs/version-0.60/transforms.md
  website/versioned_docs/version-0.60/view-style-props.md
  website/versioned_docs/version-0.60/view.md
  website/versioned_docs/version-0.60/virtualizedlist.md
  website/versioned_sidebars/version-0.60-sidebars.json
  website/versions.json
Labels: Partner, RN Team, p: Facebook

#816 chore(doc) remove cameraroll doc from react native website
  docs/cameraroll.md
  docs/components-and-apis.md
  docs/images.md
  website/i18n/en.json
  website/sidebars.json
Labels: Wait on future Release

#973 Set back the default to 59
  website/siteConfig.js
Labels: Contributor

#975 [CI] Migrate to Circle CI 2.1
  .circleci/config.yml
Labels: Partner, RN Team, p: Facebook

#977 Update Docusaurus to v1.11.0
  website/package.json
  website/yarn.lock
Labels: Partner, p: Facebook
