Repository facebook/react-native-website, pull requests merged in 2019-10, with the labels that each got.

#1299 Revert "Adding banner for docs survey, please remove in 2 weeks"
  website/siteConfig.js
  website/static/css/header.css
  website/static/js/2019_docs-survey.js
Labels: Partner, p: Facebook

#1273 Assorted Expo-related updates
  docs/appregistry.md
  docs/debugging.md
  docs/getting-started.md
  docs/linking.md
  docs/permissionsandroid.md
  docs/pushnotificationios.md
  website/versioned_docs/version-0.5/debugging.md
  website/versioned_docs/version-0.5/getting-started.md
  website/versioned_docs/version-0.60/appregistry.md
  website/versioned_docs/version-0.60/linking.md
  website/versioned_docs/version-0.60/permissionsandroid.md
  website/versioned_docs/version-0.60/pushnotificationios.md
Labels: Partner, p: expo

#1292 Use vanity URL for Reactiflux
  website/pages/en/help.js
Labels: sony

#1336 Update typescript.md with a md typo fix
  docs/typescript.md
Labels: Partner, p: microsoft

#1363 Adding styleguide for contributing writers
  README.md
  STYLEGUIDE.md
Labels: Partner, p: Facebook

#1393 Add 0.58 to .alexignore
  .alexignore
  website/versioned_docs/version-0.58/drawerlayoutandroid.md
  website/versioned_docs/version-0.58/navigatorios.md
  website/versioned_docs/version-0.58/scrollview.md
Labels: Partner, RN Team, p: Facebook
