Repository facebook/react-native-website, pull requests merged in 2019-09, with the labels that each got.

#1180 Adjust getting started wording
  docs/getting-started.md
  website/versioned_docs/version-0.60/getting-started.md
Labels: Partner, p: expo

#1209 Republish 0.60
  website/versioned_docs/version-0.60/accessibility.md
  website/versioned_docs/version-0.60/activityindicator.md
  website/versioned_docs/version-0.60/alertios.md
  website/versioned_docs/version-0.60/animations.md
  website/versioned_docs/version-0.60/backhandler.md
  website/versioned_docs/version-0.60/button.md
  website/versioned_docs/version-0.60/communication-android.md
  website/versioned_docs/version-0.60/communication-ios.md
  website/versioned_docs/version-0.60/components-and-apis.md
  website/versioned_docs/version-0.60/datepickerandroid.md
  website/versioned_docs/version-0.60/datepickerios.md
  website/versioned_docs/version-0.60/direct-manipulation.md
  website/versioned_docs/version-0.60/easing.md
  website/versioned_docs/version-0.60/flatlist.md
  website/versioned_docs/version-0.60/flexbox.md
  website/versioned_docs/version-0.60/getting-started.md
  website/versioned_docs/version-0.60/height-and-width.md
  website/versioned_docs/version-0.60/hermes.md
  website/versioned_docs/version-0.60/image.md
  website/versioned_docs/version-0.60/imagebackground.md
  website/versioned_docs/version-0.60/imageeditor.md
  website/versioned_docs/version-0.60/imagepickerios.md
  website/versioned_docs/version-0.60/inputaccessoryview.md
  website/versioned_docs/version-0.60/integration-with-existing-apps.md
  website/versioned_docs/version-0.60/javascript-environment.md
  website/versioned_docs/version-0.60/keyboardavoidingview.md
  website/versioned_docs/version-0.60/layoutanimation.md
  website/versioned_docs/version-0.60/linking.md
  website/versioned_docs/version-0.60/native-modules-android.md
  website/versioned_docs/version-0.60/native-modules-setup.md
  website/versioned_docs/version-0.60/navigation.md
  website/versioned_docs/version-0.60/network.md
  website/versioned_docs/version-0.60/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.60/performance.md
  website/versioned_docs/version-0.60/pickerios.md
  website/versioned_docs/version-0.60/props.md
  website/versioned_docs/version-0.60/pushnotificationios.md
  website/versioned_docs/version-0.60/removing-default-permissions.md
  website/versioned_docs/version-0.60/scrollview.md
  website/versioned_docs/version-0.60/sectionlist.md
  website/versioned_docs/version-0.60/segmentedcontrolios.md
  website/versioned_docs/version-0.60/share.md
  website/versioned_docs/version-0.60/statusbarios.md
  website/versioned_docs/version-0.60/stylesheet.md
  website/versioned_docs/version-0.60/switch.md
  website/versioned_docs/version-0.60/textinput.md
  website/versioned_docs/version-0.60/timepickerandroid.md
  website/versioned_docs/version-0.60/toastandroid.md
  website/versioned_docs/version-0.60/touchableopacity.md
  website/versioned_docs/version-0.60/touchablewithoutfeedback.md
  website/versioned_docs/version-0.60/tutorial.md
  website/versioned_docs/version-0.60/typescript.md
  website/versioned_docs/version-0.60/upgrading.md
  website/versioned_docs/version-0.60/view.md
  website/versioned_docs/version-0.60/virtualizedlist.md
  website/versioned_sidebars/version-0.60-sidebars.json
Labels: Contributor

#1213 Display a right side nav
  website/core/RemarkablePlugins.js
  website/siteConfig.js
Labels: Contributor

#1225 Set allowFullScreen to Eli's talk
  website/pages/en/index.js
Labels: Contributor

#1218 imp: Replace img with snack example
  docs/button.md
  website/versioned_docs/version-0.60/button.md
Labels: Partner, p: callstack

#1232 Improve design of Components and APIs page
  docs/components-and-apis.md
  website/static/css/react-native.css
Labels: Contributor

#1229 Update links related to React Conf
  website/pages/en/help.js
Labels: Contributor

#1231 Split components and APIs grid in 2 or 3
  website/static/css/react-native.css
Labels: Contributor

#1221 imp: Add snack examples to FlatList
  docs/flatlist.md
  website/versioned_docs/version-0.60/flatlist.md
Labels: Partner, p: callstack

#1263 Adding banner for docs survey, please remove in 2 weeks
  website/siteConfig.js
  website/static/css/header.css
  website/static/js/2019_docs-survey.js
Labels: Partner, p: Facebook

#1226 Update dependencies
  website/core/RemarkablePlugins.js
  website/package.json
  website/static/css/toc.css
  website/yarn.lock
Labels: Contributor

#1242 imp: snack example for RefreshControl, SafeAreaView and ScrollView
  docs/refreshcontrol.md
  docs/safeareaview.md
  docs/scrollview.md
Labels: Partner, p: callstack

#1245 Explicitly mention how to upgrade RN when switching to Hermes
  docs/hermes.md
Labels: Partner, p: Facebook

#1247 imp: Snack example for SectionList
  docs/sectionlist.md
Labels: Partner, p: callstack

#1265 s/fadeAdmin/fadeAnim
  docs/animations.md
  website/versioned_docs/version-0.5/animations.md
Labels: Contributor

#1266 Improve Optimizing FlatList page
  docs/optimizing-flatlist-configuration.md
Labels: Contributor

#1267 Remove WebView from components-and-apis
  docs/components-and-apis.md
Labels: Contributor

#1268 Change the order of Optimizing FlatList
  website/sidebars.json
  website/versioned_sidebars/version-0.60-sidebars.json
Labels: Contributor

#1269 Replace tag ending with </button>
  docs/getting-started.md
  website/versioned_docs/version-0.5/getting-started.md
Labels: Contributor

#1270 Republish 0.60
  docs/native-modules-android.md
  docs/navigation.md
  website/versionedDocsBlacklist.json
  website/versioned_docs/version-0.5/components-and-apis.md
  website/versioned_docs/version-0.5/height-and-width.md
  website/versioned_docs/version-0.5/native-modules-android.md
  website/versioned_docs/version-0.5/navigation.md
  website/versioned_docs/version-0.5/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.60/hermes.md
  website/versioned_docs/version-0.60/inputaccessoryview.md
  website/versioned_docs/version-0.60/out-of-tree-platforms.md
  website/versioned_docs/version-0.60/refreshcontrol.md
  website/versioned_docs/version-0.60/safeareaview.md
  website/versioned_docs/version-0.60/scrollview.md
  website/versioned_docs/version-0.60/sectionlist.md
Labels: Contributor

#1276 Add 0.61 blog post
  website/blog/2019-09-18-version-0.61.md
Labels: Partner, RN Team, p: Facebook

#1282 Add guide for Fast Refresh
  docs/debugging.md
  docs/fast-refresh.md
  website/i18n/en.json
  website/sidebars.json
Labels: Partner, RN Team, p: Facebook

#1287 Add 0.61 docs
  website/i18n/en.json
  website/versioned_docs/version-0.61/debugging.md
  website/versioned_docs/version-0.61/fast-refresh.md
  website/versioned_sidebars/version-0.61-sidebars.json
  website/versions.json
Labels: Partner, p: Facebook
