Repository facebook/react-native-website, pull requests merged in 2019-04, with the labels that each got.

#359 Add dataDetectorType prop to Text for Android
  docs/text.md
Labels: :clock1: Waiting on PR

#873 chore: remove accessibilityComponentType and accessibilityTraits props
  docs/accessibility.md
  docs/view.md
Labels: :clock1: Waiting on PR

#903 Update flex description
  docs/layout-props.md
Labels: p: facebook, partner, rn team

#902 Recommend using Android App Bundle for publishing Android app
  docs/signed-apk-android.md
Labels: p: software mansion, partner
