Repository facebook/react-native-website, pull requests merged in 2019-11, with the labels that each got.

#1449 Adding GA tracking and user feedback input to docs pages.
  website/siteConfig.js
  website/static/css/footer.css
  website/static/js/docs-rating.js
Labels: Partner, p: Facebook

#1454 upgrading docusaurus to latest version
  website/package.json
  website/yarn.lock
Labels: Partner, p: Facebook

#1326 Update accessibility related APIs
  docs/accessibility.md
  docs/touchablewithoutfeedback.md
  docs/view.md
  website/versioned_docs/version-0.5/accessibility.md
  website/versioned_docs/version-0.60/text.md
  website/versioned_docs/version-0.60/touchablewithoutfeedback.md
  website/versioned_docs/version-0.60/view.md
Labels: Wait on future Release

#1429 Fix misnamed method headers / index entries (fixes #1428)
  website/versioned_docs/version-0.43/touchablenativefeedback.md
  website/versioned_docs/version-0.5/navigator.md
  website/versioned_docs/version-0.60/touchablenativefeedback.md
  website/versioned_docs/version-0.61/debugging.md
Labels: Partner, p: Facebook

#1435 Updates doc that causes propogation of inaccurate netinfo documentation
  website/versioned_docs/version-0.6/netinfo.md
Labels: Partner, p: Facebook

#1471 Fix satisfaction button parameters
  website/static/js/docs-rating.js
Labels: Partner, p: Facebook

#1473 Update intro sentence
  website/blog/2019-11-18-react-native-doctor.md
Labels: Partner, RN Team, p: Facebook
