Repository facebook/react-native-website, pull requests merged in 2020-07, with the labels that each got.

#2020 Replace YellowBox docs with LogBox docs.
  docs/debugging.md
Labels: CLA Signed, Partner, RN Team, p: Facebook

#2022 Update flatlist.md
  docs/flatlist.md
Labels: CLA Signed

#2015 Added missing argument in code snippet.
  docs/native-components-android.md
Labels: CLA Signed

#2023 Remove duplicate documentation property for statusBarTranslucent on Modal
  docs/modal.md
Labels: CLA Signed

#2018 Add an ability to slide up announcement bar on scroll
  website/static/css/header.css
  website/static/js/announcement.js
Labels: CLA Signed

#2010 remove unused variables declarations and parameters in different files.
  website/core/RemarkablePlugins.js
  website/pages/en/help.js
  website/static/js/codeblocks.js
Labels: CLA Signed

#2019 Fixed the Function Component Example
  docs/appstate.md
Labels: CLA Signed

#2024 Blog post for the 0.63 release
  website/blog/2020-07-06-version-0.63.md
  website/blog/assets/0.63-logbox.png
  website/static/css/blog.css
Labels: CLA Signed, Partner, p: callstack

#2027 Fix Alert API docs
  docs/alert.md
Labels: CLA Signed

#2007 adding docs for android_hyphenationStrategy
  docs/text.md
Labels: CLA Signed, Wait on future Release

#2008 updated default folder location for Android Sdk in Windows
  docs/getting-started.md
Labels: CLA Signed

#2034 Link to the actual Upgrade Helper, not the GitHub repo for it
  docs/upgrading.md
Labels: CLA Signed

#2035 Update Android version in environment setup
  docs/getting-started.md
  website/versioned_docs/version-0.63/getting-started.md
Labels: CLA Signed

#2036 Fixed some minor typos
  docs/pressevent.md
Labels: CLA Signed

#2037 Fixed a minor typo
  docs/pressable.md
Labels: CLA Signed

#2043 Fixed bug in AlignItems.
  docs/flexbox.md
  website/versioned_docs/version-0.63/flexbox.md
Labels: CLA Signed

#2042 (Accessibility) fix some cases
  docs/accessibility.md
  website/versioned_docs/version-0.5/accessibility.md
  website/versioned_docs/version-0.62/accessibility.md
  website/versioned_docs/version-0.63/accessibility.md
Labels: CLA Signed

#2045 Fixed a minor typo
  website/versioned_docs/version-0.63/pressable.md
Labels: CLA Signed

#2046 Fixed some minor typos
  website/versioned_docs/version-0.63/pressevent.md
Labels: CLA Signed

#2047 Update Android version in environment setup
  docs/getting-started.md
  website/versioned_docs/version-0.63/getting-started.md
Labels: CLA Signed

#2028 fix link in hermes docs, metro configuration link.
  website/versioned_docs/version-0.62/hermes.md
Labels: CLA Signed

#2052 Fix missing "in" in intro-react.md
  docs/intro-react.md
Labels: CLA Signed

#2051 Modify duplicate code block in intro-react.md
  docs/intro-react.md
Labels: CLA Signed

#2041 Clarify <Pressible> Docs
  docs/pressable.md
Labels: CLA Signed

#2039 Quick Grammatical change
  website/pages/en/index.js
Labels: CLA Signed

#2038 Update textinput.md grammar for importantForAutofill description
  docs/textinput.md
Labels: CLA Signed

#1959 replace "required" column in code reference with special label
  docs/activityindicator.md
  docs/button.md
  docs/pressable.md
  website/static/css/docs.css
Labels: CLA Signed, Design

#2031 Update LaunchScreen pro tip to use Storyboard
  docs/running-on-device.md
Labels: CLA Signed

#2026 replace state usage comparison image with the code blocks
  docs/tutorial.md
  website/static/css/docs.css
Labels: CLA Signed

#2055 Updated StatusBar currentHeight description regarding issue #2049
  docs/statusbar.md
Labels: CLA Signed

#2060 disable web platform preview for the Switch component
  docs/switch.md
  website/versioned_docs/version-0.62/switch.md
  website/versioned_docs/version-0.63/switch.md
Labels: CLA Signed

#2063 Fix typo :zap:
  docs/debugging.md
Labels: CLA Signed

#2072 Clarify android environment variables for macOS and Linux
  docs/getting-started.md
Labels: CLA Signed

#2074 fix and update few links
  docs/typescript.md
  website/pages/en/showcase.js
Labels: CLA Signed

#2078 Fixing the broken link for the RTL Example
  website/blog/2016-08-19-right-to-left-support-for-react-native-apps.md
Labels: CLA Signed

#2075 Add `expo-secure-store` to a list of libraries to consider for secure storage
  docs/security.md
Labels: CLA Signed

#2077 Make a small correction to Principles blog post
  website/blog/2020-07-17-react-native-principles.md
Labels: CLA Signed

#2087 Update getting-started.md
  docs/getting-started.md
Labels: CLA Signed

#2084 update Text Style Props, replace inline listing with link on Text website
  docs/text-style-props.md
  docs/text.md
  website/versioned_docs/version-0.60/text.md
  website/versioned_docs/version-0.62/text.md
  website/versioned_docs/version-0.63/text.md
Labels: CLA Signed

#2064 Docs update blog post and annual survey link
  website/blog/2020-07-23-docs-update.md
  website/siteConfig.js
  website/static/css/header.css
  website/static/js/survey-banner.js
Labels: CLA Signed, Partner, RN Team, p: Facebook

#2053 Minor wording changes in PlatformColor.md
  docs/platformcolor.md
Labels: CLA Signed

#2090 Update pressable.md
  docs/pressable.md
Labels: CLA Signed

#2095 Fix typo in javascript-environment.md
  docs/javascript-environment.md
Labels: CLA Signed

#2059 update StatusBar example and docs
  docs/statusbar.md
  website/static/css/docs.css
Labels: CLA Signed

#2093 update PixelRatio.md with new devices description.
  docs/pixelratio.md
Labels: CLA Signed

#2085 Update instructions for enabling developer options on Android.
  docs/running-on-device.md
  website/versioned_docs/version-0.5/running-on-device.md
Labels: CLA Signed

#2097 Removing Video show from Help
  website/pages/en/help.js
Labels: CLA Signed, Partner, RN Team, p: Facebook

#2096 Backport #2075 to 0.63
  website/versioned_docs/version-0.63/security.md
Labels: CLA Signed, Partner, p: expo

#2098 Fix scrolling bug in side nav
  website/static/css/docs.css
Labels: CLA Signed

#2070 Updated Android Environment setup
  docs/getting-started.md
Labels: CLA Signed

#2099 fix simple typo
  docs/native-components-android.md
Labels: CLA Signed

#2106 fix CameraRoll edit button
  website/versioned_docs/version-0.58/cameraroll.md
Labels: CLA Signed

#2105 remove broken on-page sidebar from Running on Device page
  docs/running-on-device.md
  website/versioned_docs/version-0.62/running-on-device.md
Labels: CLA Signed

#2108 fix typo in blog post
  website/blog/2020-07-23-docs-update.md
Labels: CLA Signed

#2109 Correct anchor height offset for Black Lives Matter banner
  website/static/css/header.css
Labels: CLA Signed

#2104 fix Environment Setup page sections, backport all the changes to 0.63
  docs/getting-started.md
  website/versioned_docs/version-0.63/getting-started.md
Labels: CLA Signed

#2110 Minor grammar fix in Introduction
  docs/intro-react-native-components.md
Labels: CLA Signed

#2102 Small improvement / error fix in using-a-scrollView.md
  docs/using-a-scrollview.md
Labels: CLA Signed

#2103 update the Image Style Props page
  docs/image-style-props.md
Labels: CLA Signed

#2100 update RefreshControl page, fix minor platform labels display issues
  docs/refreshcontrol.md
  website/static/css/docs.css
  website/static/css/react-native.css
Labels: CLA Signed

#2083 Update security.md
  docs/security.md
Labels: CLA Signed

#2112 Adding Will Holen's doc on symbolication
  docs/symbolication.md
  website/i18n/en.json
  website/sidebars.json
Labels: CLA Signed, Partner, RN Team, p: Facebook

#2114 not sure if intentional 😉
  website/versioned_docs/version-0.63/debugging.md
Labels: CLA Signed

#2117 Update share.md
  docs/share.md
Labels: CLA Signed
