Repository facebook/react-native-website, pull requests merged in 2020-10, with the labels that each got.

#2233 Improved README.md
  README.md
Labels: CLA Signed

#2232 fix typo
  docs/typescript.md
Labels: CLA Signed

#2228 Add Shopify and Tableau to showcase
  website/showcase.json
  website/static/img/showcase/shopify.png
  website/static/img/showcase/tableau.png
Labels: CLA Signed, Partner, p: Facebook

#2241 updated debugging.md
  docs/debugging.md
Labels: CLA Signed

#2246 Update appregistry.md
  docs/appregistry.md
Labels: CLA Signed

#2243 Update out-of-tree-platforms.md
  docs/out-of-tree-platforms.md
Labels: CLA Signed, Partner, p: microsoft

#2250 Remove unnecessary python dependency
  docs/getting-started.md
Labels: CLA Signed

#2245 Update network.md to show android non ssl block
  docs/network.md
Labels: CLA Signed

#2244 remove link in native-modules-ios
  docs/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-ios.md
Labels: CLA Signed

#2249 Update textinput.md
  docs/textinput.md
Labels: CLA Signed

#2268 Netlify publish dir should be relative to base dir
  netlify.toml
Labels: CLA Signed

#2273 fix Docusaurus v2 CircleCI/GH-pages deployment
  .circleci/config.yml
  website/docusaurus.config.js
  website/package.json
  website/static/.nojekyll
Labels: CLA Signed

#2272 archive.reactnative.dev => update algolia index name
  website/siteConfig.js
Labels: CLA Signed, 📚 Archive

#2277 Try fix deployment
  website/docusaurus.config.js
Labels: CLA Signed

#2278 fix deployment CNAME
  website/docusaurus.config.js
  website/static/CNAME
Labels: CLA Signed

#2271 Remove useless v1 translation file
  website/i18n/en.json
Labels: CLA Signed

#2266 fixes equality operator used in platform test
  docs/keyboardavoidingview.md
Labels: CLA Signed

#2274 simplify snackPlayerInitializer integration, remove useless sitePlugin
  website/docusaurus.config.js
  website/sitePlugin.js
Labels: CLA Signed

#2258 docs: fix url of transferred repositories
  docs/clipboard.md
  docs/pickerios.md
  docs/progressbarandroid.md
  website/versioned_docs/version-0.61/clipboard.md
  website/versioned_docs/version-0.61/pickerios.md
  website/versioned_docs/version-0.61/progressbarandroid.md
  website/versioned_docs/version-0.61/progressviewios.md
  website/versioned_docs/version-0.62/clipboard.md
  website/versioned_docs/version-0.62/picker.md
  website/versioned_docs/version-0.62/progressbarandroid.md
  website/versioned_docs/version-0.62/progressviewios.md
  website/versioned_docs/version-0.63/picker.md
  website/versioned_docs/version-0.63/progressbarandroid.md
  website/versioned_docs/version-0.63/progressviewios.md
Labels: CLA Signed

#2264 [docs] use emulator instead of simulator when referring to avd
  docs/building-for-tv.md
Labels: CLA Signed

#2251 docs: change url for react-native-segmented-control
  docs/segmentedcontrolios.md
  website/versioned_docs/version-0.60/segmentedcontrolios.md
  website/versioned_docs/version-0.61/segmentedcontrolios.md
  website/versioned_docs/version-0.63/segmentedcontrolios.md
Labels: CLA Signed

#2252 update PixelRatio iOS description.
  docs/pixelratio.md
Labels: CLA Signed

#2259 Update tutorial.md
  docs/tutorial.md
Labels: CLA Signed

#2247 Add snack for the Pressable
  docs/pressable.md
  website/versioned_docs/version-0.63/pressable.md
Labels: CLA Signed

#2280 fex few homepage issues, mainly on mobile devices
  website/src/css/customTheme.scss
  website/src/css/index.scss
  website/src/pages/index.js
  website/static/img/homepage/cross-platform.svg
Labels: CLA Signed

#2281 fix few reported mobile issues
  website/src/css/customTheme.scss
  website/src/css/index.scss
  website/src/pages/index.js
Labels: CLA Signed

#2279 remove few files, cleanup scripts and meta files after the migration
  .gitignore
  website/docusaurus.config.js
  website/netlify-reduce-versions.js
  website/package.json
  website/sync-community-repos.js
  website/sync-guides.js
  website/versionedDocsBlacklist.json
  website/yarn.lock
Labels: CLA Signed

#2284 wrong prop usage fixed
  docs/tutorial.md
  website/versioned_docs/version-0.63/tutorial.md
Labels: CLA Signed

#2282 fix homepage animations
  website/src/pages/animations/_dissectionAnimation.js
  website/src/pages/animations/_headerAnimation.js
  website/src/pages/index.js
Labels: CLA Signed

#2288 add docusaurus serve
  website/package.json
Labels: CLA Signed

#2289 fix homepage community section links
  website/src/pages/index.js
Labels: CLA Signed

#2296 add blog posts feeds
  website/docusaurus.config.js
Labels: CLA Signed

#2297 attempt to fix trailing slash issues on GH pages
  website/docusaurus.config.js
  website/sitePlugin.js
  website/snackPlayerInitializer.js
  website/src/theme/Layout.js
  website/static/.nojekyll
Labels: CLA Signed
