Repository facebook/react-native-website, pull requests merged in 2020-09, with the labels that each got.

#2189 Modernize code examples in the direct manipulation section
  docs/direct-manipulation.md
Labels: CLA Signed, Partner, p: Facebook

#2184 update Alert API page, include iOS specific functions from deprecated AlertIOS
  docs/alert.md
Labels: CLA Signed

#2194 Update getting-started.md
  docs/getting-started.md
Labels: CLA Signed

#2185 fix homepage showcase app list graphical issue
  website/static/css/homepage/AppList.css
Labels: CLA Signed, Design

#2197 docs: add matrix to transform
  docs/transforms.md
  website/versioned_docs/version-0.62/transforms.md
  website/versioned_docs/version-0.63/transforms.md
Labels: CLA Signed

#2202 Typo fix
  docs/optimizing-flatlist-configuration.md
Labels: CLA Signed

#2199 docs: update deprecated usage of findNodeHandle in measureLayout
  docs/direct-manipulation.md
Labels: CLA Signed

#2205 TextInput: Add new `onPressIn` and `onPressOut` docs
  docs/textinput.md
Labels: CLA Signed

#2204 Fix typos
  docs/timers.md
Labels: CLA Signed

#2186 link out-of-tree platforms, add macOS platform, unify dashes on homepage
  website/pages/en/index.js
Labels: CLA Signed

#2191 update SectionList page, extract ViewToken, add labels
  docs/flatlist.md
  docs/sectionlist.md
  docs/viewtoken.md
  docs/virtualizedlist.md
  website/i18n/en.json
  website/sidebars.json
Labels: CLA Signed

#2203 Added workarounds for TextInputs
  docs/building-for-tv.md
Labels: CLA Signed

#2209 update Text page and add types, add LayoutEvent object page
  docs/image.md
  docs/layoutevent.md
  docs/text.md
  docs/textinput.md
  docs/touchablewithoutfeedback.md
  docs/view.md
  website/i18n/en.json
  website/sidebars.json
Labels: CLA Signed

#2207 Incorrect argument
  docs/signed-apk-android.md
Labels: CLA Signed

#2211 Updated ScrollView `disableIntervalMomentum` doc
  docs/scrollview.md
Labels: CLA Signed

#2213 Remove announcement banner.
  website/siteConfig.js
  website/static/css/header.css
  website/static/js/announcement.js
Labels: CLA Signed, Partner, RN Team, p: Facebook

#2216 Docs: Removing `onTextInput` prop from TextInput
  docs/textinput.md
  website/versioned_docs/version-0.62/textinput.md
  website/versioned_docs/version-0.63/textinput.md
Labels: CLA Signed

#2214 Signing not under General for me
  docs/running-on-device.md
Labels: CLA Signed

#2220 Update running-on-simulator-ios.md
  docs/running-on-simulator-ios.md
Labels: CLA Signed

#2221 [DOC] fixed errata in image doc
  docs/image.md
Labels: CLA Signed

#2225 Adding Android NDK Installation Guide
  docs/getting-started.md
Labels: CLA Signed, Wait on future Release

#2217 Docs: Integration with android fragment
  docs/integration-with-android-fragment.md
  website/sidebars.json
Labels: CLA Signed, Guest Docs

#1898 Add new option to ActionSheetIOS called disabledButtonsIndices
  docs/actionsheetios.md
Labels: :clock1: Waiting on PR, CLA Signed, Partner, Wait on future Release, p: callstack

#2136 Adding configureNext.onAnimationDidFail callback on LayoutAnimation
  docs/layoutanimation.md
Labels: CLA Signed, Wait on future Release

#2227 Added Coinbase to showcase
  website/showcase.json
  website/static/img/showcase/coinbase.png
Labels: CLA Signed, Partner, p: Facebook

#2226 0.63.3 release - update Pressable delay
  docs/pressable.md
  website/static/docs/assets/d_pressable_pressing.svg
  website/versioned_docs/version-0.63/pressable.md
Labels: CLA Signed
