Repository facebook/react-native-website, pull requests merged in 2020-05, with the labels that each got.

#1902 Add workflow page "Using Libraries"
  docs/components-and-apis.md
  docs/libraries.md
  website/i18n/en.json
  website/sidebars.json
  website/versioned_docs/version-0.62/components-and-apis.md
  website/versioned_docs/version-0.62/libraries.md
  website/versioned_sidebars/version-0.62-sidebars.json
Labels: Guest Docs, Major Contribution, Partner, p: expo

#1909 fix: add missing Appearance module APIs
  docs/appearance.md
  website/versioned_docs/version-0.62/appearance.md
Labels: Partner, p: callstack

#1910 fix: "refer to" rather than "refer"
  docs/components-and-apis.md
  website/versioned_docs/version-0.62/components-and-apis.md
Labels: Partner, p: expo

#1916 React Native packager -> Metro bundler
  docs/debugging.md
  docs/images.md
  docs/integration-with-existing-apps.md
  docs/signed-apk-android.md
  docs/troubleshooting.md
  website/versioned_docs/version-0.13/toolbarandroid.md
  website/versioned_docs/version-0.14/toolbarandroid.md
  website/versioned_docs/version-0.16/toolbarandroid.md
  website/versioned_docs/version-0.17/toolbarandroid.md
  website/versioned_docs/version-0.18/toolbarandroid.md
  website/versioned_docs/version-0.30/toolbarandroid.md
  website/versioned_docs/version-0.37/toolbarandroid.md
  website/versioned_docs/version-0.5/debugging.md
  website/versioned_docs/version-0.5/images.md
  website/versioned_docs/version-0.5/integration-with-existing-apps.md
  website/versioned_docs/version-0.5/signed-apk-android.md
  website/versioned_docs/version-0.5/toolbarandroid.md
  website/versioned_docs/version-0.5/troubleshooting.md
  website/versioned_docs/version-0.58/toolbarandroid.md
  website/versioned_docs/version-0.60/toolbarandroid.md
  website/versioned_docs/version-0.61/debugging.md
  website/versioned_docs/version-0.62/debugging.md
  website/versioned_docs/version-0.62/integration-with-existing-apps.md
  website/versioned_docs/version-0.62/signed-apk-android.md
  website/versioned_docs/version-0.62/troubleshooting.md
Labels: Partner, p: expo

#1906 add ability to highlight new pages in the sidebar
  website/static/css/docs.css
Labels: Design

#1934 Adding illustrations to security doc
  docs/assets/d_security_chart.svg
  docs/assets/d_security_deep-linking.svg
  docs/security.md
Labels: Partner, RN Team, p: Facebook

#1936 Adding the start of Object Types reference
  docs/rectorsize.md
  website/i18n/en.json
  website/sidebars.json
Labels: Partner, RN Team, p: Facebook

#1919 Adding stepped instructions for running RN application
  docs/getting-started.md
Labels: Partner, RN Team, p: Facebook

#1920 Add styling to the "Native Code Required" banners
  docs/appregistry.md
  docs/debugging.md
  docs/linking.md
  docs/permissionsandroid.md
  docs/pushnotificationios.md
  website/static/css/react-native.css
  website/static/img/expo-logo.svg
  website/versioned_docs/version-0.62/appregistry.md
  website/versioned_docs/version-0.62/debugging.md
  website/versioned_docs/version-0.62/linking.md
  website/versioned_docs/version-0.62/permissionsandroid.md
  website/versioned_docs/version-0.62/pushnotificationios.md
Labels: Design

#1939 update slightly feedback box and footer designs
  website/static/css/docs-prevnext.css
  website/static/css/docs.css
  website/static/css/footer.css
  website/static/css/react-native.css
Labels: Design

#1942 Tiny edits to pressable wording
  docs/pressable.md
Labels: Partner, RN Team, p: Facebook

#1951 Add light background to the search bar
  website/static/css/header.css
Labels: Design

#1944 Moving API and Components to their own sections
  website/i18n/en.json
  website/sidebars.json
  website/siteConfig.js
  website/versioned_sidebars/version-0.59-sidebars.json
  website/versioned_sidebars/version-0.60-sidebars.json
  website/versioned_sidebars/version-0.61-sidebars.json
  website/versioned_sidebars/version-0.62-sidebars.json
Labels: Partner, RN Team, p: Facebook

#1955 improved labels design + ActivityIndicator and Button pages tweaks
  docs/activityindicator.md
  docs/button.md
  website/static/css/docs.css
  website/static/css/react-native.css
Labels: Design
