Repository facebook/react-native-website, pull requests merged in 2020-11, with the labels that each got.

#2300 temporary fix .html ending links on the client side
  website/src/theme/Layout.js
Labels: CLA Signed

#2301 Bump minimum Node version to 12
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
Labels: CLA Signed, Partner, p: Facebook

#2302 [PlatformColor] updated supported colors section, updated example converted to snack
  docs/platformcolor.md
  website/versioned_docs/version-0.63/platformcolor.md
Labels: CLA Signed

#2299 Chaged from 'background' to 'backgroundColor'
  docs/layoutanimation.md
  website/versioned_docs/version-0.63/layoutanimation.md
Labels: CLA Signed

#2304 fix and update ImageBackground example
  docs/imagebackground.md
  website/versioned_docs/version-0.63/imagebackground.md
Labels: CLA Signed

#2306 [Core Components and APIs] fix android header, reorder sections, fix links
  docs/components-and-apis.md
  website/versioned_docs/version-0.63/components-and-apis.md
Labels: CLA Signed

#2307 move SafeAreaView to iOS components, fix sidebar in next docs
  docs/safeareaview.md
  website/sidebars.json
  website/versioned_docs/version-0.63/safeareaview.md
  website/versioned_sidebars/version-0.63-sidebars.json
Labels: CLA Signed

#2310 Fix RNTester broken links
  website/versioned_docs/version-0.60/animations.md
  website/versioned_docs/version-0.60/communication-ios.md
  website/versioned_docs/version-0.60/inputaccessoryview.md
  website/versioned_docs/version-0.60/panresponder.md
  website/versioned_docs/version-0.60/usecolorscheme.md
  website/versioned_docs/version-0.61/animations.md
  website/versioned_docs/version-0.61/communication-ios.md
  website/versioned_docs/version-0.61/inputaccessoryview.md
  website/versioned_docs/version-0.61/panresponder.md
  website/versioned_docs/version-0.61/usecolorscheme.md
  website/versioned_docs/version-0.62/animations.md
  website/versioned_docs/version-0.62/communication-ios.md
  website/versioned_docs/version-0.62/inputaccessoryview.md
  website/versioned_docs/version-0.62/panresponder.md
  website/versioned_docs/version-0.62/usecolorscheme.md
  website/versioned_docs/version-0.63/communication-ios.md
  website/versioned_docs/version-0.63/usecolorscheme.md
Labels: CLA Signed

#2311 chore: simplify parseParams in Snacks plugin, comment out few logs
  website/plugins/remark-snackplayer/package.json
  website/plugins/remark-snackplayer/src/index.js
  website/sitePlugin.js
  website/snackPlayerInitializer.js
  website/yarn.lock
Labels: CLA Signed

#2309 [image-component] add docu for method parameters and return value
  docs/image.md
Labels: CLA Signed

#2313 Fix typo under "Slow navigator transitions"
  docs/performance.md
  website/versioned_docs/version-0.63/performance.md
Labels: CLA Signed

#2314 Add link to Wix blog post
  website/showcase.json
Labels: CLA Signed, Partner, p: Facebook

#2317 Remove HAXM requirement
  docs/_getting-started-macos-android.md
Labels: CLA Signed

#2319 avoid confusing clipboard copy behavior
  website/versioned_docs/version-0.63/typescript.md
Labels: CLA Signed

#2316 add few package managers tabs, update few code blocks
  docs/_integration-with-exisiting-apps-objc.md
  docs/debugging.md
  docs/libraries.md
  docs/linking-libraries-ios.md
  docs/troubleshooting.md
Labels: CLA Signed

#2320 Update picker.md
  website/versioned_docs/version-0.63/picker.md
Labels: CLA Signed

#2321 [Typescript] port back changes from `next`
  website/versioned_docs/version-0.63/typescript.md
Labels: CLA Signed

#2327 remove removing-default-permissions page
  docs/removing-default-permissions.md
  docs/signed-apk-android.md
  website/sidebars.json
Labels: CLA Signed

#2328 attempt to fix CI OOM issues
  .circleci/config.yml
Labels: CLA Signed

#2322 [Image] update docs, add missing types, improve required label
  docs/alert.md
  docs/image.md
  website/docusaurus.config.js
  website/src/css/customTheme.scss
Labels: CLA Signed

#2323 use Yarn workspaces, convert sync-api-docs and remark Snack plugin
  netlify.toml
  package.json
  plugins/remark-snackplayer/README.md
  plugins/remark-snackplayer/package.json
  plugins/remark-snackplayer/src/index.js
  plugins/remark-snackplayer/tests/index.js
  plugins/remark-snackplayer/tests/markdown/test1.md
  plugins/remark-snackplayer/tests/markdown/test2.md
  plugins/remark-snackplayer/tests/output/output1.html
  plugins/remark-snackplayer/tests/output/output2.html
  sync-api-docs/extractDocsFromRN.js
  sync-api-docs/generateMarkdown.js
  sync-api-docs/magic.js
  sync-api-docs/package.json
  sync-api-docs/preprocessGeneratedApiDocs.js
  sync-api-docs/propFormatter.js
  sync-api-docs/sync-api-docs.js
  sync-api-docs/titleToId.js
  website/docusaurus.config.js
  website/package.json
  website/plugins/remark-snackplayer/yarn.lock
  yarn.lock
Labels: CLA Signed

#2329 Adding important privacys and ToS links for FB OSS
  website/docusaurus.config.js
Labels: CLA Signed, Partner, p: Facebook

#2331 cleanup after workspace introduction, fix remark-snackplayer tests
  .gitignore
  docs/layoutanimation.md
  package.json
  plugins/remark-snackplayer/README.md
  plugins/remark-snackplayer/package.json
  plugins/remark-snackplayer/tests/index.js
  sync-api-docs/package.json
  website/docusaurus.config.js
  website/package.json
  yarn.lock
Labels: CLA Signed

#2334 update Readme to match the workspace changes
  README.md
Labels: CLA Signed

#2333 tweak footer design to fit better four columns
  website/src/css/customTheme.scss
Labels: CLA Signed

#2324 [docs] fix: minor grammer changes
  docs/textinput.md
  website/versioned_docs/version-0.63/textinput.md
Labels: CLA Signed

#2326 updated react-native-dotenv link
  docs/security.md
  website/versioned_docs/version-0.62/security.md
  website/versioned_docs/version-0.63/security.md
Labels: CLA Signed

#2332 Update @react-native-community/async-storage url
  docs/asyncstorage.md
  website/versioned_docs/version-0.63/asyncstorage.md
Labels: CLA Signed, Needs Author Feedback

#2144 Code refactor and add method parsing
  sync-api-docs/extractDocsFromRN.js
  sync-api-docs/generateMarkdown.js
  sync-api-docs/magic.js
  sync-api-docs/methodFormatter.js
  sync-api-docs/propFormatter.js
  sync-api-docs/sync-api-docs.js
  sync-api-docs/utils.js
Labels: CLA Signed

#2336 format sync-api code with Prettier, remove unused file
  sync-api-docs/propFormatter.js
  sync-api-docs/titleToId.js
Labels: CLA Signed

#2330 Adding Words With Friends 2 logo for Zynga blog showcase
  website/showcase.json
  website/static/img/showcase/words2.png
Labels: CLA Signed

#2335 Fix wrong boolean in docs
  docs/textinput.md
  website/versioned_docs/version-0.63/textinput.md
Labels: CLA Signed

#2212 Update inline requires doc for upcoming API change
  docs/ram-bundles-inline-requires.md
Labels: CLA Signed, Partner, RN Team, Wait on future Release, p: Facebook

#2340 Update navigation.md
  docs/navigation.md
  website/versioned_docs/version-0.63/navigation.md
Labels: CLA Signed

#2341 update the versions page
  website/src/css/versions.scss
  website/src/pages/versions.js
Labels: CLA Signed

#2337 StickyHeaderIndices updated with missing info
  docs/scrollview.md
  website/versioned_docs/version-0.63/scrollview.md
Labels: CLA Signed

#2345 Fixed devDependencies flag in yarn command
  docs/typescript.md
  website/versioned_docs/version-0.63/typescript.md
Labels: CLA Signed

#2346 Update text color for dissection images
  design/Illustrations/dissection_images.psd
  website/static/img/homepage/dissection/1.png
  website/static/img/homepage/dissection/2.png
  website/static/img/homepage/dissection/3.png
Labels: CLA Signed, Design

#2343 Fix Linking docs
  website/versioned_docs/version-0.62/linking.md
  website/versioned_docs/version-0.63/linking.md
Labels: CLA Signed

#2347 [docs]: minor grammar change
  docs/headless-js-android.md
  docs/navigation.md
  website/versioned_docs/version-0.63/headless-js-android.md
  website/versioned_docs/version-0.63/navigation.md
Labels: CLA Signed

#2348 add basic styling for figure and figcaption elements
  website/src/css/customTheme.scss
Labels: CLA Signed

#2351 Minor grammar correction to tutorial.md
  website/versioned_docs/version-0.62/tutorial.md
  website/versioned_docs/version-0.63/tutorial.md
Labels: CLA Signed

#2357 Update running-on-device.md
  docs/running-on-device.md
  website/versioned_docs/version-0.63/running-on-device.md
Labels: CLA Signed

#2354 update link name in MaskedViewIOS
  website/versioned_docs/version-0.63/maskedviewios.md
Labels: CLA Signed

#2358 add temporary fix for navbar overflow issue
  website/src/css/customTheme.scss
Labels: CLA Signed

#2359 small tweaks for the docs sidebar styling
  website/src/css/customTheme.scss
Labels: CLA Signed

#2339 add simple React Native logo animation
  website/src/css/customTheme.scss
Labels: CLA Signed, Design
