Repository facebook/react-native-website, pull requests merged in 2020-03, with the labels that each got.

#1574 Clarify Vibration iOS API
  docs/vibration.md
Labels: Partner, RN Team, p: Facebook

#1611 design: use same color for tabs divider as used for TOC border
  website/static/css/tabs.css
Labels: design

#1469 Add testing guide - introduction / overview
  .alexrc.js
  docs/testing.md
  website/i18n/en.json
  website/sidebars.json
Labels: Guest Docs, Major Contribution

#1719 Clarify what a component and element are
  docs/intro-react.md
Labels: Partner, RN Team, p: Facebook

#1733 Illo fix
  design/illustrations/devices.ai
  design/illustrations/devices_arranged.ai
  design/illustrations/diagram_testing-varieties.ai
  docs/assets/p_android-ios-devices.svg
  docs/assets/p_tests-component.svg
  docs/assets/p_tests-e2e.svg
  docs/assets/p_tests-integration.svg
  docs/assets/p_tests-snapshot.svg
  docs/assets/p_tests-unit.svg
  docs/testing.md
Labels: Partner, RN Team, p: Facebook

#1736 Banner to link to environment setup
  docs/introduction.md
  website/static/css/docs.css
Labels: Partner, RN Team, p: Facebook

#1633 Add security documentation
  docs/assets/oauth-pkce.png
  docs/security.md
  website/i18n/en.json
  website/sidebars.json
Labels: Guest Docs, Major Contribution

#1755 Split out useColorScheme
  docs/appearance.md
  docs/usecolorscheme.md
  website/i18n/en.json
  website/sidebars.json
Labels: Partner, RN Team, p: Facebook

#1767 Edit to `fadingEdgeLength`
  docs/scrollview.md
Labels: Partner, RN Team, p: Facebook

#1779 Adding deprecation notices to 0.61's sidebars
  design/Illustrations/illustrations_security.ai
  website/i18n/en.json
  website/sidebars.json
  website/versioned_docs/version-0.61/alertios.md
  website/versioned_docs/version-0.61/asyncstorage.md
  website/versioned_docs/version-0.61/clipboard.md
  website/versioned_docs/version-0.61/datepickerandroid.md
  website/versioned_docs/version-0.61/datepickerios.md
  website/versioned_docs/version-0.61/imageeditor.md
  website/versioned_docs/version-0.61/imagepickerios.md
  website/versioned_docs/version-0.61/pickerios.md
  website/versioned_docs/version-0.61/progressbarandroid.md
  website/versioned_docs/version-0.61/progressviewios.md
  website/versioned_docs/version-0.61/pushnotificationios.md
  website/versioned_docs/version-0.61/segmentedcontrolios.md
  website/versioned_docs/version-0.61/slider.md
  website/versioned_docs/version-0.61/statusbarios.md
  website/versioned_docs/version-0.61/timepickerandroid.md
  website/versioned_docs/version-0.61/viewpagerandroid.md
Labels: Partner, RN Team, p: Facebook

#1784 Update default version to 0.62
  website/siteConfig.js
Labels: Contributor, Wait on future Release

#1778 Add 0.62 blog post
  website/blog/2020-03-26-version-0.62.md
  website/blog/assets/0.62-flipper.png
Labels: :memo: Blog Post, Partner, RN Team, p: Facebook
