Repository facebook/react-native-website, pull requests merged in 2020-12, with the labels that each got.

#2344 Add Call of Duty Companion App, NerdWallet, Foreca, LendMN, and FlipKart into showcase
  website/showcase.json
  website/static/img/showcase/callofduty_companion.png
  website/static/img/showcase/flipkart.png
  website/static/img/showcase/foreca.png
  website/static/img/showcase/lendmn.png
  website/static/img/showcase/nerdwallet.png
Labels: CLA Signed, Partner, p: Facebook

#2353 Installation word spelling mistake
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-windows-android.md
  website/versioned_docs/version-0.60/_getting-started-linux-android.md
  website/versioned_docs/version-0.60/_getting-started-macos-android.md
  website/versioned_docs/version-0.60/_getting-started-windows-android.md
  website/versioned_docs/version-0.61/_getting-started-linux-android.md
  website/versioned_docs/version-0.61/_getting-started-macos-android.md
  website/versioned_docs/version-0.61/_getting-started-windows-android.md
  website/versioned_docs/version-0.62/_getting-started-linux-android.md
  website/versioned_docs/version-0.62/_getting-started-macos-android.md
  website/versioned_docs/version-0.62/_getting-started-windows-android.md
  website/versioned_docs/version-0.63/_getting-started-linux-android.md
  website/versioned_docs/version-0.63/_getting-started-macos-android.md
  website/versioned_docs/version-0.63/_getting-started-windows-android.md
Labels: CLA Signed

#2363 Update intro-react-native-components.md
  website/versioned_docs/version-0.63/intro-react-native-components.md
Labels: CLA Signed

#2362 refreshed FB OS logo, footer and menu small UI tweaks
  website/src/css/customTheme.scss
  website/static/img/oss_logo.png
Labels: CLA Signed

#2261 Updating Native Modules Documentation
  docs/native-components-android.md
  docs/native-components-ios.md
  docs/native-modules-android.md
  docs/native-modules-intro.md
  docs/native-modules-ios.md
  docs/native-modules-setup.md
  website/sidebars.json
  website/static/docs/assets/native-modules-android-add-class.png
  website/static/docs/assets/native-modules-android-errorscreen.png
  website/static/docs/assets/native-modules-android-logs.png
  website/static/docs/assets/native-modules-android-open-project.png
  website/static/docs/assets/native-modules-ios-add-class.png
  website/static/docs/assets/native-modules-ios-logs.png
  website/static/docs/assets/native-modules-ios-open-project.png
  website/versioned_docs/version-0.63/native-components-android.md
  website/versioned_docs/version-0.63/native-components-ios.md
  website/versioned_docs/version-0.63/native-modules-android.md
  website/versioned_docs/version-0.63/native-modules-intro.md
  website/versioned_docs/version-0.63/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-setup.md
  website/versioned_sidebars/version-0.63-sidebars.json
Labels: CLA Signed

#2364 Javascript->JavaScript in native-modules-intro
  docs/native-modules-intro.md
Labels: CLA Signed, Partner, p: Facebook

#2365 fix "Javascript" capitalization typo across all docs
  docs/building-for-tv.md
  docs/native-components-ios.md
  docs/native-modules-android.md
  docs/native-modules-ios.md
  docs/native-modules-setup.md
  docs/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.60/building-for-tv.md
  website/versioned_docs/version-0.60/native-components-ios.md
  website/versioned_docs/version-0.60/native-modules-setup.md
  website/versioned_docs/version-0.60/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.61/building-for-tv.md
  website/versioned_docs/version-0.61/native-components-ios.md
  website/versioned_docs/version-0.61/native-modules-setup.md
  website/versioned_docs/version-0.61/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.62/building-for-tv.md
  website/versioned_docs/version-0.62/native-components-ios.md
  website/versioned_docs/version-0.62/native-modules-setup.md
  website/versioned_docs/version-0.62/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.63/building-for-tv.md
  website/versioned_docs/version-0.63/native-components-ios.md
  website/versioned_docs/version-0.63/native-modules-android.md
  website/versioned_docs/version-0.63/native-modules-intro.md
  website/versioned_docs/version-0.63/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-setup.md
  website/versioned_docs/version-0.63/optimizing-flatlist-configuration.md
Labels: CLA Signed

#2360 Update hermes.md to explain debugging on Hermes
  docs/hermes.md
  website/versioned_docs/version-0.63/hermes.md
Labels: CLA Signed, Partner, p: Facebook

#2366 Extends and class are no longer part of the example code 'above'. Add…
  website/versioned_docs/version-0.63/tutorial.md
Labels: CLA Signed

#2367 add loading param to remark-snackplayer plugin
  plugins/remark-snackplayer/package.json
  plugins/remark-snackplayer/src/index.js
  plugins/remark-snackplayer/tests/markdown/test2.md
  plugins/remark-snackplayer/tests/output/output1.html
  plugins/remark-snackplayer/tests/output/output2.html
  website/docusaurus.config.js
  yarn.lock
Labels: CLA Signed

#2368 [docs]: Add 0.64 required updates to the documentation - Part 1/x
  docs/image.md
  docs/pressable.md
  docs/scrollview.md
  docs/shadow-props.md
  docs/textinput.md
Labels: CLA Signed

#2370 update Share, Shadow and View Props pages to match latest patterns
  docs/shadow-props.md
  docs/share.md
  docs/view-style-props.md
  website/src/css/customTheme.scss
Labels: CLA Signed

#2371 fix few Lighthouse warnings, remove old Footer file
  website/blog/2018-01-18-implementing-twitters-app-loading-animation-in-react-native.md
  website/core/Footer.js
  website/src/css/customTheme.scss
  website/src/pages/index.js
Labels: CLA Signed

#2312 Recommend Node be installed via nvm-windows
  docs/_getting-started-windows-android.md
  website/versioned_docs/version-0.63/_getting-started-windows-android.md
Labels: CLA Signed

#2342 Update drawerlayoutandroid.md
  docs/drawerlayoutandroid.md
  website/versioned_docs/version-0.63/drawerlayoutandroid.md
Labels: CLA Signed

#2372 update Prettier, add styles to Prettier check, reformat files
  .prettierrc
  docs/backhandler.md
  docs/building-for-tv.md
  docs/native-modules-ios.md
  package.json
  plugins/remark-snackplayer/src/index.js
  sync-api-docs/generateMarkdown.js
  website/package.json
  website/versioned_docs/version-0.60/backhandler.md
  website/versioned_docs/version-0.60/building-for-tv.md
  website/versioned_docs/version-0.60/listview.md
  website/versioned_docs/version-0.60/webview.md
  website/versioned_docs/version-0.61/backhandler.md
  website/versioned_docs/version-0.61/building-for-tv.md
  website/versioned_docs/version-0.61/listview.md
  website/versioned_docs/version-0.61/webview.md
  website/versioned_docs/version-0.62/backhandler.md
  website/versioned_docs/version-0.62/building-for-tv.md
  website/versioned_docs/version-0.62/listview.md
  website/versioned_docs/version-0.62/webview.md
  website/versioned_docs/version-0.63/backhandler.md
  website/versioned_docs/version-0.63/building-for-tv.md
  website/versioned_docs/version-0.63/listview.md
  website/versioned_docs/version-0.63/webview.md
  yarn.lock
Labels: CLA Signed

#2373 Consolidating Params
  docs/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-ios.md
Labels: CLA Signed

#2374 update references sections on several pages, improve few examples
  docs/appregistry.md
  docs/devsettings.md
  docs/interactionmanager.md
  docs/keyboard.md
  docs/layoutanimation.md
  docs/linking.md
  docs/panresponder.md
  docs/settings.md
  docs/usecolorscheme.md
  docs/usewindowdimensions.md
  docs/vibration.md
  website/src/css/customTheme.scss
Labels: CLA Signed

#2376 update FlatList and VirtualizedList references
  docs/flatlist.md
  docs/virtualizedlist.md
Labels: CLA Signed

#2377 Typo fix
  docs/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-ios.md
Labels: CLA Signed

#2380 update AccessibilityInfo page, small fixes on other pages
  docs/accessibilityinfo.md
  docs/appearance.md
  docs/devsettings.md
  docs/layoutanimation.md
  website/src/css/customTheme.scss
Labels: CLA Signed

#2379 Add missing Platform API docs
  docs/_getting-started-windows-android.md
  docs/platform.md
  website/sidebars.json
  website/src/css/customTheme.scss
  website/versioned_docs/version-0.63/platform.md
  website/versioned_sidebars/version-0.63-sidebars.json
Labels: CLA Signed

#2384 Add a missing brackets
  docs/intro-react.md
Labels: CLA Signed

#2385 Make known issues in text listed in toc
  docs/text.md
Labels: CLA Signed

#2387 Update _getting-started-macos-ios.md
  docs/_getting-started-macos-ios.md
Labels: CLA Signed

#2386 Update native-modules-android.md
  website/versioned_docs/version-0.63/native-modules-android.md
Labels: CLA Signed

#2383 Typo fix at Flexbox.md
  docs/flexbox.md
Labels: CLA Signed

#2390 Update brew syntax
  docs/_getting-started-macos-android.md
  website/versioned_docs/version-0.60/_getting-started-macos-android.md
  website/versioned_docs/version-0.61/_getting-started-macos-android.md
  website/versioned_docs/version-0.62/_getting-started-macos-android.md
  website/versioned_docs/version-0.63/_getting-started-macos-android.md
Labels: CLA Signed

#2389 Update documentation to point to new repo for Bob
  docs/native-modules-setup.md
Labels: CLA Signed, Contributor, Partner, p: callstack

#2391 Fix comma splice
  docs/handling-touches.md
  website/versioned_docs/version-0.63/handling-touches.md
Labels: CLA Signed

#2392 Fix integration with existing apps link
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
Labels: CLA Signed

#2393 add curly braces in main component example
  website/src/pages/index.js
Labels: CLA Signed

#2395 Fix typo
  docs/native-modules-android.md
  docs/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-android.md
  website/versioned_docs/version-0.63/native-modules-ios.md
Labels: CLA Signed

#2396 Update layout-props.md
  docs/layout-props.md
  website/versioned_docs/version-0.63/layout-props.md
Labels: CLA Signed

#2397 Update platform-specific-code.md
  docs/platform-specific-code.md
  website/versioned_docs/version-0.63/platform-specific-code.md
Labels: CLA Signed

#2402 Fix typo in README.md
  README.md
Labels: CLA Signed

#2403 Update animated.md
  docs/animated.md
Labels: CLA Signed

#2398 Update typescript.md
  docs/typescript.md
  website/versioned_docs/version-0.63/typescript.md
Labels: CLA Signed

#2401 Update the Infinite Red Slack Community URL in help.md
  website/src/pages/help.md
Labels: CLA Signed

#2400 Remove unnecessary brackets from native-components-ios.md
  docs/native-components-ios.md
  website/versioned_docs/version-0.60/native-components-ios.md
  website/versioned_docs/version-0.61/native-components-ios.md
  website/versioned_docs/version-0.62/native-components-ios.md
  website/versioned_docs/version-0.63/native-components-ios.md
Labels: CLA Signed

#2405 Link directly to Reactiflux's React Native channels
  website/src/pages/help.md
Labels: CLA Signed, sony

#2407 typo
  docs/panresponder.md
Labels: CLA Signed

#2408 Fix typos in native-modules-android.md
  docs/native-modules-android.md
  website/versioned_docs/version-0.63/native-modules-android.md
Labels: CLA Signed

#2409 Fix: change comparison to equal value and equal type
  website/versioned_docs/version-0.63/keyboardavoidingview.md
Labels: CLA Signed

#2410 Improve language used in navigation.md
  website/versioned_docs/version-0.63/navigation.md
Labels: CLA Signed

#2413 Correct the version react hooks were released
  website/versioned_docs/version-0.60/introduction.md
  website/versioned_docs/version-0.61/introduction.md
  website/versioned_docs/version-0.62/introduction.md
  website/versioned_docs/version-0.63/introduction.md
Labels: CLA Signed

#2411 Update animations.md
  website/versioned_docs/version-0.63/animations.md
Labels: CLA Signed

#2412 Update security.md
  docs/security.md
  website/versioned_docs/version-0.63/security.md
Labels: CLA Signed

#2415 Update sectionlist.md
  docs/sectionlist.md
  website/versioned_docs/version-0.63/sectionlist.md
Labels: CLA Signed

#2416 Update textinput.md
  docs/textinput.md
  website/versioned_docs/version-0.63/textinput.md
Labels: CLA Signed

#2417 Update animated.md
  docs/animated.md
  website/versioned_docs/version-0.63/animated.md
Labels: CLA Signed

#2414 Update tutorial.md
  website/versioned_docs/version-0.63/tutorial.md
Labels: CLA Signed

#2421 Fix typo
  docs/alert.md
  docs/platform.md
  website/versioned_docs/version-0.63/platform.md
Labels: CLA Signed

#2422 Fix typo of uiMode
  docs/platform.md
  website/versioned_docs/version-0.63/platform.md
Labels: CLA Signed
