Repository facebook/react-native-website, pull requests merged in 2020-02, with the labels that each got.

#1558 Update AccessibilityInfo.setAccessibilityFocus()
  docs/accessibilityinfo.md
Labels: Partner, RN Team, p: Facebook

#1578 Update docs for React Navigation 5
  docs/navigation.md
  website/versioned_docs/version-0.5/navigation.md
Labels: Contributor, Partner, p: callstack

#1493 deprecation indicator and deprecation notes standardization
  docs/alertios.md
  docs/asyncstorage.md
  docs/datepickerandroid.md
  docs/datepickerios.md
  docs/imageeditor.md
  docs/imagepickerios.md
  docs/pickerios.md
  docs/progressbarandroid.md
  docs/progressviewios.md
  docs/pushnotificationios.md
  docs/segmentedcontrolios.md
  docs/slider.md
  docs/statusbarios.md
  docs/timepickerandroid.md
  docs/viewpagerandroid.md
  website/i18n/en.json
Labels: design

#1494 move props related pages to separate section in sidebar
  website/i18n/en.json
  website/sidebars.json
Labels: design

#1148 Update ReactNativeWebPlayer version, bump Expo SDK version
  website/core/RemarkablePlugins.js
Labels: Partner, RN Team, p: Facebook

#1653 Add class component example to View
  docs/view.md
Labels: Partner, RN Team, p: Facebook

#1600 ⚫️ Dark Mode: Add Appearance module documentation
  docs/appearance.md
  docs/dimensions.md
  website/i18n/en.json
  website/sidebars.json
Labels: Partner, RN Team, p: Facebook
