Repository facebook/react-native-website, pull requests merged in 2021-02, with the labels that each got.

#2424 docs: add another secure alternative to Async Storage in security page
  docs/security.md
  website/versioned_docs/version-0.63/security.md
Labels: CLA Signed

#2430 Update using-a-scrollview.md
  website/versioned_docs/version-0.63/using-a-scrollview.md
Labels: CLA Signed

#2435 Update text.md adjustsFontSizeToFit platform
  docs/text.md
  website/versioned_docs/version-0.62/text.md
  website/versioned_docs/version-0.63/text.md
Labels: CLA Signed

#2436 Fix link to profiling in performance doc
  docs/performance.md
  website/versioned_docs/version-0.62/performance.md
  website/versioned_docs/version-0.63/performance.md
Labels: CLA Signed

#2437 Fix typo
  docs/rect.md
  website/versioned_docs/version-0.63/rect.md
Labels: CLA Signed

#2440 Describe new added feature userInterfaceStyle in ActionSheetIOS
  docs/actionsheetios.md
  website/versioned_docs/version-0.63/actionsheetios.md
Labels: CLA Signed

#2444 Fix spacing for Class Component in ActivityIndicator Docs
  docs/activityindicator.md
  website/versioned_docs/version-0.63/activityindicator.md
Labels: CLA Signed

#2447 fix image in native modules ios
  docs/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-ios.md
Labels: CLA Signed

#2450 Fix the description for the *Component props for vritualized lists
  docs/flatlist.md
  docs/sectionlist.md
  docs/virtualizedlist.md
  website/versioned_docs/version-0.60/flatlist.md
  website/versioned_docs/version-0.60/sectionlist.md
  website/versioned_docs/version-0.60/virtualizedlist.md
  website/versioned_docs/version-0.61/flatlist.md
  website/versioned_docs/version-0.61/sectionlist.md
  website/versioned_docs/version-0.61/virtualizedlist.md
  website/versioned_docs/version-0.62/flatlist.md
  website/versioned_docs/version-0.62/sectionlist.md
  website/versioned_docs/version-0.62/virtualizedlist.md
  website/versioned_docs/version-0.63/flatlist.md
  website/versioned_docs/version-0.63/sectionlist.md
  website/versioned_docs/version-0.63/virtualizedlist.md
Labels: CLA Signed, Contributor, Partner, p: callstack

#2458 Fix ScrollView alwaysBounceVertical doc
  docs/scrollview.md
  website/versioned_docs/version-0.63/scrollview.md
Labels: CLA Signed

#2464 Remove documentation of setOpacityTo instance method
  docs/touchableopacity.md
  website/versioned_docs/version-0.62/touchableopacity.md
  website/versioned_docs/version-0.63/touchableopacity.md
Labels: CLA Signed

#2466 Update scrollview.md
  docs/scrollview.md
Labels: CLA Signed

#2451 Fix FlexShrink default value
  docs/flexbox.md
  website/versioned_docs/version-0.63/flexbox.md
Labels: CLA Signed

#2468 #2453 - Add missing methods section to Platform API reference
  docs/platform.md
  docs/platformcolor.md
  website/versioned_docs/version-0.63/platform.md
Labels: CLA Signed

#2467 Update flatlist.md and virtualizedlist.md
  docs/flatlist.md
  docs/virtualizedlist.md
  website/versioned_docs/version-0.60/flatlist.md
  website/versioned_docs/version-0.60/virtualizedlist.md
  website/versioned_docs/version-0.61/flatlist.md
  website/versioned_docs/version-0.61/virtualizedlist.md
  website/versioned_docs/version-0.62/flatlist.md
  website/versioned_docs/version-0.62/virtualizedlist.md
  website/versioned_docs/version-0.63/flatlist.md
  website/versioned_docs/version-0.63/virtualizedlist.md
Labels: CLA Signed

#2472 fix example in PlatformColor
  docs/platformcolor.md
  website/versioned_docs/version-0.63/platformcolor.md
Labels: CLA Signed

#2474 Support dependencies on Snack player
  docs/text-style-props.md
  plugins/remark-snackplayer/README.md
  plugins/remark-snackplayer/package.json
  plugins/remark-snackplayer/src/index.js
  plugins/remark-snackplayer/tests/markdown/test2.md
  plugins/remark-snackplayer/tests/output/output1.html
  plugins/remark-snackplayer/tests/output/output2.html
Labels: CLA Signed

#2448 Fix swift bug in native-modules-ios.md
  docs/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-ios.md
Labels: CLA Signed

#2480 remove expo-constants from examples in favor of build-in solutions, prettier doc files
  docs/flatlist.md
  docs/layout-props.md
  docs/native-components-ios.md
  docs/permissionsandroid.md
  docs/scrollview.md
  docs/sectionlist.md
  docs/text-style-props.md
  docs/toastandroid.md
  docs/touchablenativefeedback.md
  docs/virtualizedlist.md
  website/versioned_docs/version-0.60/flatlist.md
  website/versioned_docs/version-0.60/native-components-ios.md
  website/versioned_docs/version-0.60/sectionlist.md
  website/versioned_docs/version-0.60/virtualizedlist.md
  website/versioned_docs/version-0.61/flatlist.md
  website/versioned_docs/version-0.61/native-components-ios.md
  website/versioned_docs/version-0.61/sectionlist.md
  website/versioned_docs/version-0.61/virtualizedlist.md
  website/versioned_docs/version-0.62/flatlist.md
  website/versioned_docs/version-0.62/native-components-ios.md
  website/versioned_docs/version-0.62/sectionlist.md
  website/versioned_docs/version-0.62/virtualizedlist.md
  website/versioned_docs/version-0.63/flatlist.md
  website/versioned_docs/version-0.63/layout-props.md
  website/versioned_docs/version-0.63/native-components-ios.md
  website/versioned_docs/version-0.63/permissionsandroid.md
  website/versioned_docs/version-0.63/refreshcontrol.md
  website/versioned_docs/version-0.63/scrollview.md
  website/versioned_docs/version-0.63/sectionlist.md
  website/versioned_docs/version-0.63/statusbar.md
  website/versioned_docs/version-0.63/text-style-props.md
  website/versioned_docs/version-0.63/toastandroid.md
  website/versioned_docs/version-0.63/touchablenativefeedback.md
  website/versioned_docs/version-0.63/virtualizedlist.md
Labels: CLA Signed

#2482 update ScrollView page, add platform labels, add missing prop and defaults
  docs/flatlist.md
  docs/pressable.md
  docs/scrollview.md
  docs/text.md
  docs/view.md
  docs/virtualizedlist.md
  website/src/css/customTheme.scss
  website/versioned_docs/version-0.63/scrollview.md
Labels: CLA Signed

#2481 Inserting omitted code
  website/versioned_docs/version-0.63/modal.md
Labels: CLA Signed

#2483 attempt to fix CI test pipeline job timeout
  .circleci/config.yml
Labels: 🧰 Infra

#2484 CI: add extended timeout to the website deploy
  .circleci/config.yml
Labels: CLA Signed, 🧰 Infra

#2485 update modal page, add missing defaults, simplify examples
  docs/modal.md
  website/versioned_docs/version-0.63/modal.md
Labels: CLA Signed

#2490 Android Pay is now Google Pay
  docs/native-modules-intro.md
  website/versioned_docs/version-0.63/native-modules-intro.md
Labels: CLA Signed

#2491 remove invalid Appearance API pages
  website/versioned_docs/version-0.60/appearance.md
  website/versioned_docs/version-0.61/appearance.md
Labels: CLA Signed

#2492 remove invalid usecolorscheme pages created after migration
  website/versioned_docs/version-0.60/usecolorscheme.md
  website/versioned_docs/version-0.61/usecolorscheme.md
Labels: CLA Signed

#2493 add year dividers to the blog posts sidebar
  website/src/css/customTheme.scss
  website/src/theme/BlogSidebar/index.js
  website/src/theme/BlogSidebar/styles.module.css
Labels: CLA Signed, Design

#2470 update deprecation notes to point to the RN Directory instead of single package
  docs/asyncstorage.md
  docs/checkbox.md
  docs/clipboard.md
  docs/datepickerandroid.md
  docs/datepickerios.md
  docs/imageeditor.md
  docs/imagepickerios.md
  docs/picker.md
  docs/pickerios.md
  docs/progressbarandroid.md
  docs/progressviewios.md
  docs/pushnotificationios.md
  docs/segmentedcontrolios.md
  docs/slider.md
  docs/timepickerandroid.md
  docs/viewpagerandroid.md
  website/versioned_docs/version-0.63/asyncstorage.md
  website/versioned_docs/version-0.63/cameraroll.md
  website/versioned_docs/version-0.63/checkbox.md
  website/versioned_docs/version-0.63/clipboard.md
  website/versioned_docs/version-0.63/datepickerandroid.md
  website/versioned_docs/version-0.63/datepickerios.md
  website/versioned_docs/version-0.63/geolocation.md
  website/versioned_docs/version-0.63/imageeditor.md
  website/versioned_docs/version-0.63/imagepickerios.md
  website/versioned_docs/version-0.63/imagestore.md
  website/versioned_docs/version-0.63/maskedviewios.md
  website/versioned_docs/version-0.63/netinfo.md
  website/versioned_docs/version-0.63/picker.md
  website/versioned_docs/version-0.63/pickerios.md
  website/versioned_docs/version-0.63/progressbarandroid.md
  website/versioned_docs/version-0.63/progressviewios.md
  website/versioned_docs/version-0.63/pushnotificationios.md
  website/versioned_docs/version-0.63/segmentedcontrolios.md
  website/versioned_docs/version-0.63/slider.md
  website/versioned_docs/version-0.63/timepickerandroid.md
  website/versioned_docs/version-0.63/viewpagerandroid.md
  website/versioned_docs/version-0.63/webview.md
Labels: CLA Signed

#2494 Remove unnecessary `
  docs/flatlist.md
  website/versioned_docs/version-0.60/flatlist.md
  website/versioned_docs/version-0.61/flatlist.md
  website/versioned_docs/version-0.62/flatlist.md
  website/versioned_docs/version-0.63/flatlist.md
Labels: CLA Signed

#2500 generalize More Resources page intro
  docs/more-resources.md
  website/versioned_docs/version-0.63/more-resources.md
Labels: CLA Signed

#2501 Fixed typo – containg -> containing
  docs/alert.md
Labels: CLA Signed

#2502 Typo fix
  website/versioned_docs/version-0.63/optimizing-flatlist-configuration.md
Labels: CLA Signed

#2505 [docs] Mention flex layout default values differing from spec/web default values
  docs/flexbox.md
  website/versioned_docs/version-0.63/flexbox.md
Labels: CLA Signed

#2503 Fix typo
  docs/native-modules-android.md
  docs/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-android.md
  website/versioned_docs/version-0.63/native-modules-ios.md
Labels: CLA Signed

#2509 Update flexbox.md
  website/versioned_docs/version-0.63/flexbox.md
Labels: CLA Signed

#2510 Update flexbox.md
  docs/flexbox.md
Labels: CLA Signed

#2508 Fixes some spelling errors
  docs/headless-js-android.md
  docs/libraries.md
  docs/pixelratio.md
  docs/refreshcontrol.md
Labels: CLA Signed

#2514 Pay wasn't capitalized (Native Modules intro)
  docs/native-modules-intro.md
  website/versioned_docs/version-0.63/native-modules-intro.md
Labels: CLA Signed

#2515 docs: fix typo in link anchor
  docs/upgrading.md
  website/versioned_docs/version-0.63/upgrading.md
Labels: CLA Signed

#2516 update link to profiling with systrace
  docs/profiling.md
  website/versioned_docs/version-0.63/profiling.md
Labels: CLA Signed

#2461 Update Coinbase blog
  website/showcase.json
Labels: CLA Signed, Partner, Showcase, p: Facebook

#2517 Update Docs for Ignite now using "MobX-State-Tree" for state management
  website/versioned_docs/version-0.63/more-resources.md
Labels: CLA Signed

#2518 fix react-native issue #30326 - Text numberOfLines={2} and other than ellipsizeMode="tail" breaks on Android
  docs/text.md
Labels: CLA Signed
