Repository facebook/react-native-website, pull requests merged in 2021-09, with the labels that each got.

#2745 Update debugging.md
  docs/debugging.md
Labels: CLA Signed

#2750 Update flexbox.md
  docs/flexbox.md
Labels: CLA Signed

#2753 Update flexbox.md
  docs/flexbox.md
Labels: CLA Signed

#2752 Add " Preparing Your App for iOS 15 and Android 12" blog post
  website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
  website/static/blog/assets/ios-15-navigation-bar.jpg
  website/static/blog/assets/ios-15-quicktype-bar.png
Labels: Partner, p: Facebook, CLA Signed

#2744 Docusaurus canary upgrade + blog post multi-authors
  .eslintrc.json
  package.json
  website/blog/2021-08-06-version-065.md
  website/blog/2021-08-19-h2-2021.md
  website/blog/2021-08-26-many-platform-vision/index.md
  website/blog/2021-08-26-many-platform-vision/many-platform-vision-facebook-dating.png
  website/blog/2021-08-26-many-platform-vision/many-platform-vision-facebook-website.png
  website/blog/2021-08-26-many-platform-vision/many-platform-vision-messenger-desktop.png
  website/blog/2021-08-26-many-platform-vision/many-platform-vision-oculus-home.png
  website/blog/2021-08-30-react-native-is-hiring-managers.md
  website/blog/authors.yml
  website/docusaurus.config.js
  website/package.json
  website/sitePlugin.js
  website/src/css/customTheme.scss
  website/src/theme/DocItem/index.js
  website/src/theme/DocItem/styles.module.css
  website/src/theme/DocItemFooter/index.js
  website/src/theme/Layout.js
  yarn.lock
Labels: CLA Signed

#2751 Update flexbox.md
  docs/flexbox.md
Labels: CLA Signed

#2754 Update flexbox.md
  docs/flexbox.md
Labels: CLA Signed

#2756 docs: remove "see the code" section in swift an objc examples
  docs/_integration-with-exisiting-apps-objc.md
  docs/_integration-with-exisiting-apps-swift.md
  website/versioned_docs/version-0.65/_integration-with-exisiting-apps-objc.md
  website/versioned_docs/version-0.65/_integration-with-exisiting-apps-swift.md
Labels: CLA Signed

#2755 Update network.md
  docs/network.md
Labels: CLA Signed

#2759 Add truncation to recent blog posts
  website/blog/2021-08-19-h2-2021.md
  website/blog/2021-08-26-many-platform-vision/index.md
  website/blog/2021-08-30-react-native-is-hiring-managers.md
  website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
Labels: Partner, p: Facebook, CLA Signed

#2760 Migrate recent blog posts to `authors.yml`
  website/blog/2021-08-26-many-platform-vision/index.md
  website/blog/2021-08-30-react-native-is-hiring-managers.md
  website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
  website/blog/authors.yml
Labels: Partner, p: Facebook, CLA Signed

#2747 Update iOS path to use a different port
  docs/troubleshooting.md
Labels: CLA Signed

#2773 Clearify type definition of sendIntent parameter
  docs/linking.md
Labels: CLA Signed

#2770 Update fast-refresh.md
  docs/fast-refresh.md
Labels: CLA Signed

#2732 update out-of-tree platforms list
  docs/out-of-tree-platforms.md
  website/versioned_docs/version-0.64/out-of-tree-platforms.md
  website/versioned_docs/version-0.65/out-of-tree-platforms.md
Labels: CLA Signed, Needs: React Native Team Attention

#2772 fix and generalize shared event types definitions
  docs/button.md
  docs/image.md
  docs/linking.md
  docs/pressable.md
  docs/text.md
  docs/textinput.md
  docs/touchablewithoutfeedback.md
  docs/view.md
  website/versioned_docs/version-0.65/button.md
  website/versioned_docs/version-0.65/image.md
  website/versioned_docs/version-0.65/pressable.md
  website/versioned_docs/version-0.65/text.md
  website/versioned_docs/version-0.65/textinput.md
  website/versioned_docs/version-0.65/touchablewithoutfeedback.md
  website/versioned_docs/version-0.65/view.md
Labels: Partner, p: expo, CLA Signed

#2720 Update using-a-scrollview.md
  docs/using-a-scrollview.md
Labels: CLA Signed

#2777 Remove blog date fields and fix filename discrepancy
  website/blog/2021-08-17-version-065.md
  website/blog/2021-08-19-h2-2021.md
  website/blog/2021-08-26-many-platform-vision/index.md
  website/blog/2021-08-30-react-native-is-hiring-managers.md
  website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
Labels: Partner, p: Facebook, CLA Signed

#2775 recent blog posts cleanup, fix lint warning
  website/blog/2021-08-26-many-platform-vision.md
  website/blog/2021-08-30-react-native-is-hiring-managers.md
  website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
  website/static/blog/assets/many-platform-vision-facebook-dating.png
  website/static/blog/assets/many-platform-vision-facebook-website.png
  website/static/blog/assets/many-platform-vision-messenger-desktop.png
  website/static/blog/assets/many-platform-vision-oculus-home.png
Labels: Partner, p: expo, CLA Signed

#2776 Add a note about where to place the Gradle vars
  docs/signed-apk-android.md
Labels: CLA Signed

#2778 Update appstate.md
  docs/appstate.md
Labels: CLA Signed

#2780 docs: remove unused style object
  docs/animations.md
Labels: CLA Signed

#2782 Force `trim@^1.0.1` resolution
  package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#2774 Add help relating to Android intent queries
  docs/linking.md
Labels: CLA Signed

#2599 docs: add fragment to native-components-android.md
  docs/native-components-android.md
Labels: CLA Signed, Needs: React Native Team Attention, Shared with React Native Team

#2784 Remove the link to 2021 React Community Survey
  website/docusaurus.config.js
Labels: CLA Signed

#2794 Bump ansi-regex to ^5.0.1 to fix CVE-2021-3807
  package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed
