Repository facebook/react-native-website, pull requests merged in 2021-04, with the labels that each got.

#2571 FIX: added StatusBar import
  docs/text-style-props.md
  website/versioned_docs/version-0.62/text-style-props.md
  website/versioned_docs/version-0.63/text-style-props.md
  website/versioned_docs/version-0.64/text-style-props.md
Labels: CLA Signed

#2572 Fix: added missing import of Slider
  docs/text-style-props.md
  website/versioned_docs/version-0.64/text-style-props.md
Labels: CLA Signed

#2574 Fixed typo in text.md
  docs/text.md
  website/versioned_docs/version-0.64/text.md
Labels: CLA Signed

#2570 improve CI checks, ditch `test` in favor of Netlify, fix Alex warnings
  .alexignore
  .circleci/config.yml
  website/blog/2020-03-26-version-0.62.md
  website/blog/2020-07-06-version-0.63.md
  website/blog/2020-07-17-react-native-principles.md
  website/blog/2021-03-12-version-0.64.md
  website/package.json
  website/src/css/customTheme.scss
Labels: CLA Signed, 🧰 Infra

#2577 Remove ScrollView.scrollWithoutAnimationTo() documentation
  docs/scrollview.md
Labels: CLA Signed, Partner, RN Team, p: Facebook

#2578 Deprecate `removeListener` APIs
  docs/accessibilityinfo.md
  docs/appearance.md
  docs/appstate.md
  docs/dimensions.md
  docs/keyboard.md
  docs/linking.md
Labels: CLA Signed, Partner, RN Team, p: Facebook

#2576 docs: fix minor typo
  docs/ram-bundles-inline-requires.md
  website/versioned_docs/version-0.64/ram-bundles-inline-requires.md
Labels: CLA Signed

#2579 changed for all version docs pull request #2568
  website/versioned_docs/version-0.62/using-a-scrollview.md
  website/versioned_docs/version-0.64/using-a-scrollview.md
Labels: CLA Signed

#2441 Documentation Update for RN PR #30737 - Remove Android specifier for progressViewOffset prop.
  docs/flatlist.md
  docs/refreshcontrol.md
  docs/virtualizedlist.md
Labels: CLA Signed, Wait on future Release

#2583 improve the lint setup, add verbose output on Prettier error
  .circleci/config.yml
  .eslintrc.json
  package.json
  website/package.json
  yarn.lock
Labels: CLA Signed, 🧰 Infra

#2581 feat: add `getRecommendedTimeoutMillis` section on accessibilityInfo
  docs/accessibilityinfo.md
Labels: CLA Signed

#2584 docs: fix inaccurate example
  website/src/pages/index.js
Labels: CLA Signed

#2549 Update TalkBack download info in accessibility.md
  docs/accessibility.md
Labels: CLA Signed, Partner, p: Facebook

#2585 Add notes about enabling Hermes for iOS
  docs/hermes.md
  website/versioned_docs/version-0.64/hermes.md
Labels: CLA Signed

#2580 March Update for GAAD Pledge initiative by Facebook
  website/blog/2021-04-08-GAAD-March-Accessibility-Issue-Update.md
Labels: :memo: Blog Post, CLA Signed

#2586 Update the documentation of ActionSheetIOS
  docs/actionsheetios.md
  website/versioned_docs/version-0.64/actionsheetios.md
Labels: CLA Signed

#2587 fix Animated example with space buttons
  docs/animated.md
  website/versioned_docs/version-0.63/animated.md
  website/versioned_docs/version-0.64/animated.md
Labels: CLA Signed

#2592 Fix broken mozilla.org link in timers.md
  docs/timers.md
  website/versioned_docs/version-0.64/timers.md
Labels: CLA Signed

#2591 Update _getting-started-macos-ios.md
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  website/versioned_docs/version-0.64/_getting-started-linux-android.md
  website/versioned_docs/version-0.64/_getting-started-macos-android.md
  website/versioned_docs/version-0.64/_getting-started-macos-ios.md
  website/versioned_docs/version-0.64/_getting-started-windows-android.md
Labels: CLA Signed

#2594 update TypeScript guide example and TS Playground link
  docs/typescript.md
  website/versioned_docs/version-0.64/typescript.md
Labels: CLA Signed

#2595 Update appstate.md
  docs/appstate.md
  website/versioned_docs/version-0.64/appstate.md
Labels: CLA Signed

#2597 Update alert.md
  docs/alert.md
Labels: CLA Signed

#2598 Update alert.md
  website/versioned_docs/version-0.64/alert.md
Labels: CLA Signed

#2589 Update references to requireNativeComponent in iOS Native Components doc
  docs/native-components-ios.md
Labels: CLA Signed

#2600 Accessibility improvement
  website/src/css/customTheme.scss
Labels: CLA Signed
