Repository facebook/react-native-website, pull requests merged in 2021-06, with the labels that each got.

#2628 docs: fix style buttons in Systrace API
  docs/systrace.md
  website/versioned_docs/version-0.64/systrace.md
Labels: CLA Signed

#2633 Add a note about the chrome debugger causing useColorScheme to always return "light"
  docs/usecolorscheme.md
  website/versioned_docs/version-0.64/usecolorscheme.md
Labels: CLA Signed

#2636 update Docusaurus to latest beta, fix SCSS, fix Algolia styles
  website/package.json
  website/src/css/customTheme.scss
  website/src/css/index.scss
  yarn.lock
Labels: CLA Signed, 🦖 Docusaurus

#2627 Roottag documentation
  docs/roottag.md
  website/sidebars.json
Labels: CLA Signed, Partner, p: Facebook

#2638 Fixed some minor typos
  docs/text.md
Labels: CLA Signed

#2639 Update pixelratio.md
  docs/pixelratio.md
  website/versioned_docs/version-0.64/pixelratio.md
Labels: CLA Signed

#2642 Fix/Value for flexWrap
  docs/flexbox.md
Labels: CLA Signed

#2603 update Coinbase icon
  website/static/img/showcase/coinbase.png
Labels: CLA Signed, Needs: React Native Team Attention, Showcase

#2640 support high contrast colors
  docs/dynamiccolorios.md
Labels: CLA Signed

#2653 Images: Remove mention of platform-specific extensions
  docs/images.md
Labels: CLA Signed, Partner, RN Team, p: Facebook

#2645 Update platform-specific-code.md
  docs/platform-specific-code.md
Labels: CLA Signed

#2650 Remove unused failureCallback in example
  docs/native-modules-android.md
  website/versioned_docs/version-0.64/native-modules-android.md
Labels: CLA Signed

#2652 Update reference to file for iOS remote debugging
  docs/debugging.md
  website/versioned_docs/version-0.64/debugging.md
Labels: CLA Signed

#2656 Disable web-preview for TextStyleProps example
  docs/text-style-props.md
  website/versioned_docs/version-0.64/text-style-props.md
Labels: CLA Signed

#2657 Add Mercari's blog to the showcase
  website/showcase.json
Labels: CLA Signed, Partner, p: Facebook

#2658 Fix typo: NativeNodules -> NativeModules
  docs/native-modules-ios.md
  website/versioned_docs/version-0.64/native-modules-ios.md
Labels: CLA Signed
