Repository facebook/react-native-website, pull requests merged in 2021-03, with the labels that each got.

#2521 Update intro-react-native-components.md
  docs/intro-react-native-components.md
  website/versioned_docs/version-0.63/intro-react-native-components.md
Labels: CLA Signed

#2525 update Docusaurus to latest version
  docs/alert.md
  sync-api-docs/package.json
  website/docusaurus.config.js
  website/package.json
  website/src/css/customTheme.scss
  website/src/theme/DocItem/index.js
  website/versioned_docs/version-0.63/intro-react-native-components.md
  yarn.lock
Labels: CLA Signed

#2519 Update running-on-device.md
  docs/running-on-device.md
  website/versioned_docs/version-0.63/running-on-device.md
Labels: CLA Signed

#2527 Update debugging.md
  docs/debugging.md
  website/versioned_docs/version-0.63/debugging.md
Labels: CLA Signed

#2526 Change the command for scaffolding a module
  docs/native-modules-setup.md
Labels: CLA Signed, Contributor, Partner, p: callstack

#2528 small deps bumps, fix mankypkg CLI check warnings
  README.md
  netlify.toml
  package.json
  website/core/PrismTheme.js
  website/package.json
  yarn.lock
Labels: CLA Signed

#2529 Add NerdWallet blog link
  website/showcase.json
Labels: CLA Signed, Partner, Showcase, p: Facebook

#2531 cleanup removed APIs/Components pages
  docs/checkbox.md
  docs/imageeditor.md
  docs/timepickerandroid.md
  docs/viewpagerandroid.md
  website/versioned_docs/version-0.60/imageeditor.md
  website/versioned_docs/version-0.60/imagestore.md
  website/versioned_docs/version-0.60/netinfo.md
  website/versioned_docs/version-0.60/viewpagerandroid.md
  website/versioned_docs/version-0.61/imageeditor.md
  website/versioned_docs/version-0.61/imagestore.md
  website/versioned_docs/version-0.61/netinfo.md
  website/versioned_docs/version-0.61/viewpagerandroid.md
  website/versioned_docs/version-0.62/imageeditor.md
  website/versioned_docs/version-0.62/imagestore.md
  website/versioned_docs/version-0.62/netinfo.md
  website/versioned_docs/version-0.62/viewpagerandroid.md
  website/versioned_docs/version-0.63/imageeditor.md
  website/versioned_docs/version-0.63/imagestore.md
  website/versioned_docs/version-0.63/netinfo.md
  website/versioned_docs/version-0.63/viewpagerandroid.md
Labels: CLA Signed

#2420 setup and enable PWA
  website/docusaurus.config.js
  website/package.json
  website/static/img/pwa/apple-icon-120.png
  website/static/img/pwa/apple-icon-152.png
  website/static/img/pwa/apple-icon-167.png
  website/static/img/pwa/apple-icon-180.png
  website/static/img/pwa/manifest-icon-192.png
  website/static/img/pwa/manifest-icon-512.png
  website/static/manifest.json
  yarn.lock
Labels: CLA Signed, 🦖 Docusaurus

#2486 Include Android SDK Command-line Tools
  docs/_getting-started-macos-android.md
  website/versioned_docs/version-0.63/_getting-started-macos-android.md
Labels: CLA Signed

#2534 fix FlatList guide typo
  docs/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.60/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.61/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.62/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.63/optimizing-flatlist-configuration.md
Labels: CLA Signed

#2530 Post to boost the GAAD Pledge initiative by Facebook to improve RN a11y
  website/blog/2021-03-08-GAAD-React-Native-Accessibility.md
Labels: :memo: Blog Post, CLA Signed

#2535 Add missing space after comma
  docs/virtualizedlist.md
  website/versioned_docs/version-0.63/virtualizedlist.md
Labels: CLA Signed

#2536 Update note about RCTLinking to account for the addition of auto-linking in 0.60
  website/versioned_docs/version-0.63/linking.md
Labels: CLA Signed

#2537 Add Clarification to Docs - Views are not clickable if parent has height of 0
  docs/handling-touches.md
  docs/style.md
Labels: CLA Signed

#2533 height and width are not the same on different screens
  docs/height-and-width.md
  website/versioned_docs/version-0.63/height-and-width.md
Labels: CLA Signed

#2539 attempt to fix share metadata
  website/docusaurus.config.js
Labels: CLA Signed

#2540 Fixing typo in inilne-requires example in 64 blog
  website/blog/2021-03-11-version-0.64.md
Labels: CLA Signed, Partner, p: Facebook

#2541 Fix typos in 0.64 blog post
  website/blog/2021-03-11-version-0.64.md
Labels: CLA Signed, Partner, p: Facebook

#2543 rewrite redirects for Netlify, cleanup deployment scrips, correct post date
  .circleci/config.yml
  website/blog/2021-03-12-version-0.64.md
  website/docusaurus.config.js
  website/static/.circleci/config.yml
  website/static/.nojekyll
  website/static/_redirects
  website/static/docs/android-setup.html
  website/static/docs/building-for-apple-tv.html
  website/static/docs/building-from-source.html
  website/static/docs/contributing.html
  website/static/docs/maintainers.html
  website/static/docs/publishing-forks.html
  website/static/docs/testing.html
  website/static/docs/understanding-cli.html
Labels: CLA Signed, 🧰 Infra

#2545 Change styling to note
  docs/height-and-width.md
  website/versioned_docs/version-0.63/height-and-width.md
  website/versioned_docs/version-0.64/height-and-width.md
Labels: CLA Signed

#2547 update Docusaurus to latest release, add fixes to custom theme
  docs/height-and-width.md
  website/blog/2021-03-12-version-0.64.md
  website/docusaurus.config.js
  website/package.json
  website/src/css/customTheme.scss
  website/src/pages/index.js
  website/src/theme/DocItem/index.js
  website/src/theme/DocItem/styles.module.css
  website/versioned_docs/version-0.63/height-and-width.md
  website/versioned_docs/version-0.64/height-and-width.md
  yarn.lock
Labels: CLA Signed

#2548 fixed introduction md Tabs functionality
  docs/introduction.md
  website/versioned_docs/version-0.64/introduction.md
Labels: CLA Signed

#2546 Update tutorial.md
  docs/tutorial.md
  website/versioned_docs/version-0.64/tutorial.md
Labels: CLA Signed

#2552 Clarify note about Hermes + RAM Bundles
  docs/ram-bundles-inline-requires.md
  website/versioned_docs/version-0.64/ram-bundles-inline-requires.md
Labels: CLA Signed

#2555 remove VR platform props from docs
  docs/scrollview.md
  website/src/css/customTheme.scss
  website/versioned_docs/version-0.60/scrollview.md
  website/versioned_docs/version-0.61/scrollview.md
  website/versioned_docs/version-0.62/scrollview.md
  website/versioned_docs/version-0.63/scrollview.md
  website/versioned_docs/version-0.64/scrollview.md
Labels: CLA Signed

#2556 chore: add nativeID to image.md
  docs/image.md
  website/versioned_docs/version-0.64/image.md
Labels: CLA Signed

#2557 attempt to speed up Netlify preview deploys
  netlify.toml
  website/docusaurus.config.js
Labels: CLA Signed, 🧰 Infra

#2554 fix return type
  docs/native-modules-ios.md
Labels: CLA Signed

#2558 docs: update second Flatlist example.
  docs/flatlist.md
  website/versioned_docs/version-0.64/flatlist.md
Labels: CLA Signed

#2559 extract versions for deploy preview programmatically
  website/docusaurus.config.js
Labels: CLA Signed

#2560 improve share metadata after latest update
  website/src/pages/index.js
  website/src/pages/showcase.js
  website/src/pages/versions.js
Labels: CLA Signed

#2564 refactor Keyboard API examples
  docs/keyboard.md
  website/versioned_docs/version-0.62/keyboard.md
  website/versioned_docs/version-0.63/keyboard.md
  website/versioned_docs/version-0.64/keyboard.md
Labels: CLA Signed

#2565 minor React bump, small style tweaks and fixes
  .circleci/config.yml
  website/package.json
  website/src/css/customTheme.scss
  website/src/pages/index.js
  website/src/theme/DocItem/index.js
  yarn.lock
Labels: CLA Signed

#2568 App variable is not declared
  docs/using-a-scrollview.md
Labels: CLA Signed
