Repository facebook/react-native-website, pull requests merged in 2021-01, with the labels that each got.

#2394 Point to the correct Shopify React Native apps
  website/showcase.json
Labels: CLA Signed

#2423 Fix typo
  docs/native-modules-android.md
Labels: CLA Signed

#2431 docs: fix dead link
  docs/intro-react.md
  website/versioned_docs/version-0.60/intro-react.md
  website/versioned_docs/version-0.61/intro-react.md
  website/versioned_docs/version-0.62/intro-react.md
  website/versioned_docs/version-0.63/intro-react.md
Labels: CLA Signed

#2432 docs: fix dead link to rebound
  docs/animated.md
  website/versioned_docs/version-0.60/animated.md
  website/versioned_docs/version-0.61/animated.md
  website/versioned_docs/version-0.62/animated.md
  website/versioned_docs/version-0.63/animated.md
Labels: CLA Signed

#2429 Fix typo
  docs/native-modules-android.md
  website/versioned_docs/version-0.63/native-modules-android.md
Labels: CLA Signed

#2426 Fix typo
  docs/native-components-ios.md
  website/versioned_docs/version-0.63/native-components-ios.md
Labels: CLA Signed

#2418 Update image.md
  docs/image.md
  website/versioned_docs/version-0.63/image.md
Labels: CLA Signed

#2434 Fix syntax error.
  docs/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-ios.md
Labels: CLA Signed

#2427 Add Mercari to customer showcase
  website/showcase.json
  website/static/img/showcase/mercari.png
Labels: CLA Signed, Partner, p: Facebook

#2462 Update Reactiflux invite link
  website/src/pages/help.md
Labels: CLA Signed, sony
