Repository facebook/react-native-website, pull requests merged in 2021-08, with the labels that each got.

#2711 Use native-stack for getting started with navigation
  docs/navigation.md
Labels: CLA Signed, Contributor, Partner, p: callstack

#2713 chore: fix link in showcase
  website/src/pages/showcase.js
Labels: CLA Signed

#2582 Update devsettings.md
  docs/devsettings.md
  website/versioned_docs/version-0.60/devsettings.md
  website/versioned_docs/version-0.61/devsettings.md
  website/versioned_docs/version-0.62/devsettings.md
  website/versioned_docs/version-0.63/devsettings.md
  website/versioned_docs/version-0.64/devsettings.md
Labels: CLA Signed

#2719 website: add bunch required labels in different components
  docs/touchablehighlight.md
  docs/touchablenativefeedback.md
  docs/touchableopacity.md
  docs/touchablewithoutfeedback.md
  docs/view.md
Labels: CLA Signed

#2726 docs: removed unnecessary use of ternary
  docs/touchablehighlight.md
Labels: CLA Signed

#2727 Add 2021 banner survey
  website/docusaurus.config.js
  website/src/css/customTheme.scss
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#2717 Release post for 0.65
  website/blog/2021-08-06-version-065.md
Labels: Partner, p: Facebook, CLA Signed

#1184 Update textinput autocomplete
  docs/textinput.md
Labels: Wait on future Release, CLA Signed

#2629 Documentation about proposed RCTSetCustomNSURLSessionConfigurationProvider
  docs/network.md
Labels: Wait on future Release, CLA Signed

#2661 Update scrollview.md adding new prop automaticallyAdjustsScrollIndicatorInsets
  docs/scrollview.md
Labels: Wait on future Release, CLA Signed

#2667 Add "togglebutton" accessibilityRole
  docs/accessibility.md
Labels: Wait on future Release, Partner, p: Facebook, CLA Signed

#2692 Added accessiblity documentation for Button and Text component
  docs/button.md
  docs/text.md
Labels: Wait on future Release, CLA Signed

#2714 docs: update `StatusBarIOS` deprecation message
  docs/statusbarios.md
Labels: Wait on future Release, CLA Signed

#2725 update onRequestClose for IOS modal
  docs/modal.md
Labels: Wait on future Release, CLA Signed

#2729 fix survey banner border and link hover color
  website/docusaurus.config.js
  website/src/css/customTheme.scss
Labels: CLA Signed

#2730 backport NSURLSession docs to `0.65`
  website/versioned_docs/version-0.65/network.md
Labels: CLA Signed

#2733 Update async-storage github link
  docs/security.md
  website/versioned_docs/version-0.62/security.md
  website/versioned_docs/version-0.63/security.md
  website/versioned_docs/version-0.64/security.md
  website/versioned_docs/version-0.65/security.md
Labels: CLA Signed

#2728 add foreground prop in pressable ripple config
  docs/pressable.md
Labels: Wait on future Release, CLA Signed

#2731 fix warning: functions are not valid as ReactChild
  docs/text.md
Labels: CLA Signed

#2734 fix warning: functions are not valid as ReactChild
  website/versioned_docs/version-0.65/text.md
Labels: CLA Signed

#2735 Add React Native in H2 2021 post
  website/blog/2021-08-19-h2-2021.md
Labels: Partner, p: Facebook, CLA Signed

#2736 Add ignore to name
  website/blog/2021-08-19-h2-2021.md
Labels: Partner, p: Facebook, CLA Signed

#2737 update Readme to clarify local running and linting
  README.md
Labels: CLA Signed

#2748 Add "React Native Is Hiring Managers" blog post
  website/blog/2021-08-30-react-native-is-hiring-managers.md
Labels: Partner, p: Facebook, CLA Signed

#2742 make CI checks list explicit, fix alex commands, update Readme
  .circleci/config.yml
  README.md
  website/package.json
Labels: Partner, p: expo, CLA Signed

#2749 fix external links to React and React Native repositories
  CONTRIBUTING.md
  STYLEGUIDE.md
  website/src/pages/versions.js
  website/static/_redirects
Labels: Partner, p: expo, CLA Signed
