Repository facebook/react-native-website, pull requests merged in 2021-10, with the labels that each got.

#2797 Release 0.66 Post
  website/blog/2021-10-01-version-066.md
  website/static/blog/assets/0.66-artifact.png
  website/static/blog/assets/0.66-build-npm-package.png
Labels: Partner, p: Facebook, CLA Signed

#2799 docs: update getting started troubleshooting link
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  website/versioned_docs/version-0.66/_getting-started-linux-android.md
  website/versioned_docs/version-0.66/_getting-started-macos-android.md
  website/versioned_docs/version-0.66/_getting-started-macos-ios.md
  website/versioned_docs/version-0.66/_getting-started-windows-android.md
Labels: CLA Signed

#2795 Update handling-text-input.md
  docs/handling-text-input.md
Labels: CLA Signed

#2796 Update tsconfig.json example
  docs/typescript.md
  website/versioned_docs/version-0.63/typescript.md
  website/versioned_docs/version-0.64/typescript.md
  website/versioned_docs/version-0.65/typescript.md
  website/versioned_docs/version-0.66/typescript.md
Labels: CLA Signed

#2801 add section of `stickyHeaderHiddenOnScroll` option
  docs/scrollview.md
  website/versioned_docs/version-0.65/scrollview.md
  website/versioned_docs/version-0.66/scrollview.md
Labels: CLA Signed

#2791 Update native-modules-android.md
  docs/native-modules-android.md
  website/versioned_docs/version-0.65/native-modules-android.md
  website/versioned_docs/version-0.66/native-modules-android.md
Labels: CLA Signed, Needs: React Native Team Attention, Shared with React Native Team
