Repository facebook/react-native-website, pull requests merged in 2021-12, with the labels that each got.

#2873 Fix typo in alert.md
  docs/alert.md
Labels: Partner, p: Facebook, CLA Signed

#2869 win/android docs: update node install to use nodejs-lts
  docs/_getting-started-windows-android.md
Labels: CLA Signed

#2868 Update handling-text-input.md to emphasize that setText(t) does not t…
  docs/handling-text-input.md
Labels: CLA Signed

#2871 Fix for #2870 - description of status bar.
  docs/statusbar.md
Labels: CLA Signed

#2876 docs: update SafeAreaView
  docs/safeareaview.md
  website/versioned_docs/version-0.66/safeareaview.md
Labels: CLA Signed

#2860 improve ToC and readability of Android Native Components
  docs/native-components-android.md
  website/versioned_docs/version-0.66/native-components-android.md
Labels: Partner, p: expo, CLA Signed

#2881 Updated missing link in animations.md
  docs/animations.md
  website/versioned_docs/version-0.66/animations.md
Labels: CLA Signed

#2888 Update image.md
  docs/image.md
Labels: CLA Signed

#2884 Add "return" details for addEventListener()
  docs/appstate.md
Labels: CLA Signed

#2899 Formatting for view-flattening
  docs/view-flattening.md
Labels: Partner, p: Facebook, CLA Signed

#2898 Xplat implementation
  docs/xplat-implementation.md
Labels: Partner, p: Facebook, CLA Signed

#2897 threading-model formatting
  docs/threading-model.md
Labels: Partner, p: Facebook, CLA Signed

#2900 Format render-pipeline.md
  docs/render-pipeline.md
Labels: Partner, p: Facebook, CLA Signed

#2901 Format fabric-renderer.md
  docs/fabric-renderer.md
Labels: Partner, p: Facebook, CLA Signed

#2902 Add images to Fabric Deep Dive
  docs/render-pipeline.md
  docs/threading-model.md
  docs/view-flattening.md
  docs/xplat-implementation.md
  website/static/docs/assets/Architecture/renderer-phase-one.png
  website/static/docs/assets/Architecture/renderer-phase-three.png
  website/static/docs/assets/Architecture/renderer-phase-two.png
  website/static/docs/assets/Architecture/renderer-pipeline/data-flow.jpg
  website/static/docs/assets/Architecture/renderer-pipeline/phase-one-render.png
  website/static/docs/assets/Architecture/renderer-pipeline/phase-three-mount.png
  website/static/docs/assets/Architecture/renderer-pipeline/phase-two-commit.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-1.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-2.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-3.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-4.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-5.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-6.png
  website/static/docs/assets/Architecture/threading-model/case-1.jpg
  website/static/docs/assets/Architecture/threading-model/case-2.jpg
  website/static/docs/assets/Architecture/threading-model/case-3.jpg
  website/static/docs/assets/Architecture/threading-model/case-4.jpg
  website/static/docs/assets/Architecture/threading-model/case-5.jpg
  website/static/docs/assets/Architecture/threading-model/case-6.jpg
  website/static/docs/assets/Architecture/threading-model/symbols.png
  website/static/docs/assets/Architecture/view-flattening/diagram-one.png
  website/static/docs/assets/Architecture/view-flattening/diagram-two.png
  website/static/docs/assets/Architecture/xplat-implementation/xplat-implementation-diagram.png
Labels: Partner, p: Facebook, CLA Signed

#2903 Resize images in threading model section
  docs/threading-model.md
  website/static/docs/assets/Architecture/threading-model/case-1.jpg
  website/static/docs/assets/Architecture/threading-model/case-2.jpg
  website/static/docs/assets/Architecture/threading-model/case-3.jpg
  website/static/docs/assets/Architecture/threading-model/case-4.jpg
  website/static/docs/assets/Architecture/threading-model/case-5.jpg
  website/static/docs/assets/Architecture/threading-model/case-6.jpg
  website/static/docs/assets/Architecture/threading-model/symbols.png
Labels: Partner, p: Facebook, CLA Signed

#2892 Initial draft of new Architecture Section containing renderer overview
  .alexrc.js
  docs/architecture-overview.md
  docs/fabric-renderer.md
  docs/glossary.md
  docs/render-pipeline.md
  docs/threading-model.md
  docs/view-flattening.md
  docs/xplat-implementation.md
  website/docusaurus.config.js
  website/sidebars.json
  website/static/docs/assets/Architecture/renderer-phase-one.png
  website/static/docs/assets/Architecture/renderer-phase-three.png
  website/static/docs/assets/Architecture/renderer-phase-two.png
  website/static/docs/assets/Architecture/renderer-pipeline/data-flow.jpg
  website/static/docs/assets/Architecture/renderer-pipeline/phase-one-render.png
  website/static/docs/assets/Architecture/renderer-pipeline/phase-three-mount.png
  website/static/docs/assets/Architecture/renderer-pipeline/phase-two-commit.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-1.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-2.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-3.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-4.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-5.png
  website/static/docs/assets/Architecture/renderer-pipeline/render-pipeline-6.png
  website/static/docs/assets/Architecture/threading-model/case-1.jpg
  website/static/docs/assets/Architecture/threading-model/case-2.jpg
  website/static/docs/assets/Architecture/threading-model/case-3.jpg
  website/static/docs/assets/Architecture/threading-model/case-4.jpg
  website/static/docs/assets/Architecture/threading-model/case-5.jpg
  website/static/docs/assets/Architecture/threading-model/case-6.jpg
  website/static/docs/assets/Architecture/threading-model/symbols.png
  website/static/docs/assets/Architecture/view-flattening/diagram-one.png
  website/static/docs/assets/Architecture/view-flattening/diagram-two.png
  website/static/docs/assets/Architecture/xplat-implementation/xplat-implementation-diagram.png
  website/versioned_docs/version-0.66/architecture-overview.md
  website/versioned_docs/version-0.66/fabric-renderer.md
  website/versioned_docs/version-0.66/glossary.md
  website/versioned_docs/version-0.66/render-pipeline.md
  website/versioned_docs/version-0.66/threading-model.md
  website/versioned_docs/version-0.66/view-flattening.md
  website/versioned_docs/version-0.66/xplat-implementation.md
  website/versioned_sidebars/version-0.66-sidebars.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#2883 add styles for non-linkable sidebar entries
  website/src/css/customTheme.scss
Labels: Partner, p: expo, CLA Signed

#2687 update word from currently to may
  docs/images.md
Labels: CLA Signed

#2910 Typofix in fabric-renderer.md file
  docs/fabric-renderer.md
  website/versioned_docs/version-0.66/fabric-renderer.md
Labels: CLA Signed

#2909 Architecture section minor fixes
  docs/fabric-renderer.md
  docs/glossary.md
  website/versioned_docs/version-0.66/fabric-renderer.md
  website/versioned_docs/version-0.66/glossary.md
Labels: CLA Signed

#2896 Update release aab file
  docs/signed-apk-android.md
Labels: CLA Signed

#2912 docs: unwanted text in code block
  docs/native-modules-android.md
Labels: CLA Signed

#2913 Remove unnecessary keyword
  docs/animations.md
Labels: CLA Signed
