Repository facebook/react-native-website, pull requests merged in 2021-07, with the labels that each got.

#2662 update Docusaurus to the latest beta
  website/package.json
  website/src/css/customTheme.scss
  website/src/theme/DocItem/index.js
  yarn.lock
Labels: CLA Signed, 🦖 Docusaurus

#2663 docs: update examples _integration-with-exisiting-apps
  docs/_integration-with-exisiting-apps-java.md
  docs/_integration-with-exisiting-apps-objc.md
  docs/_integration-with-exisiting-apps-swift.md
  website/versioned_docs/version-0.64/_integration-with-exisiting-apps-java.md
  website/versioned_docs/version-0.64/_integration-with-exisiting-apps-objc.md
  website/versioned_docs/version-0.64/_integration-with-exisiting-apps-swift.md
Labels: CLA Signed

#2666 fix for version banner in the latest docs
  website/src/theme/DocVersionSuggestions/index.js
Labels: CLA Signed

#2668 reswizzle `DocItem` to fix version banner issue correctly
  website/src/css/customTheme.scss
  website/src/css/versions.scss
  website/src/theme/DocItem/index.js
  website/src/theme/DocItem/styles.module.css
  website/src/theme/DocVersionSuggestions/index.js
Labels: CLA Signed, 🦖 Docusaurus

#2670 spelling mistake in line 256 intro-react.md
  docs/intro-react.md
  website/versioned_docs/version-0.64/intro-react.md
Labels: CLA Signed

#2675 Clarify some things in the Hermes section
  docs/hermes.md
Labels: CLA Signed

#2680 update ImageBackground example
  docs/imagebackground.md
  website/versioned_docs/version-0.64/imagebackground.md
Labels: CLA Signed

#2674 Removed undefined className
  website/src/pages/index.js
Labels: CLA Signed

#2688 Add MDN link for aspectRatio
  docs/layout-props.md
Labels: CLA Signed

#2684 Remove react-native-dom from list of out-of-tree platforms
  docs/out-of-tree-platforms.md
  website/versioned_docs/version-0.64/out-of-tree-platforms.md
Labels: CLA Signed, Partner, p: Facebook

#2689 attempt to fix CORS issue with `movies.json` file
  netlify.toml
Labels: CLA Signed

#2690 Update documentation for `TextInput`'s `autoCapitalize` property to c…
  website/versioned_docs/version-0.64/textinput.md
Labels: CLA Signed, Partner, p: Facebook

#2686 website: update networking examples
  docs/network.md
  website/versioned_docs/version-0.64/network.md
Labels: CLA Signed

#2676 Update Syntax Transforms list
  docs/javascript-environment.md
  website/core/TableRowWithCodeBlock.js
  website/src/css/customTheme.scss
Labels: CLA Signed

#2691 allow wrapping code blocks content in tables
  website/src/css/customTheme.scss
Labels: CLA Signed

#2693 Update discord logo
  website/static/img/showcase/discord.png
Labels: CLA Signed, Needs: React Native Team Attention, Showcase

#2701 Update Snack to .dev domain
  docs/getting-started.md
  plugins/remark-snackplayer/README.md
  website/docusaurus.config.js
  website/snackPlayerInitializer.js
  website/versioned_docs/version-0.64/getting-started.md
Labels: CLA Signed

#2696 Update link to WebView library
  docs/custom-webview-android.md
  docs/custom-webview-ios.md
  website/versioned_docs/version-0.64/custom-webview-android.md
  website/versioned_docs/version-0.64/custom-webview-ios.md
Labels: CLA Signed

#2698 website: update Dimensions API, improve required labels.
  docs/dimensions.md
  website/versioned_docs/version-0.64/dimensions.md
Labels: CLA Signed

#2705 docs: typo correction
  docs/network.md
Labels: CLA Signed

#2707 docs: remove inactive link
  website/src/pages/help.md
Labels: CLA Signed

#2708 website: add required labels TextInput
  docs/textinput.md
  website/versioned_docs/version-0.64/textinput.md
Labels: CLA Signed

#2709 add dark mode specific version of RN components diagram
  docs/intro-react-native-components.md
  website/static/docs/assets/diagram_react-native-components.svg
  website/static/docs/assets/diagram_react-native-components_dark.svg
  website/versioned_docs/version-0.64/intro-react-native-components.md
Labels: CLA Signed, Design
