Repository facebook/react-native-website, pull requests merged in 2021-05, with the labels that each got.

#2604 Remove mention of a closed issue in the documentation
  docs/text.md
  website/versioned_docs/version-0.64/text.md
Labels: CLA Signed

#2606 Update references to requireNativeComponent in the versioned iOS Native Components docs
  website/versioned_docs/version-0.60/native-components-ios.md
  website/versioned_docs/version-0.61/native-components-ios.md
  website/versioned_docs/version-0.62/native-components-ios.md
  website/versioned_docs/version-0.63/native-components-ios.md
  website/versioned_docs/version-0.64/native-components-ios.md
Labels: CLA Signed

#2607 String Change
  docs/intro-react.md
Labels: CLA Signed

#2573 Upgrade website to Docusaurus using webpack 5
  .eslintrc.json
  netlify.toml
  package.json
  website/package.json
  website/src/css/customTheme.scss
  yarn.lock
Labels: CLA Signed, 🦖 Docusaurus

#2616 Adding survey link for 1% of visitors
  website/docusaurus.config.js
Labels: CLA Signed, Partner, p: Facebook

#2617 Updating proton native project not maintained!
  docs/out-of-tree-platforms.md
Labels: CLA Signed

#2618 GAAD 1 year later blog post 5/20
  website/blog/2021-05-20-GAAD-One-Year-Later.md
Labels: CLA Signed

#2623 GAAD Article Hot-fix
  website/blog/2021-05-20-GAAD-One-Year-Later.md
Labels: CLA Signed

#2622 Docs: Update sectionlist.md
  docs/sectionlist.md
  website/versioned_docs/version-0.64/sectionlist.md
Labels: CLA Signed

#2615 about installation using the sdkmanager command
  docs/_getting-started-macos-android.md
Labels: CLA Signed

#2621 Update usewindowdimensions.md
  docs/usewindowdimensions.md
Labels: CLA Signed

#2619 fix text in hamburger menu for mobile devices
  website/src/css/customTheme.scss
Labels: CLA Signed

#2624 Update Direct Manipulation docs to mention TextInput's .clear()
  docs/direct-manipulation.md
Labels: CLA Signed

#2631 Removed "TextInput" from the imports as it was never used.
  docs/intro-react.md
Labels: CLA Signed
