Repository facebook/react-native-website, pull requests merged in 2022-06, with the labels that each got.

#3137 correction on tvParallaxProperties
  docs/touchableopacity.md
Labels: CLA Signed

#3140 upgrade Docusuarus, reswizzle and fix Blog sidebars
  netlify.toml
  website/package.json
  website/src/css/customTheme.scss
  website/src/theme/BlogSidebar/Desktop/index.d.ts
  website/src/theme/BlogSidebar/Desktop/index.js
  website/src/theme/BlogSidebar/Desktop/styles.module.css
  website/src/theme/BlogSidebar/Mobile/index.d.ts
  website/src/theme/BlogSidebar/Mobile/index.js
  website/src/theme/BlogSidebar/Mobile/styles.module.css
  website/src/theme/BlogSidebar/index.js
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#3145 alternative fix for the CodeBlocks background
  website/core/PrismTheme.js
  website/src/css/customTheme.scss
Labels: Partner, p: expo, CLA Signed

#3141 docs: add automaticallyAdjustKeyboardInsets to scrollview props
  docs/scrollview.md
  website/versioned_docs/version-0.68/scrollview.md
Labels: CLA Signed

#3147 Update _getting-started-linux-android.md
  docs/_getting-started-linux-android.md
Labels: CLA Signed

#3151 Updated TextInput multiline property
  docs/textinput.md
Labels: CLA Signed

#3092 Add a page about React 18 & Concurrent React
  docs/react-18-and-react-native.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#3157 Remove backtick from readme
  README.md
Labels: CLA Signed

#3159 Add a page explaining Bundled Hermes
  docs/hermes.md
  website/architecture/bundled-hermes.md
  website/sidebarsArchitecture.json
Labels: Partner, p: Facebook, CLA Signed

#3158 Add steps for release testing
  website/contributing/release-candidate-minor.md
  website/contributing/release-candidate-patch.md
  website/contributing/release-stable-minor.md
  website/contributing/release-stable-patch.md
Labels: Partner, CLA Signed, p: shopify

#3161 Fix typos for the bundled hermes docs
  docs/hermes.md
  website/architecture/bundled-hermes.md
Labels: Partner, CLA Signed, p: shopify

#3150 Add Kotlin to docs/_integration-with-exisiting-apps-java
  docs/_integration-with-existing-apps-kotlin.md
  docs/integration-with-existing-apps.md
Labels: CLA Signed

#3162 Add Build Tools for Visual Studio 2022 to Bundled Hermes
  website/architecture/bundled-hermes.md
Labels: Partner, p: Facebook, CLA Signed

#3125 Add Kotlin code for "headless-js-android" documentation
  docs/headless-js-android.md
  website/versioned_docs/version-0.68/headless-js-android.md
Labels: CLA Signed

#3163 [Blog Post] Resources - Migrating Your React Native Library to the New Architecture
  website/blog/2022-06-16-resources-migrating-your-react-native-library-to-the-new-architecture.md
  website/blog/authors.yml
  website/static/blog/assets/new-arch-example-steps-to-migrate-an-app.png
Labels: Partner, p: Facebook, CLA Signed

#3120 Move the remaining RN wiki content to website
  .alexignore
  CONTRIBUTING.md
  README.md
  website/architecture/bundled-hermes.md
  website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
  website/blog/2022-01-19-version-067.md
  website/blog/2022-01-21-react-native-h2-2021-recap.md
  website/blog/2022-03-15-an-update-on-the-new-architecture-rollout.md
  website/blog/2022-03-30-version-068.md
  website/contributing/bots-reference.md
  website/contributing/changelogs-in-pull-requests.md
  website/contributing/contributing-overview.md
  website/contributing/contribution-license-agreement.md
  website/contributing/how-to-build-from-source.md
  website/contributing/how-to-contribute-code.md
  website/contributing/how-to-contribute.md
  website/contributing/how-to-file-an-issue.md
  website/contributing/how-to-open-a-pull-request.md
  website/contributing/how-to-run-and-write-tests.md
  website/contributing/labeling-github-issues.md
  website/contributing/managing-pull-requests.md
  website/contributing/release-candidate-minor.md
  website/contributing/release-roles-responsibilites.md
  website/contributing/release-stable-minor.md
  website/contributing/release-stable-patch.md
  website/contributing/release-testing.md
  website/contributing/triaging-github-issues.md
  website/docusaurus.config.js
  website/sidebarsArchitecture.json
  website/sidebarsContributing.json
  website/src/css/customTheme.scss
  website/static/_redirects
  website/static/img/importing-pull-requests.png
Labels: Partner, p: expo, CLA Signed

#3171 correct redirect for Contributing section landing page
  website/static/_redirects
Labels: Partner, p: expo, CLA Signed

#3169 small tweaks for the CodeBlocks appearance
  website/src/css/customTheme.scss
Labels: Partner, p: expo, CLA Signed

#3170 replace old blockquotes with admonitions, add codeblocks titles (part 1)
  docs/accessibility.md
  docs/colors.md
  docs/communication-ios.md
  docs/direct-manipulation.md
  docs/flexbox.md
  docs/height-and-width.md
  docs/hermes.md
  docs/images.md
  docs/linking-libraries-ios.md
  docs/native-components-ios.md
  docs/navigation.md
  docs/profile-hermes.md
  docs/profiling.md
  docs/publishing-to-app-store.md
  docs/ram-bundles-inline-requires.md
  docs/signed-apk-android.md
  docs/timers.md
Labels: Partner, p: expo, CLA Signed

#3164 Blog post for 0.69 RN release
  website/blog/2022-06-21-version-069.md
  website/blog/authors.yml
Labels: Partner, CLA Signed, p: shopify

#3173 Update diff-purge docs link with permalinks
  website/contributing/updating-upgrade-helper.md
Labels: Partner, p: Facebook, CLA Signed

#3175 added a note in running your app on real device section
  docs/running-on-device.md
Labels: CLA Signed

#3156 Add userInterfaceStyle option to Alert
  docs/alert.md
Labels: Wait on future Release, CLA Signed

#3131 Update accessibilityIgnoresInvertColors property
  docs/accessibility.md
Labels: CLA Signed

#2959 fix: spring damping error in example
  docs/layoutanimation.md
Labels: CLA Signed

#3166 Fix for "Type 'Timeout' is not assignable to type 'number'"
  docs/typescript.md
Labels: CLA Signed

#3180 correct link in 0.69 blogpost
  website/blog/2022-06-21-version-069.md
Labels: Partner, p: expo, CLA Signed

#3153 [FEAT][TNA] Fabric Component - Add Component to App (Android)
  docs/the-new-architecture/pillars-fabric-components.md
Labels: Partner, p: Facebook, CLA Signed

#3149 [FEAT][TNA] Fabric Component - Add Component to App (iOS)
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars.md
Labels: Partner, p: Facebook, CLA Signed

#3136 [FEAT][TNA] Fabric Component - Add Configuration Files
  docs/the-new-architecture/landing-page.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars.md
  docs/the-new-architecture/use-app-template.md
  website/core/TabsConstants.js
Labels: Partner, p: Facebook, CLA Signed

#3181 Update release steps
  website/contributing/release-candidate-minor.md
  website/contributing/release-stable-minor.md
  website/contributing/release-stable-patch.md
Labels: Partner, CLA Signed, p: shopify

#3174 Update troubleshooting.md
  docs/troubleshooting.md
Labels: CLA Signed

#3184 Fix outdated "JavaScript Syntax Transformers"
  docs/javascript-environment.md
  website/versioned_docs/version-0.65/javascript-environment.md
  website/versioned_docs/version-0.66/javascript-environment.md
  website/versioned_docs/version-0.67/javascript-environment.md
  website/versioned_docs/version-0.68/javascript-environment.md
  website/versioned_docs/version-0.69/javascript-environment.md
Labels: CLA Signed

#3185 Just removed a typing mistake.
  docs/intro-react-native-components.md
  website/versioned_docs/version-0.69/intro-react-native-components.md
Labels: CLA Signed

#3178 docs(jdk): recommend JDK 11. JDK18 will not work. JDK17 may not work < 0.68
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-windows-android.md
Labels: sony, CLA Signed

#3187 Fix invocation of bump script command
  website/contributing/release-candidate-minor.md
  website/contributing/release-candidate-patch.md
  website/contributing/release-stable-minor.md
  website/contributing/release-stable-patch.md
Labels: Partner, CLA Signed, p: shopify
