Repository facebook/react-native-website, pull requests merged in 2022-12, with the labels that each got.

#3445 Add [Breaking] to commit changelog documentation
  website/contributing/changelogs-in-pull-requests.md
Labels: Partner, p: Facebook, CLA Signed

#3447 fix changelog entries
  website/contributing/changelogs-in-pull-requests.md
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3444 Update TS Instructions for Simplified Template
  docs/typescript.md
Labels: Partner, p: Facebook, CLA Signed

#3446 [0.71] Update page on Integration with Existing Apps for 71
  docs/_integration-with-exisiting-apps-java.md
  docs/_integration-with-existing-apps-kotlin.md
Labels: Partner, p: Facebook, CLA Signed

#3450 Start TypeScriptify-ing the examples
  docs/accessibilityinfo.md
  docs/actionsheetios.md
  docs/activityindicator.md
  docs/alert.md
  docs/animated.md
  docs/animatedvaluexy.md
  docs/animations.md
  docs/appstate.md
  docs/backhandler.md
  docs/checkbox.md
  docs/datepickerios.md
  docs/dimensions.md
  docs/direct-manipulation.md
  docs/flexbox.md
  docs/handling-touches.md
  docs/image.md
  docs/improvingux.md
  docs/layout-props.md
  docs/network.md
  docs/permissionsandroid.md
  docs/settings.md
  docs/share.md
  docs/text-style-props.md
  docs/touchablenativefeedback.md
  docs/using-a-listview.md
  docs/vibration.md
  docs/virtualizedlist.md
  scripts/lint-examples/bin/eslint-examples-js.js
  scripts/lint-examples/bin/eslint-examples-tsx.js
  scripts/lint-examples/bin/tsc-examples.js
  scripts/lint-examples/package.json
  scripts/lint-examples/src/lintExamples.js
  scripts/lint-examples/tsconfig.json
  website/core/TabsConstants.js
  website/package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#3457 Update ignite blurb on more resources
  docs/more-resources.md
Labels: CLA Signed

#3452 Updated the installation instructions
  docs/getting-started.md
Labels: CLA Signed

#3459 Typescriptify Examples A-F
  docs/direct-manipulation.md
  docs/drawerlayoutandroid.md
  docs/easing.md
  docs/flatlist.md
  docs/flexbox.md
  package.json
  scripts/lint-examples/patches/react-native+0.71.0-rc.0.patch
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#3460 Typescriptify Examples H-J
  docs/handling-touches.md
  docs/image-style-props.md
  docs/improvingux.md
  docs/interactionmanager.md
  docs/intro-react.md
Labels: Partner, p: Facebook, CLA Signed

#3461 Typescriptify Examples K-P
  docs/keyboard.md
  docs/layout-props.md
  docs/linking.md
  docs/modal.md
  docs/network.md
  docs/panresponder.md
  docs/props.md
Labels: Partner, p: Facebook, CLA Signed

#3449 [0.71] Update page on Enabling Hermes for 71
  docs/hermes.md
Labels: Partner, p: Facebook, CLA Signed

#3462 Add Vincent Riemer as a blog post author
  website/blog/authors.yml
Labels: Partner, p: Facebook, CLA Signed

#3463 Fix rendering of snacks on route update on mobile
  website/snackPlayerInitializer.js
Labels: Partner, p: Facebook, CLA Signed

#3475 Refine the "Pointer Events in React Native" blog post's intro
  website/blog/2022-12-13-pointer-events-in-react-native.md
Labels: Partner, p: Facebook, CLA Signed

#3473 Typescriptify Examples Q-S
  docs/refreshcontrol.md
  docs/sectionlist.md
  docs/segmentedcontrolios.md
  docs/settings.md
  docs/shadow-props.md
  docs/share.md
  docs/state.md
  docs/statusbar.md
  docs/stylesheet.md
  package.json
  scripts/lint-examples/patches/react-native+0.71.0-rc.0.patch
Labels: Partner, p: Facebook, CLA Signed

#3476 [0.71] Add page on React Native Gradle Plugin for 71
  docs/react-native-gradle-plugin.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#3453 [0.71][Android] Update pages on New Architecture for 71
  docs/build-speed.md
  docs/new-architecture-app-intro.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-troubleshooting.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: Facebook, CLA Signed

#3439 Add Cxx TurboModule Guide
  docs/the-new-architecture/cxx-custom-types.md
  docs/the-new-architecture/cxx-cxxturbomodules.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#3471 fix: remove explicit folly version as it's not needed anymore
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.68/new-architecture-library-ios.md
  website/versioned_docs/version-0.69/new-architecture-library-ios.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
Labels: CLA Signed

#3481 Update community staying-updated.md
  website/community/staying-updated.md
Labels: CLA Signed

#3482 chore: fix objective-c syntax highlighting on fabric guide
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
Labels: CLA Signed

#3474 Typescriptify Examples T-Z (and enforce)
  .circleci/config.yml
  docs/text-style-props.md
  docs/text.md
  docs/textinput.md
  docs/toastandroid.md
  docs/touchablehighlight.md
  docs/touchableopacity.md
  docs/tutorial.md
  docs/using-a-listview.md
  docs/virtualizedlist.md
  scripts/lint-examples/src/lintExamples.js
  website/package.json
Labels: Partner, p: Facebook, CLA Signed

#3478 Update Inline JSX and Type Definitions (2/2)
  docs/new-architecture-library-intro.md
  docs/optimizing-flatlist-configuration.md
  docs/panresponder.md
  docs/performance.md
  docs/permissionsandroid.md
  docs/pixelratio.md
  docs/platform-specific-code.md
  docs/platform.md
  docs/pressable.md
  docs/pushnotificationios.md
  docs/ram-bundles-inline-requires.md
  docs/scrollview.md
  docs/sectionlist.md
  docs/settings.md
  docs/share.md
  docs/statusbar.md
  docs/stylesheet.md
  docs/switch.md
  docs/systrace.md
  docs/testing-overview.md
  docs/text-style-props.md
  docs/text.md
  docs/textinput.md
  docs/the-new-architecture/cxx-cxxturbomodules.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
  docs/timers.md
  docs/toastandroid.md
  docs/touchablehighlight.md
  docs/touchablenativefeedback.md
  docs/touchablewithoutfeedback.md
  docs/tutorial.md
  docs/usecolorscheme.md
  docs/usewindowdimensions.md
  docs/vibration.md
  docs/view.md
  docs/viewtoken.md
  docs/virtualizedlist.md
Labels: Partner, p: Facebook, CLA Signed

#3483 Make C++ TM example work with C++17
  docs/the-new-architecture/cxx-custom-types.md
Labels: Partner, p: Facebook, CLA Signed

#3484 Update AccessibilityInfo Inline JSX to TSX
  docs/accessibilityinfo.md
Labels: Partner, p: Facebook, CLA Signed

#3448 Rename `POST_NOTIFICATION` to `POST_NOTIFICATIONS`
  docs/permissionsandroid.md
Labels: :clock1: Waiting on PR, Wait on future Release, CLA Signed

#3486 Update Linting to RN 0.71.0-rc.5
  package.json
  scripts/lint-examples/package.json
  scripts/lint-examples/patches/react-native+0.71.0-rc.0.patch
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#3489 Remove `NativeDeprecated` from "Direct Manipulation" page
  docs/direct-manipulation.md
Labels: Partner, p: Facebook, CLA Signed
