Repository facebook/react-native-website, pull requests merged in 2022-05, with the labels that each got.

#3102 Make the 'new' badge float right in mobile
  website/src/css/customTheme.scss
Labels: CLA Signed

#3103 Update version compare from latest to right now
  website/src/pages/versions.js
Labels: CLA Signed

#3077 docs: add to Build app for Release.
  docs/publishing-to-app-store.md
Labels: CLA Signed

#3093 Updating release instructions with Hermes bump steps
  website/contributing/release-candidate-minor.md
Labels: Partner, p: Facebook, CLA Signed

#3060 Update custom webview documentation with kotlin code examples
  docs/custom-webview-android.md
Labels: CLA Signed

#3107 Clarify usage of Ruby version managers
  docs/_getting-started-macos-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3109 Clarify how to enable hermes since RN 0.68
  docs/hermes.md
  website/versioned_docs/version-0.68/hermes.md
Labels: Partner, p: Facebook, CLA Signed

#3111 [fix] add documentation about how to configure Folly properly
  docs/new-architecture-app-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3113 docs: fix the mismatch between android version name and its API level
  docs/_getting-started-windows-android.md
Labels: CLA Signed

#3110 Update picker to be Removed since RN 0.66
  docs/picker-item.md
  docs/picker-style-props.md
  docs/picker.md
  docs/pickerios.md
  website/versioned_docs/version-0.66/picker.md
  website/versioned_docs/version-0.66/pickerios.md
  website/versioned_docs/version-0.67/picker-item.md
  website/versioned_docs/version-0.67/picker-style-props.md
  website/versioned_docs/version-0.67/picker.md
  website/versioned_docs/version-0.67/pickerios.md
  website/versioned_docs/version-0.68/picker-item.md
  website/versioned_docs/version-0.68/picker-style-props.md
  website/versioned_docs/version-0.68/picker.md
  website/versioned_docs/version-0.68/pickerios.md
Labels: Partner, p: Facebook, CLA Signed

#3116 Add Kotlin to docs/new-architecture-library-intro
  docs/new-architecture-library-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3117 Update RN Geolocation library URL.
  docs/communication-ios.md
Labels: CLA Signed

#2845 solution for Error: spawnSync ./gradlew EACCES
  docs/troubleshooting.md
Labels: CLA Signed

#3121 [FIX] iOS: Setup Folly Title
  docs/new-architecture-app-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3122 Remove "Add Babel Plugins" Section
  docs/new-architecture-app-renderer-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3124 Blogpost: React Native Accessibility - GAAD 2022 Update
  website/blog/2022-05-19-GAAD-2022-update.md
Labels: Partner, p: Facebook, CLA Signed

#3128 Update _getting-started-macos-android.md
  docs/_getting-started-macos-android.md
Labels: CLA Signed

#3130 Getting Started: fix typo
  docs/_getting-started-macos-android.md
Labels: Partner, p: expo, CLA Signed

#3129 Update PWA Manifest and Maskable images
  website/package.json
  website/static/img/pwa/apple-icon-180.png
  website/static/img/pwa/manifest-icon-192.png
  website/static/img/pwa/manifest-icon-512.png
  website/static/manifest.json
Labels: CLA Signed

#3138 For Windows Run command prompt as administrator
  docs/signed-apk-android.md
Labels: CLA Signed
