Repository facebook/react-native-website, pull requests merged in 2022-01, with the labels that each got.

#2905 architecture section small tweaks
  docs/architecture-glossary.md
  docs/fabric-renderer.md
  docs/render-pipeline.md
  docs/view-flattening.md
  docs/xplat-implementation.md
  website/sidebars.json
  website/versioned_docs/version-0.66/architecture-glossary.md
  website/versioned_docs/version-0.66/fabric-renderer.md
  website/versioned_docs/version-0.66/render-pipeline.md
  website/versioned_docs/version-0.66/view-flattening.md
  website/versioned_docs/version-0.66/xplat-implementation.md
  website/versioned_sidebars/version-0.66-sidebars.json
Labels: Partner, p: expo, CLA Signed

#2882 split The New Architecture guide into few pages
  docs/new-architecture-app-intro.md
  docs/new-architecture-app-modules-android.md
  docs/new-architecture-app-modules-ios.md
  docs/new-architecture-app-renderer-android.md
  docs/new-architecture-app-renderer-ios.md
  docs/new-architecture-appendix.md
  docs/new-architecture-intro.md
  docs/new-architecture-library-android.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-library-ios.md
  docs/new-architecture-playbook.md
  website/sidebars.json
Labels: Partner, p: expo, CLA Signed

#2915 feat: add cancelButtonTintColor props in ActionSheetIOS for change cancel tint color
  docs/actionsheetios.md
Labels: CLA Signed

#2369 change Docs sidebar groupings, add small indentation for pages, adjust sidebar design
  website/sidebars.json
  website/src/css/customTheme.scss
Labels: Design, CLA Signed

#2917 Correct link to the docs
  docs/sectionlist.md
  website/versioned_docs/version-0.60/sectionlist.md
  website/versioned_docs/version-0.61/sectionlist.md
  website/versioned_docs/version-0.62/sectionlist.md
  website/versioned_docs/version-0.63/sectionlist.md
  website/versioned_docs/version-0.64/sectionlist.md
  website/versioned_docs/version-0.65/sectionlist.md
  website/versioned_docs/version-0.66/sectionlist.md
Labels: CLA Signed

#2918 update Docusaurus, fix layout issues, fix warnings
  website/docusaurus.config.js
  website/package.json
  website/src/css/customTheme.scss
  website/src/theme/BlogSidebar/index.js
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#2921 Adding a command
  README.md
Labels: CLA Signed

#2925 update name in tutorial.md
  docs/tutorial.md
Labels: CLA Signed

#2923 docs: adds `View props` to props section of Modal
  docs/modal.md
Labels: CLA Signed

#2929 Migrate from probot/stale to actions/stale
  .github/stale.yml
  .github/workflows/stale-bot.yml
Labels: 🧰 Infra, Partner, p: Facebook, CLA Signed

#2928 switch to esbuild-loader, add Flow highlight support
  website/docusaurus.config.js
  website/package.json
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#2935 Use descriptive component names and fix use of ref
  docs/new-architecture-library-intro.md
Labels: Partner, p: Facebook, CLA Signed

#2800 Adopt OpenJDK11
  docs/_getting-started-macos-android.md
  docs/_getting-started-windows-android.md
Labels: Wait on future Release, CLA Signed

#2933 blogpost for 0.67
  website/blog/2022-01-19-version-067.md
  website/blog/authors.yml
Labels: Partner, Contributor, p: microsoft, CLA Signed

#2937 blogpost: React Native - H2 2021 Recap
  website/blog/2022-01-21-react-native-h2-2021-recap.md
  website/blog/authors.yml
Labels: Partner, p: Facebook, CLA Signed

#2938 Fix typo in H2 blog post: next year -> this year
  website/blog/2022-01-21-react-native-h2-2021-recap.md
Labels: Partner, p: Facebook, CLA Signed

#2943 docs: remove text running-on-device
  website/versioned_docs/version-0.67/running-on-device.md
Labels: CLA Signed

#2944 remove text on docs running-on-device
  docs/running-on-device.md
Labels: CLA Signed

#2942 Fix small grammatical error
  docs/using-a-scrollview.md
Labels: CLA Signed

#2945 Fix flexShrink default value in Layout Props docs
  docs/layout-props.md
Labels: CLA Signed

#2947 update website font, misc UI tweaks
  website/src/css/customTheme.scss
  website/src/css/index.scss
  website/src/pages/showcase.js
  website/static/img/homepage/cross-platform.svg
Labels: Partner, p: expo, CLA Signed
