Repository facebook/react-native-website, pull requests merged in 2022-08, with the labels that each got.

#3200 [TNA][Review] Review of the New Architecture guide
  docs/direct-manipulation.md
  docs/intro-react-native-components.md
  docs/introduction.md
  docs/more-resources.md
  docs/native-components-android.md
  docs/native-components-ios.md
  docs/native-modules-android.md
  docs/native-modules-intro.md
  docs/native-modules-ios.md
  docs/native-modules-setup.md
  docs/new-architecture-app-intro.md
  docs/new-architecture-app-modules-android.md
  docs/new-architecture-app-renderer-ios.md
  docs/new-architecture-appendix.md
  docs/new-architecture-intro.md
  docs/new-architecture-library-android.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-library-ios.md
  docs/react-18-and-react-native.md
  docs/the-new-architecture/_markdown_native_deprecation.mdx
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-troubleshooting.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/backward-compatibility.md
  docs/the-new-architecture/landing-page.md
  docs/the-new-architecture/pillars-codegen.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
  docs/the-new-architecture/pillars.md
  docs/the-new-architecture/use-app-template.md
  docs/the-new-architecture/why.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#3238 Add more info to Prerequisites for Libraries guide
  docs/new-architecture-library-intro.md
  website/versioned_docs/version-0.68/new-architecture-library-intro.md
  website/versioned_docs/version-0.69/new-architecture-library-intro.md
Labels: CLA Signed

#3225 [Documentation] iOS Simulator version&udid
  docs/running-on-simulator-ios.md
Labels: CLA Signed

#3242 Add retrospective as a copilot responsibility
  website/contributing/release-roles-responsibilites.md
Labels: Partner, CLA Signed, p: shopify

#3240 update release related docs page
  website/contributing/_markdown-async-testing-note.mdx
  website/contributing/release-branch-cut-and-rc0.md
  website/contributing/release-candidate-patch.md
  website/contributing/release-roles-responsibilites.md
  website/contributing/release-stable-patch.md
  yarn.lock
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3236 chore: Specify return vs resolve
  docs/linking.md
Labels: Partner, p: microsoft, CLA Signed

#3218 update Docusaurus and other dependencies
  .alexrc.js
  docs/debugging.md
  docs/native-components-android.md
  docs/new-architecture-library-intro.md
  docs/running-on-device.md
  docs/textinput.md
  package.json
  website/architecture/architecture-overview.md
  website/blog/2018-04-09-build-com-app.md
  website/blog/2021-08-26-many-platform-vision.md
  website/blog/2021-10-26-toward-hermes-being-the-default.md
  website/package.json
  website/versioned_docs/version-0.60/colors.md
  website/versioned_docs/version-0.60/debugging.md
  website/versioned_docs/version-0.60/native-components-android.md
  website/versioned_docs/version-0.60/running-on-device.md
  website/versioned_docs/version-0.61/colors.md
  website/versioned_docs/version-0.61/debugging.md
  website/versioned_docs/version-0.61/native-components-android.md
  website/versioned_docs/version-0.61/running-on-device.md
  website/versioned_docs/version-0.62/debugging.md
  website/versioned_docs/version-0.62/running-on-device.md
  website/versioned_docs/version-0.63/debugging.md
  website/versioned_docs/version-0.63/native-components-android.md
  website/versioned_docs/version-0.63/running-on-device.md
  website/versioned_docs/version-0.64/debugging.md
  website/versioned_docs/version-0.64/running-on-device.md
  website/versioned_docs/version-0.65/debugging.md
  website/versioned_docs/version-0.65/running-on-device.md
  website/versioned_docs/version-0.66/debugging.md
  website/versioned_docs/version-0.66/running-on-device.md
  website/versioned_docs/version-0.67/debugging.md
  website/versioned_docs/version-0.67/running-on-device.md
  website/versioned_docs/version-0.68/debugging.md
  website/versioned_docs/version-0.68/native-components-android.md
  website/versioned_docs/version-0.68/new-architecture-library-intro.md
  website/versioned_docs/version-0.68/running-on-device.md
  website/versioned_docs/version-0.69/debugging.md
  website/versioned_docs/version-0.69/new-architecture-library-intro.md
  website/versioned_docs/version-0.69/running-on-device.md
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#3241 Add kotlin examples in new-architecture-app-modules-android.md
  docs/new-architecture-app-modules-android.md
Labels: CLA Signed

#3244 Change links in main home page
  website/src/pages/index.js
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3037 Refactoring The New Architecture Guide
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  docs/_remove-global-cli.md
  docs/build-speed.md
  docs/direct-manipulation.md
  docs/intro-react-native-components.md
  docs/introduction.md
  docs/more-resources.md
  docs/native-components-android.md
  docs/native-components-ios.md
  docs/native-modules-android.md
  docs/native-modules-intro.md
  docs/native-modules-ios.md
  docs/native-modules-setup.md
  docs/new-architecture-app-intro.md
  docs/new-architecture-app-modules-android.md
  docs/new-architecture-app-renderer-ios.md
  docs/new-architecture-appendix.md
  docs/new-architecture-intro.md
  docs/new-architecture-library-android.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-library-ios.md
  docs/react-18-and-react-native.md
  docs/the-new-architecture/_markdown_beta_ts_support.mdx
  docs/the-new-architecture/_markdown_native_deprecation.mdx
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/backward-compatibility.md
  docs/the-new-architecture/landing-page.md
  docs/the-new-architecture/pillars-codegen.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
  docs/the-new-architecture/pillars.md
  docs/the-new-architecture/use-app-template.md
  docs/the-new-architecture/why.md
  website/core/TabsConstants.js
  website/package.json
  website/sidebars.json
  website/static/docs/assets/metro-new-arch.png
  website/versioned_docs/version-0.68/build-speed.md
  website/versioned_docs/version-0.68/new-architecture-app-intro.md
  website/versioned_docs/version-0.68/new-architecture-app-modules-android.md
  website/versioned_docs/version-0.69/build-speed.md
  website/versioned_docs/version-0.69/new-architecture-app-intro.md
  website/versioned_docs/version-0.69/new-architecture-app-modules-android.md
Labels: Partner, p: Facebook, CLA Signed

#3247 Fix typo in the sidebar
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#3246 Delete ubereats.png
  website/static/img/showcase/ubereats.png
Labels: CLA Signed

#3253 Update android studio screenshot
  docs/_getting-started-macos-android.md
  website/static/docs/assets/GettingStartedAndroidStudioWelcomeMacOS.png
  website/versioned_docs/version-0.60/_getting-started-macos-android.md
  website/versioned_docs/version-0.61/_getting-started-macos-android.md
  website/versioned_docs/version-0.62/_getting-started-macos-android.md
  website/versioned_docs/version-0.63/_getting-started-macos-android.md
  website/versioned_docs/version-0.64/_getting-started-macos-android.md
  website/versioned_docs/version-0.65/_getting-started-macos-android.md
  website/versioned_docs/version-0.66/_getting-started-macos-android.md
  website/versioned_docs/version-0.67/_getting-started-macos-android.md
  website/versioned_docs/version-0.68/_getting-started-macos-android.md
  website/versioned_docs/version-0.69/_getting-started-macos-android.md
Labels: CLA Signed

#3254 Adding Android 13 Permissions into PermissionsAndroid
  docs/permissionsandroid.md
Labels: CLA Signed

#3255 Adding cursorColor Props On TextInput Android
  docs/textinput.md
Labels: CLA Signed

#3257 Update Android Studio screenshot (Windows)
  docs/_getting-started-windows-android.md
  website/static/docs/assets/GettingStartedAndroidStudioWelcomeWindows.png
  website/versioned_docs/version-0.60/_getting-started-windows-android.md
  website/versioned_docs/version-0.61/_getting-started-windows-android.md
  website/versioned_docs/version-0.62/_getting-started-windows-android.md
  website/versioned_docs/version-0.63/_getting-started-windows-android.md
  website/versioned_docs/version-0.64/_getting-started-windows-android.md
  website/versioned_docs/version-0.65/_getting-started-windows-android.md
  website/versioned_docs/version-0.66/_getting-started-windows-android.md
  website/versioned_docs/version-0.67/_getting-started-windows-android.md
  website/versioned_docs/version-0.68/_getting-started-windows-android.md
  website/versioned_docs/version-0.69/_getting-started-windows-android.md
Labels: CLA Signed

#3256 docs (releases): small refactoring and updating templates
  website/contributing/_markdown-GH-release-notes-prerelease.mdx
  website/contributing/_markdown-road-to-release-template.mdx
  website/contributing/release-branch-cut-and-rc0.md
  website/contributing/release-candidate-patch.md
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3259 Update documentation for keyboard events on Android
  docs/keyboard.md
Labels: Partner, p: Facebook, CLA Signed

#3248 Update to Docusaurus stable release, fix alert admonition styling
  website/package.json
  website/src/css/customTheme.scss
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#3263 chore(releases): remove old references to testers
  website/contributing/release-branch-cut-and-rc0.md
  website/contributing/release-candidate-patch.md
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3249 adding accessibilityLabelledBy to documentation
  docs/accessibility.md
  website/versioned_docs/version-0.68/accessibility.md
  website/versioned_docs/version-0.69/accessibility.md
Labels: CLA Signed

#3267 Update references to Expo / Expo CLI
  docs/appregistry.md
  docs/debugging.md
  docs/getting-started.md
  docs/linking.md
  docs/permissionsandroid.md
  docs/publishing-to-app-store.md
  docs/pushnotificationios.md
  docs/running-on-device.md
  docs/signed-apk-android.md
  docs/typescript.md
  docs/upgrading.md
  website/core/TabsConstants.js
  website/versioned_docs/version-0.69/appregistry.md
  website/versioned_docs/version-0.69/debugging.md
  website/versioned_docs/version-0.69/getting-started.md
  website/versioned_docs/version-0.69/linking.md
  website/versioned_docs/version-0.69/more-resources.md
  website/versioned_docs/version-0.69/permissionsandroid.md
  website/versioned_docs/version-0.69/publishing-to-app-store.md
  website/versioned_docs/version-0.69/pushnotificationios.md
  website/versioned_docs/version-0.69/running-on-device.md
  website/versioned_docs/version-0.69/signed-apk-android.md
  website/versioned_docs/version-0.69/typescript.md
  website/versioned_docs/version-0.69/upgrading.md
Labels: Partner, p: expo, CLA Signed

#3258 feat(images): Adding iOS Image Cache Limits
  docs/images.md
  website/versioned_docs/version-0.69/images.md
Labels: CLA Signed

#3261 nit: fix typo in new architecture docs
  docs/the-new-architecture/pillars-codegen.md
  docs/the-new-architecture/pillars-fabric-components.md
Labels: CLA Signed

#3271 fix(images): move app-transport-security reference
  docs/images.md
  docs/network.md
  website/versioned_docs/version-0.60/images.md
  website/versioned_docs/version-0.60/network.md
  website/versioned_docs/version-0.61/images.md
  website/versioned_docs/version-0.61/network.md
  website/versioned_docs/version-0.62/images.md
  website/versioned_docs/version-0.62/network.md
  website/versioned_docs/version-0.63/images.md
  website/versioned_docs/version-0.63/network.md
  website/versioned_docs/version-0.64/images.md
  website/versioned_docs/version-0.64/network.md
  website/versioned_docs/version-0.65/images.md
  website/versioned_docs/version-0.65/network.md
  website/versioned_docs/version-0.66/images.md
  website/versioned_docs/version-0.66/network.md
  website/versioned_docs/version-0.67/images.md
  website/versioned_docs/version-0.67/network.md
  website/versioned_docs/version-0.68/images.md
  website/versioned_docs/version-0.68/network.md
  website/versioned_docs/version-0.69/images.md
  website/versioned_docs/version-0.69/network.md
Labels: CLA Signed

#3282 Move the "Using `forwardRef`" and "Using a `getter`" sections to a lower hierarchy level
  docs/new-architecture-library-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3283 Upgrade toast Android example to camelCase
  docs/toastandroid.md
  website/versioned_docs/version-0.62/toastandroid.md
  website/versioned_docs/version-0.63/toastandroid.md
  website/versioned_docs/version-0.64/toastandroid.md
  website/versioned_docs/version-0.65/toastandroid.md
  website/versioned_docs/version-0.66/toastandroid.md
  website/versioned_docs/version-0.67/toastandroid.md
  website/versioned_docs/version-0.68/toastandroid.md
  website/versioned_docs/version-0.69/toastandroid.md
Labels: CLA Signed
