Repository facebook/react-native-website, pull requests merged in 2022-04, with the labels that each got.

#3048 Add missing semicolon in native modules guide
  docs/native-modules-android.md
  docs/native-modules-ios.md
  website/versioned_docs/version-0.63/native-modules-android.md
  website/versioned_docs/version-0.63/native-modules-ios.md
  website/versioned_docs/version-0.64/native-modules-android.md
  website/versioned_docs/version-0.64/native-modules-ios.md
  website/versioned_docs/version-0.65/native-modules-android.md
  website/versioned_docs/version-0.65/native-modules-ios.md
  website/versioned_docs/version-0.66/native-modules-android.md
  website/versioned_docs/version-0.66/native-modules-ios.md
  website/versioned_docs/version-0.67/native-modules-android.md
  website/versioned_docs/version-0.67/native-modules-ios.md
  website/versioned_docs/version-0.68/native-modules-android.md
  website/versioned_docs/version-0.68/native-modules-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3042 Clarified 0.68 breaking changes
  website/blog/2022-03-30-version-068.md
Labels: CLA Signed

#3050 update Expo links in `next` and `0.68` docs
  docs/debugging.md
  docs/getting-started.md
  docs/libraries.md
  docs/more-resources.md
  docs/permissionsandroid.md
  docs/publishing-to-app-store.md
  docs/pushnotificationios.md
  docs/security.md
  docs/upgrading.md
  website/blog/2017-03-13-introducing-create-react-native-app.md
  website/versioned_docs/version-0.68/debugging.md
  website/versioned_docs/version-0.68/getting-started.md
  website/versioned_docs/version-0.68/libraries.md
  website/versioned_docs/version-0.68/more-resources.md
  website/versioned_docs/version-0.68/permissionsandroid.md
  website/versioned_docs/version-0.68/publishing-to-app-store.md
  website/versioned_docs/version-0.68/pushnotificationios.md
  website/versioned_docs/version-0.68/security.md
  website/versioned_docs/version-0.68/upgrading.md
Labels: Partner, p: expo, CLA Signed

#3049 Add a Troubleshooting section to the Build Speed guide
  docs/build-speed.md
  website/versioned_docs/version-0.68/build-speed.md
Labels: Partner, p: Facebook, CLA Signed

#3062 [ci] switch to next-gen CircleCI img
  .circleci/config.yml
Labels: Partner, p: expo, CLA Signed

#3063 Suggest Zulu11 for all the users (regardless of M1 or not)
  docs/_getting-started-macos-android.md
  website/blog/2022-03-30-version-068.md
  website/versioned_docs/version-0.68/_getting-started-macos-android.md
Labels: Partner, p: Facebook, CLA Signed

#3065 Fix iOS and Android labels under accessibilityHint
  docs/accessibility.md
Labels: CLA Signed

#3038 [Guide - The New Architecture] What Backward Compatibility Is
  docs/the-new-architecture/backward-compatibility.md
Labels: Partner, p: Facebook, CLA Signed

#3067 :children_crossing: improve hermes logo alignment on mobile devices
  docs/hermes.md
  website/src/css/customTheme.scss
  website/versioned_docs/version-0.66/hermes.md
  website/versioned_docs/version-0.67/hermes.md
  website/versioned_docs/version-0.68/hermes.md
Labels: CLA Signed

#3064 Update setup guide node version
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  docs/getting-started.md
  website/versioned_docs/version-0.68/_getting-started-linux-android.md
  website/versioned_docs/version-0.68/_getting-started-macos-android.md
  website/versioned_docs/version-0.68/_getting-started-macos-ios.md
  website/versioned_docs/version-0.68/_getting-started-windows-android.md
  website/versioned_docs/version-0.68/getting-started.md
Labels: CLA Signed

#3059 update Docusaurus and other deps, fix broken styles
  website/docusaurus.config.js
  website/package.json
  website/src/css/customTheme.scss
  website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
  website/versioned_docs/version-0.60/geolocation.md
  website/versioned_docs/version-0.61/geolocation.md
  website/versioned_docs/version-0.62/geolocation.md
  website/versioned_docs/version-0.63/geolocation.md
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#3071 Update release-faq.md
  website/contributing/release-faq.md
Labels: CLA Signed

#3070 Add Kotlin code for "Communication Android" documentation
  docs/communication-android.md
Labels: CLA Signed

#3073 Update patch release instructions
  website/contributing/release-candidate-patch.md
  website/contributing/release-stable-patch.md
  website/contributing/release-testing.md
Labels: Partner, CLA Signed, p: shopify

#3036 Add TypeScript support in New Architecture/Codegen
  docs/new-architecture-library-intro.md
  website/core/TabsConstants.js
Labels: Partner, p: Facebook, CLA Signed

#3078 fix: mistake is function call.
  docs/optimizing-flatlist-configuration.md
Labels: CLA Signed

#3056 Guide to creating a New Architecture app from template
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  docs/_remove-global-cli.md
  docs/the-new-architecture/use-app-template.md
  website/static/docs/assets/metro-new-arch.png
Labels: Partner, CLA Signed, p: Infinite Red

#3072 New Architecture landing page
  docs/the-new-architecture/landing-page.md
Labels: Partner, CLA Signed, p: Infinite Red

#3043 [Guide - The New Architecture] Why A New Architecture
  docs/the-new-architecture/why.md
Labels: Partner, p: Facebook, CLA Signed

#3080 [Doc] add paragraph on .xcode.env
  docs/_getting-started-macos-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3046 [Guide - The New Architecture] Pillars
  docs/the-new-architecture/pillars.md
Labels: Partner, p: Facebook, CLA Signed

#3079 Note for the plugin `transform-remove-console`
  docs/performance.md
  website/versioned_docs/version-0.60/performance.md
  website/versioned_docs/version-0.61/performance.md
  website/versioned_docs/version-0.62/performance.md
  website/versioned_docs/version-0.63/performance.md
  website/versioned_docs/version-0.64/performance.md
  website/versioned_docs/version-0.65/performance.md
  website/versioned_docs/version-0.66/performance.md
  website/versioned_docs/version-0.67/performance.md
  website/versioned_docs/version-0.68/performance.md
Labels: CLA Signed

#3068 Add Kotlin examples in the "Android Native UI Components" documentation
  docs/native-components-android.md
Labels: CLA Signed

#3086 Fixing issue #3082 for missing import in native-components-android
  docs/native-components-android.md
Labels: CLA Signed

#3089 fix typo in threading-model doc
  website/architecture/threading-model.md
Labels: Partner, p: expo, CLA Signed

#3087 Macos/Android Getting Started: M1 mac new system image
  docs/_getting-started-macos-android.md
Labels: CLA Signed

#3090 Update valid values for keyboardType
  docs/textinput.md
  website/versioned_docs/version-0.66/textinput.md
  website/versioned_docs/version-0.67/textinput.md
  website/versioned_docs/version-0.68/textinput.md
Labels: CLA Signed

#3098 customTheme.css (Make Font size smaller in banner)
  website/src/css/customTheme.scss
Labels: CLA Signed

#3099 Fix imporperly formatted code in introduction
  docs/introduction.md
  website/versioned_docs/version-0.60/introduction.md
  website/versioned_docs/version-0.61/introduction.md
  website/versioned_docs/version-0.62/introduction.md
  website/versioned_docs/version-0.63/introduction.md
  website/versioned_docs/version-0.64/introduction.md
  website/versioned_docs/version-0.65/introduction.md
  website/versioned_docs/version-0.66/introduction.md
  website/versioned_docs/version-0.67/introduction.md
Labels: CLA Signed
