Repository facebook/react-native-website, pull requests merged in 2022-09, with the labels that each got.

#3296 [Fix] JS migration api
  docs/new-architecture-library-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3298 Blog post for 0.70 RN release
  website/blog/2022-09-05-version-070.md
  website/blog/authors.yml
Labels: Partner, p: Facebook, CLA Signed

#3278 feat: Add readOnly prop to TextInput docs
  docs/textinput.md
Labels: CLA Signed

#3279 feat: Add prefersCrossFadeTransitions to AccessibilityInfo docs
  docs/accessibilityinfo.md
Labels: Wait on future Release, CLA Signed

#3280 feat: Add rows prop to TextInput docs
  docs/textinput.md
Labels: Wait on future Release, CLA Signed

#3289 feat: Add inputMode prop to TextInput docs
  docs/textinput.md
Labels: Wait on future Release, CLA Signed

#3284 Fix color reference in flexbox.md
  docs/flexbox.md
Labels: CLA Signed

#3224 [Documentation] adding accessibilityRole grid to documentation
  docs/accessibility.md
  docs/view.md
Labels: CLA Signed

#3286 feat: Add tabIndex prop to View docs
  docs/view.md
Labels: Wait on future Release, CLA Signed

#3292 feat: Add tintColor prop to Image docs
  docs/image.md
Labels: Wait on future Release, CLA Signed

#3299 Added enterKeyHint prop to textInput docs
  docs/textinput.md
Labels: CLA Signed

#3301 Revert renaming native components
  docs/intro-react-native-components.md
  docs/introduction.md
  website/versioned_docs/version-0.70/intro-react-native-components.md
  website/versioned_docs/version-0.70/introduction.md
Labels: Partner, p: Facebook, CLA Signed

#3302 docs: fix package location
  docs/new-architecture-library-ios.md
Labels: CLA Signed

#3304 Update New Architecture instructions to use CMake instead of Android.mk
  docs/new-architecture-app-modules-android.md
  docs/new-architecture-app-renderer-android.md
  docs/new-architecture-library-android.md
  docs/the-new-architecture/pillars-codegen.md
  docs/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.70/new-architecture-app-modules-android.md
  website/versioned_docs/version-0.70/new-architecture-app-renderer-android.md
  website/versioned_docs/version-0.70/new-architecture-library-android.md
Labels: Partner, p: Facebook, CLA Signed

#3309 Follow-up on CMake clarification for 0.70
  website/versioned_docs/version-0.70/the-new-architecture/pillars-codegen.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: Facebook, CLA Signed

#3288 The New Architecture section editorial review
  docs/new-architecture-app-intro.md
  docs/new-architecture-library-android.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-library-ios.md
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/landing-page.md
  docs/the-new-architecture/pillars-codegen.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
  docs/the-new-architecture/pillars.md
  docs/the-new-architecture/use-app-template.md
  docs/the-new-architecture/why.md
Labels: Partner, p: Facebook, CLA Signed

#3268 [New Architecture][iOS][0.71.0] Update the App Migration section
  docs/hermes.md
  docs/new-architecture-app-intro.md
  docs/new-architecture-app-modules-ios.md
  docs/new-architecture-app-renderer-ios.md
  docs/new-architecture-intro.md
  docs/react-18-and-react-native.md
  docs/the-new-architecture/pillars-turbomodule.md
  docs/the-new-architecture/use-app-template.md
  website/sidebars.json
  website/static/_redirects
Labels: Partner, p: Facebook, CLA Signed

#3312 [Fix]Address feedback from #3268
  docs/new-architecture-intro.md
  docs/react-18-and-react-native.md
  website/versioned_docs/version-0.70/new-architecture-app-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3308 Clarify New Architecture Terminology
  docs/new-architecture-app-intro.md
  docs/new-architecture-app-modules-android.md
  docs/new-architecture-app-renderer-android.md
  docs/new-architecture-appendix.md
  docs/new-architecture-intro.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-library-ios.md
  docs/react-18-and-react-native.md
  docs/the-new-architecture/_markdown_native_deprecation.mdx
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/backward-compatibility.md
  docs/the-new-architecture/landing-page.md
  docs/the-new-architecture/pillars-codegen.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
  docs/the-new-architecture/pillars.md
  docs/the-new-architecture/use-app-template.md
  docs/the-new-architecture/why.md
Labels: Partner, p: Facebook, CLA Signed

#3314 Revert "Clarify New Architecture Terminology"
  docs/new-architecture-app-intro.md
  docs/new-architecture-app-modules-android.md
  docs/new-architecture-app-renderer-android.md
  docs/new-architecture-appendix.md
  docs/new-architecture-intro.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-library-ios.md
  docs/react-18-and-react-native.md
  docs/the-new-architecture/_markdown_native_deprecation.mdx
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/backward-compatibility.md
  docs/the-new-architecture/landing-page.md
  docs/the-new-architecture/pillars-codegen.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
  docs/the-new-architecture/pillars.md
  docs/the-new-architecture/use-app-template.md
  docs/the-new-architecture/why.md
Labels: Partner, p: Facebook, CLA Signed

#3316 Clarify New Architecture Terminology - Take 2
  docs/new-architecture-app-intro.md
  docs/new-architecture-app-modules-android.md
  docs/new-architecture-app-renderer-android.md
  docs/new-architecture-appendix.md
  docs/new-architecture-intro.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-library-ios.md
  docs/react-18-and-react-native.md
  docs/the-new-architecture/_markdown_native_deprecation.mdx
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/backward-compatibility.md
  docs/the-new-architecture/landing-page.md
  docs/the-new-architecture/pillars-codegen.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
  docs/the-new-architecture/pillars.md
  docs/the-new-architecture/use-app-template.md
  docs/the-new-architecture/why.md
Labels: Partner, p: Facebook, CLA Signed

#3315 [0.70] Clarify New Architecture Terminology
  website/versioned_docs/version-0.70/new-architecture-app-intro.md
  website/versioned_docs/version-0.70/new-architecture-app-modules-android.md
  website/versioned_docs/version-0.70/new-architecture-app-modules-ios.md
  website/versioned_docs/version-0.70/new-architecture-app-renderer-android.md
  website/versioned_docs/version-0.70/new-architecture-appendix.md
  website/versioned_docs/version-0.70/new-architecture-intro.md
  website/versioned_docs/version-0.70/new-architecture-library-intro.md
  website/versioned_docs/version-0.70/new-architecture-library-ios.md
  website/versioned_docs/version-0.70/react-18-and-react-native.md
  website/versioned_docs/version-0.70/the-new-architecture/_markdown_native_deprecation.mdx
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility.md
  website/versioned_docs/version-0.70/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-codegen.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars.md
  website/versioned_docs/version-0.70/the-new-architecture/use-app-template.md
  website/versioned_docs/version-0.70/the-new-architecture/why.md
Labels: Partner, p: Facebook, CLA Signed

#3313 Remove unnecessary box from Legacy Native Modules/Components
  docs/native-modules-android.md
  docs/native-modules-ios.md
  website/versioned_docs/version-0.70/native-modules-android.md
  website/versioned_docs/version-0.70/native-modules-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3322 Fix title case in testing-overview.md
  docs/testing-overview.md
Labels: CLA Signed

#3321 [FEAT] Add doc to simplify podspecs for Native Modules and Native Components
  docs/new-architecture-library-ios.md
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: Facebook, CLA Signed

#3323 [Fix] Improve Getting started with iOS
  docs/_getting-started-macos-ios.md
  website/versioned_docs/version-0.70/_getting-started-macos-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3319 Fix broken links to Appendix
  docs/new-architecture-library-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3326 fix _getting-started-macos-ios.md info format
  docs/_getting-started-macos-ios.md
  website/versioned_docs/version-0.70/_getting-started-macos-ios.md
Labels: CLA Signed

#3327 minor tweaks to the wording for the versions page
  website/src/pages/versions.js
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3328 showcase: update entries
  website/showcase.json
  website/static/img/showcase/bolt.png
  website/static/img/showcase/dave.png
  website/static/img/showcase/klarna.jpg
  website/static/img/showcase/mattermost.webp
  website/static/img/showcase/openvpn.png
  website/static/img/showcase/playstation.png
  website/static/img/showcase/puma.png
  website/static/img/showcase/wordpress.png
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3330 fix incorrect link to re-enable prod deploy
  website/versioned_docs/version-0.68/build-speed.md
Labels: Partner, p: expo, CLA Signed

#3177 Modify the top navbar to be less full
  website/docusaurus.config.js
  website/src/css/customTheme.scss
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3333 Update docs with AGP 7.3.x setup
  docs/new-architecture-app-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3306 feat: Update colors docs regarding expanded support for CSS Colors
  docs/colors.md
Labels: CLA Signed

#3334 [Fix]Improve wording for iOS getting started
  docs/_getting-started-macos-ios.md
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
Labels: Partner, p: Facebook, CLA Signed

#3285 feat: Add id prop to Text, TouchableWithoutFeedback and View docs
  docs/text.md
  docs/touchablewithoutfeedback.md
  docs/view.md
Labels: CLA Signed

#3237 Updated button.md to reference Pressable instead of Touchable Opacity…
  website/versioned_docs/version-0.69/button.md
Labels: CLA Signed

#3332 chore: clean up new arch docs
  docs/new-architecture-library-intro.md
  docs/the-new-architecture/pillars.md
  docs/the-new-architecture/use-app-template.md
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3310 Added Documentation for crossOrigin, referrerPolicy, width, height, src and srcSet props to Image
  docs/image.md
Labels: CLA Signed

#3336 fix: remove isFabricEnabled check from docs
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
Labels: CLA Signed

#3320 added documnetatuin for `aria-modal` prop
  docs/accessibility.md
  docs/view.md
Labels: CLA Signed

#3311 added documentation for `userSelect` prop to Text docs
  docs/text.md
Labels: CLA Signed

#3293 New: Sourcemap Page
  docs/profile-hermes.md
  docs/sourcemaps.md
  website/sidebars.json
Labels: CLA Signed

#3318 added documentation for `aria-valuemax` `aria-valuemin` `aria-valuenow` `aria-valuetext`
  docs/accessibility.md
  docs/touchablewithoutfeedback.md
  docs/view.md
Labels: CLA Signed

#3343 Add ability to pass ItemSeparatorComponent as React Element
  docs/flatlist.md
  docs/sectionlist.md
  docs/virtualizedlist.md
  website/versioned_docs/version-0.70/flatlist.md
  website/versioned_docs/version-0.70/sectionlist.md
  website/versioned_docs/version-0.70/virtualizedlist.md
Labels: CLA Signed

#3344 clean warning
  docs/layout-props.md
Labels: CLA Signed

#3345 fix(native-modules-android.md): rename createCalendarEventCallback
  docs/native-modules-android.md
Labels: CLA Signed

#3340 Update showcase link for Artsy
  website/showcase.json
Labels: CLA Signed

#3347 add NFL to the showcase
  website/showcase.json
  website/static/img/showcase/nfl.webp
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3348 Checks for the documentation
  docs/new-architecture-intro.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-library-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3352 Apply updated copyright to `*.js` files
  .alexrc.js
  LICENSE
  plugins/remark-snackplayer/src/index.js
  plugins/remark-snackplayer/tests/index.js
  sync-api-docs/extractDocsFromRN.js
  sync-api-docs/generateMarkdown.js
  sync-api-docs/magic.js
  sync-api-docs/methodFormatter.js
  sync-api-docs/preprocessGeneratedApiDocs.js
  sync-api-docs/propFormatter.js
  sync-api-docs/sync-api-docs.js
  sync-api-docs/utils.js
  website/core/DocsRating.js
  website/core/PrismTheme.js
  website/core/TableRowWithCodeBlock.js
  website/core/TabsConstants.js
  website/image-check.js
  website/snackPlayerInitializer.js
  website/src/pages/animations/_dissectionAnimation.js
  website/src/pages/animations/_headerAnimation.js
  website/src/pages/index.js
  website/src/pages/showcase.js
  website/src/pages/versions.js
  website/src/theme/BlogSidebar/Desktop/index.js
  website/src/theme/BlogSidebar/Mobile/index.js
  website/src/theme/DocItemFooter/index.js
  website/src/theme/Icon/ExternalLink/index.js
  website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js
Labels: Partner, p: Facebook, CLA Signed

#3338 rework the community section of the website
  .github/ISSUE_TEMPLATE/config.yml
  docs/more-resources.md
  website/community/communities.md
  website/community/overview.md
  website/community/staying-updated.md
  website/community/support.md
  website/contributing/how-to-file-an-issue.md
  website/docusaurus.config.js
  website/sidebarsCommunity.json
  website/src/css/customTheme.scss
  website/src/pages/help.md
  website/static/_redirects
  website/static/manifest.json
  website/versioned_docs/version-0.62/more-resources.md
  website/versioned_docs/version-0.63/more-resources.md
  website/versioned_docs/version-0.64/more-resources.md
  website/versioned_docs/version-0.65/more-resources.md
  website/versioned_docs/version-0.66/more-resources.md
  website/versioned_docs/version-0.67/more-resources.md
  website/versioned_docs/version-0.68/more-resources.md
  website/versioned_docs/version-0.69/more-resources.md
  website/versioned_docs/version-0.70/more-resources.md
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3354 Update to Contributor Covenant
  CODE_OF_CONDUCT.md
Labels: Partner, p: Facebook, CLA Signed

#3353 Fix more copyright header issues
  LICENSE
  plugins/remark-snackplayer/src/index.js
  plugins/remark-snackplayer/tests/index.js
  sync-api-docs/extractDocsFromRN.js
  sync-api-docs/generateMarkdown.js
  sync-api-docs/magic.js
  sync-api-docs/methodFormatter.js
  sync-api-docs/preprocessGeneratedApiDocs.js
  sync-api-docs/propFormatter.js
  sync-api-docs/sync-api-docs.js
  sync-api-docs/utils.js
  website/core/DocsRating.js
  website/core/PrismTheme.js
  website/core/TableRowWithCodeBlock.js
  website/core/TabsConstants.js
  website/image-check.js
  website/snackPlayerInitializer.js
  website/src/css/_shared.scss
  website/src/css/customTheme.scss
  website/src/css/index.scss
  website/src/css/showcase.scss
  website/src/css/versions.scss
  website/src/pages/animations/_dissectionAnimation.js
  website/src/pages/animations/_headerAnimation.js
  website/src/pages/index.js
  website/src/pages/showcase.js
  website/src/pages/versions.js
  website/src/theme/BlogSidebar/Desktop/index.d.ts
  website/src/theme/BlogSidebar/Desktop/index.js
  website/src/theme/BlogSidebar/Desktop/styles.module.css
  website/src/theme/BlogSidebar/Mobile/index.d.ts
  website/src/theme/BlogSidebar/Mobile/index.js
  website/src/theme/BlogSidebar/Mobile/styles.module.css
  website/src/theme/DocItemFooter/index.js
  website/src/theme/Icon/ExternalLink/index.js
  website/src/theme/Icon/ExternalLink/styles.module.css
Labels: Partner, p: Facebook, CLA Signed
