Repository facebook/react-native-website, pull requests merged in 2022-10, with the labels that each got.

#3337 fix: remove isTurboModuleEnabled check from docs
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
Labels: CLA Signed

#3355 Update pillars-turbomodule.md
  docs/the-new-architecture/pillars-turbomodule.md
Labels: CLA Signed

#3349 Showcase: add Wix's apps section.
  website/showcase.json
  website/src/pages/showcase.js
  website/static/img/showcase/dine.webp
  website/static/img/showcase/fit.webp
  website/static/img/showcase/owner.webp
  website/static/img/showcase/wix_logo_darkbg.svg
  website/static/img/showcase/wix_logo_lightbg.svg
Labels: CLA Signed

#3360 Finalize the Kotlinization
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: Facebook, CLA Signed

#3365 fix: duplicate header
  website/community/communities.md
Labels: CLA Signed

#3369 Missing header in `docusaurus.config.js`
  website/docusaurus.config.js
Labels: Partner, p: Facebook, CLA Signed

#3370 Fix headers on *.ts files
  website/src/theme/BlogSidebar/Desktop/index.d.ts
  website/src/theme/BlogSidebar/Mobile/index.d.ts
Labels: Partner, p: Facebook, CLA Signed

#3367 Fix Android version label for older version documents
  website/versioned_docs/version-0.65/_getting-started-linux-android.md
  website/versioned_docs/version-0.65/_getting-started-macos-android.md
  website/versioned_docs/version-0.65/_getting-started-windows-android.md
  website/versioned_docs/version-0.66/_getting-started-linux-android.md
  website/versioned_docs/version-0.66/_getting-started-macos-android.md
  website/versioned_docs/version-0.66/_getting-started-windows-android.md
  website/versioned_docs/version-0.67/_getting-started-windows-android.md
Labels: CLA Signed

#3363 feat: Update aspectRatio supported types docs
  docs/layout-props.md
Labels: CLA Signed

#3357 Update scrollview.md
  docs/scrollview.md
Labels: CLA Signed

#3358 Reorder zsh because newer macOS uses zsh
  docs/_getting-started-macos-android.md
Labels: CLA Signed

#3346 docs: update running on simulator iOS
  docs/running-on-simulator-ios.md
Labels: CLA Signed

#3371 fix: add back missing docs vote component
  website/src/theme/DocItem/Footer/index.js
  website/src/theme/DocItem/Footer/styles.module.css
  website/src/theme/DocItemFooter/index.js
Labels: Partner, p: expo, CLA Signed

#3364 [Fix] Improve TM explanation
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: Facebook, CLA Signed

#3356 New Architecture - Remove the extra steps required to copy .so files
  docs/new-architecture-app-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3368 chore(release): Update release testing section for new E2E testing script
  website/contributing/how-to-contribute-code.md
  website/contributing/how-to-run-and-write-tests.md
  website/contributing/release-testing.md
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3377 Fixed typo in headless-js-android.md
  docs/headless-js-android.md
  website/versioned_docs/version-0.70/headless-js-android.md
Labels: CLA Signed

#3374 Fix typo in New Architecture Intro
  docs/new-architecture-app-intro.md
Labels: CLA Signed

#3376 Add updated instructions on using Hermes
  docs/hermes.md
Labels: Partner, p: Facebook, CLA Signed

#3380 Upstream hermes.md to version 0.70 of the docs
  website/versioned_docs/version-0.70/hermes.md
Labels: Partner, p: Facebook, CLA Signed

#3387 fix: missing paren in publishing
  website/contributing/how-to-build-from-source.md
Labels: CLA Signed

#3342 Recommend to use `es2019` and use community driven TS config `@tsconfig/react-native`
  docs/typescript.md
  website/versioned_docs/version-0.69/typescript.md
  website/versioned_docs/version-0.70/typescript.md
Labels: CLA Signed
