Repository facebook/react-native-website, pull requests merged in 2022-07, with the labels that each got.

#3189 Update Android SDK version to 31
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-windows-android.md
  website/versioned_docs/version-0.68/_getting-started-linux-android.md
  website/versioned_docs/version-0.68/_getting-started-macos-android.md
  website/versioned_docs/version-0.68/_getting-started-windows-android.md
  website/versioned_docs/version-0.69/_getting-started-linux-android.md
  website/versioned_docs/version-0.69/_getting-started-macos-android.md
  website/versioned_docs/version-0.69/_getting-started-windows-android.md
Labels: CLA Signed

#3190 Use monospace for method name on docs/easing
  docs/easing.md
Labels: CLA Signed

#3191 add communication-android link to Android Guides
  website/sidebars.json
  website/versioned_sidebars/version-0.65-sidebars.json
  website/versioned_sidebars/version-0.66-sidebars.json
  website/versioned_sidebars/version-0.67-sidebars.json
  website/versioned_sidebars/version-0.68-sidebars.json
  website/versioned_sidebars/version-0.69-sidebars.json
Labels: CLA Signed

#3193 Update snippet in profile-hermes to be Groovy rather than Java
  docs/profile-hermes.md
Labels: Partner, p: Facebook, CLA Signed

#3039 [Guide - The New Architecture] TurboModules as Native Modules
  docs/the-new-architecture/_markdown_beta_ts_support.mdx
  docs/the-new-architecture/backward-compatibility-turbomodules.md
Labels: Partner, p: Facebook, CLA Signed

#3040 [Guide - The New Architecture] Fabric Components as Native Components
  docs/the-new-architecture/backward-compatibility-fabric-components.md
Labels: Partner, p: Facebook, CLA Signed

#3194 Add kotlin code sample to new-architecture-library-android.md
  docs/new-architecture-library-android.md
Labels: CLA Signed

#3203 Add a few Microsoft apps to the showcase
  website/showcase.json
  website/static/img/showcase/officemobile.png
  website/static/img/showcase/outlookmobile.png
  website/static/img/showcase/teamsmobile.png
  website/static/img/showcase/xboxgamepass.png
Labels: Partner, Contributor, p: microsoft, CLA Signed, Showcase

#3210 Correct minor mistake in native-components-android.md
  docs/native-components-android.md
Labels: CLA Signed

#3208 Update fast-refresh.md
  docs/fast-refresh.md
Labels: CLA Signed

#3199 Fixed Artsy logo and infoLink of oculus in webiste/showcase
  website/showcase.json
Labels: CLA Signed, Showcase

#3206 Wrap "Android SDK Build-Tools" with backticks
  docs/_getting-started-windows-android.md
Labels: CLA Signed

#3202 Update keyboardavoidingview.md
  docs/keyboardavoidingview.md
Labels: CLA Signed

#3209 Update debugging.md
  docs/debugging.md
Labels: CLA Signed

#3216 Update iOS data in Hermes default blog post
  website/static/blog/assets/hermes-default-ios-data.png
Labels: Partner, p: Facebook, CLA Signed

#3221 Update the contributing section docs
  website/contributing/contributing-overview.md
  website/contributing/how-to-build-from-source.md
  website/contributing/how-to-contribute-code.md
  website/contributing/how-to-run-and-write-tests.md
  website/contributing/release-branch-cut-and-rc0.md
  website/contributing/release-candidate-patch.md
  website/contributing/release-dependencies.md
  website/contributing/release-faq.md
  website/contributing/release-stable-minor.md
  website/contributing/release-stable-patch.md
  website/contributing/release-testing.md
  website/contributing/updating-upgrade-helper.md
  website/sidebarsContributing.json
  website/static/_redirects
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3228 docs: add build tools to Table of Contents
  website/architecture/architecture-overview.md
Labels: CLA Signed

#3223 Update build-speed.md page in docs
  docs/build-speed.md
Labels: CLA Signed

#3230 docs: add two sections to the New Architecture
  docs/new-architecture-intro.md
Labels: CLA Signed

#3214 Note on connecting to React Native simulator.
  docs/debugging.md
Labels: CLA Signed

#3222 Fix a couple of problems on the release runbook
  website/contributing/release-branch-cut-and-rc0.md
Labels: Partner, p: Facebook, CLA Signed

#3231 Improving UX: replace videos and links with SnackPlayers, update examples
  docs/improvingux.md
  website/versioned_docs/version-0.69/improvingux.md
Labels: Partner, p: expo, CLA Signed

#3233 Fix extra whitespace on debugging.md
  docs/debugging.md
Labels: Partner, p: Facebook, CLA Signed
