Repository facebook/react-native-website, pull requests merged in 2023-04, with the labels that each got.

#3664 fix: imageUrl in imageBackGround page
  docs/imagebackground.md
Labels: CLA Signed

#3668 Update More Resources React's Documentation link
  docs/more-resources.md
Labels: CLA Signed

#3678 Naming inconsistency causing build failure in Android Java file.
  docs/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
Labels: CLA Signed

#3682 Update platform label for `maintainVisibleContentPosition`
  docs/scrollview.md
Labels: Partner, p: Facebook, CLA Signed

#3686 s/arams/params/
  docs/virtualizedlist.md
Labels: CLA Signed

#3680 feat: redirect current version urls
  scripts/update-redirect/index.js
  scripts/update-redirect/package.json
  website/package.json
  website/static/_redirects
Labels: Partner, p: Facebook, CLA Signed

#3694 Updated typo in flexGrow functionality
  docs/flexbox.md
Labels: CLA Signed

#3691 Update Kotlin code snippet for consistency with Java
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.71/the-new-architecture/backward-compatibility-turbomodules.md
Labels: CLA Signed

#3692 [docs] Update in-app dev menu instructions, consistently name as "Dev Menu"
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-windows-android.md
  docs/animations.md
  docs/building-for-tv.md
  docs/debugging.md
  docs/devsettings.md
  docs/fast-refresh.md
  docs/hermes.md
  docs/performance.md
  docs/profile-hermes.md
  docs/publishing-to-app-store.md
  docs/running-on-device.md
  website/architecture/architecture-glossary.md
  website/static/docs/assets/DevMenu.png
Labels: Partner, p: Facebook, CLA Signed

#3695 Adding 'Never gets stale' to exception labels for stalebot
  .github/workflows/stale-bot.yml
Labels: Partner, p: Facebook, CLA Signed

#3696 Wrap scheduling alternatives in `code`
  docs/interactionmanager.md
Labels: CLA Signed

#3698 Replace deprecated `--variant` and `--configuration` with `--mode`
  docs/hermes.md
  docs/publishing-to-app-store.md
  docs/running-on-device.md
  website/versioned_docs/version-0.71/hermes.md
  website/versioned_docs/version-0.71/publishing-to-app-store.md
  website/versioned_docs/version-0.71/running-on-device.md
Labels: CLA Signed

#3699 Remove reference to `generatedComponentApiDocs.js`
  sync-api-docs/magic.js
Labels: Partner, p: microsoft, CLA Signed

#3688 chore: replace manual command with CLI command
  docs/signed-apk-android.md
Labels: CLA Signed
