Repository facebook/react-native-website, pull requests merged in 2023-10, with the labels that each got.

#3864 adjust SnackPlayer height and presentation
  plugins/remark-snackplayer/package.json
  plugins/remark-snackplayer/src/index.js
  plugins/remark-snackplayer/tests/index.js
  plugins/remark-snackplayer/tests/output/output1.html
  plugins/remark-snackplayer/tests/output/output2.html
  website/modules/snackPlayerInitializer.js
  website/src/css/customTheme.scss
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#3865 update Docusaurus to beta release, versions page tweaks
  website/package.json
  website/src/css/versions.scss
  website/src/pages/versions.js
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#3876 [docs] Reorganise docs sidebar
  website/sidebars.json
  website/versioned_sidebars/version-0.70-sidebars.json
  website/versioned_sidebars/version-0.71-sidebars.json
  website/versioned_sidebars/version-0.72-sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#3881 fix: default value of textBreakStrategy prop of TextInput component
  docs/textinput.md
  website/versioned_docs/version-0.70/textinput.md
  website/versioned_docs/version-0.71/textinput.md
  website/versioned_docs/version-0.72/textinput.md
Labels: CLA Signed

#3886 Update network.md
  docs/network.md
Labels: CLA Signed

#3878 Improve instructions for enabling app transport security
  docs/publishing-to-app-store.md
  website/static/docs/assets/XCodeEnableATS.png
Labels: CLA Signed

#3506 Add section on updating linting tools
  README.md
Labels: Partner, p: Facebook, CLA Signed

#3748 Updating docs to reflect bumping node from 16 to 18
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
Labels: Wait on future Release, Partner, p: Facebook, CLA Signed

#3889 [docs] Create "Debugging Release Builds" guide, consolidate existing pages
  docs/debugging-release-builds.md
  docs/profile-hermes.md
  docs/sourcemaps.md
  docs/symbolication.md
  website/sidebars.json
  website/static/_redirects
Labels: Partner, p: Facebook, CLA Signed

#3898 [docs] Overhaul "Debugging Basics" guide
  docs/debugging.md
  docs/react-devtools.md
  website/core/TabsConstants.js
  website/static/docs/assets/debugging-debugger-welcome.jpg
  website/static/docs/assets/debugging-dev-menu.jpg
  website/static/docs/assets/debugging-flipper-console.jpg
  website/static/docs/assets/debugging-hermes-debugger-instructions.jpg
  website/static/docs/assets/debugging-logbox.jpg
  website/static/docs/assets/debugging-performance-monitor.jpg
  website/static/docs/assets/debugging-react-devtools-blank.jpg
Labels: Partner, p: Facebook, CLA Signed

#3899 Fix a backlink on hermes-as-the-default
  website/blog/2022-07-08-hermes-as-the-default.md
Labels: CLA Signed

#3900 [docs] Add Other Debugging Methods guide
  docs/other-debugging-methods.md
  website/sidebars.json
  website/static/docs/assets/debugging-chrome-remote-debugger.jpg
  website/static/docs/assets/debugging-safari-developer-tools.jpg
Labels: Partner, p: Facebook, CLA Signed

#3895 Recover debugging native code section
  docs/native-debugging.md
  website/versioned_docs/version-0.72/native-debugging.md
Labels: CLA Signed

#3901 [docs] Refresh React DevTools visuals, condense formatting
  docs/react-devtools.md
  website/static/docs/assets/debugging-element-inspector-react-devtools.gif
  website/static/docs/assets/debugging-element-inspector.gif
  website/static/docs/assets/debugging-react-devtools-connection.gif
  website/static/docs/assets/debugging-react-devtools-detail.jpg
Labels: Partner, p: Facebook, CLA Signed
