Repository facebook/react-native-website, pull requests merged in 2023-08, with the labels that each got.

#3812 Update website to use JDK 17
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-windows-android.md
Labels: Partner, p: Facebook, CLA Signed

#3814 update: use new react.dev docs link
  docs/handling-text-input.md
Labels: CLA Signed

#3809 Update guidance on repo build scripts
  website/contributing/how-to-contribute-code.md
  website/contributing/how-to-open-a-pull-request.md
Labels: Partner, p: Facebook, CLA Signed

#3766 Add second package manager in "Upgrade dependencies" section.
  docs/upgrading.md
Labels: CLA Signed

#3795 Update testing instructions for the script that downloads artifacts from CircleCI
  website/contributing/release-testing.md
Labels: Partner, p: Facebook, CLA Signed

#3816 Update Expo Go guide link
  docs/running-on-device.md
  website/versioned_docs/version-0.69/running-on-device.md
  website/versioned_docs/version-0.70/running-on-device.md
  website/versioned_docs/version-0.71/running-on-device.md
  website/versioned_docs/version-0.72/running-on-device.md
Labels: CLA Signed

#3820 [website] add VerticalTable, improve new arch appendix
  docs/new-architecture-appendix.md
  website/core/TableRowWithCodeBlock.js
  website/core/VerticalTable.js
  website/src/css/customTheme.scss
  website/versioned_docs/version-0.71/new-architecture-appendix.md
  website/versioned_docs/version-0.72/new-architecture-appendix.md
Labels: Partner, p: expo, CLA Signed

#3815 chores(releases): rename script and add info note
  website/contributing/_markdown-older-bump-script.mdx
  website/contributing/release-branch-cut-and-rc0.md
  website/contributing/release-candidate-patch.md
  website/contributing/release-stable-minor.md
  website/contributing/release-stable-patch.md
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3824 Fix native module type conversion tables for iOS and Android
  docs/native-modules-android.md
  docs/native-modules-ios.md
  website/versioned_docs/version-0.70/native-modules-android.md
  website/versioned_docs/version-0.70/native-modules-ios.md
  website/versioned_docs/version-0.71/native-modules-android.md
  website/versioned_docs/version-0.71/native-modules-ios.md
  website/versioned_docs/version-0.72/native-modules-android.md
  website/versioned_docs/version-0.72/native-modules-ios.md
Labels: CLA Signed

#3827 Update case-police, fix case of webpack + CocoaPods
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  docs/navigation.md
  docs/platform-specific-code.md
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
  package.json
  website/blog/2016-03-24-introducing-hot-reloading.md
  website/blog/2017-06-21-react-native-monthly-1.md
  website/blog/2017-11-06-react-native-monthly-5.md
  website/versioned_docs/version-0.70/platform-specific-code.md
  website/versioned_docs/version-0.71/platform-specific-code.md
  website/versioned_docs/version-0.72/navigation.md
  website/versioned_docs/version-0.72/platform-specific-code.md
  website/versioned_docs/version-0.72/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.72/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.72/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.72/the-new-architecture/pillars-turbomodule.md
  yarn.lock
Labels: CLA Signed

#3822 correct broken links, update Case Police in package.json to match lock
  docs/_getting-started-linux-android.md
  docs/communication-ios.md
  docs/custom-webview-android.md
  docs/custom-webview-ios.md
  docs/getting-started.md
  docs/javascript-environment.md
  website/blog/2021-10-26-toward-hermes-being-the-default.md
  website/package.json
  website/versioned_docs/version-0.70/_getting-started-linux-android.md
  website/versioned_docs/version-0.70/custom-webview-android.md
  website/versioned_docs/version-0.70/custom-webview-ios.md
  website/versioned_docs/version-0.70/getting-started.md
  website/versioned_docs/version-0.70/javascript-environment.md
  website/versioned_docs/version-0.71/_getting-started-linux-android.md
  website/versioned_docs/version-0.71/custom-webview-android.md
  website/versioned_docs/version-0.71/custom-webview-ios.md
  website/versioned_docs/version-0.71/getting-started.md
  website/versioned_docs/version-0.71/javascript-environment.md
  website/versioned_docs/version-0.72/_getting-started-linux-android.md
  website/versioned_docs/version-0.72/communication-ios.md
  website/versioned_docs/version-0.72/custom-webview-android.md
  website/versioned_docs/version-0.72/custom-webview-ios.md
  website/versioned_docs/version-0.72/getting-started.md
  website/versioned_docs/version-0.72/javascript-environment.md
Labels: Partner, p: expo, CLA Signed
