Repository facebook/react-native-website, pull requests merged in 2023-07, with the labels that each got.

#3761 SECURITY: FIX Use `https` links over `http` → Sitewide Change
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_integration-with-existing-apps-objc.md
  docs/_integration-with-existing-apps-swift.md
  docs/animated.md
  docs/asyncstorage.md
  docs/communication-android.md
  docs/communication-ios.md
  docs/debugging.md
  docs/easing.md
  docs/headless-js-android.md
  docs/image.md
  docs/javascript-environment.md
  docs/linking.md
  docs/network.md
  docs/performance.md
  docs/running-on-device.md
  docs/testing-overview.md
  docs/textinput.md
  docs/view.md
  website/blog/2016-03-24-introducing-hot-reloading.md
  website/blog/2016-04-13-react-native-a-year-in-review.md
  website/blog/2016-08-12-react-native-meetup-san-francisco.md
  website/blog/2016-08-19-right-to-left-support-for-react-native-apps.md
  website/blog/2016-12-05-easier-upgrades.md
  website/blog/2017-06-21-react-native-monthly-1.md
  website/blog/2017-07-28-react-native-monthly-2.md
  website/blog/2017-09-21-react-native-monthly-4.md
  website/blog/2018-01-09-react-native-monthly-6.md
  website/blog/2018-01-18-implementing-twitters-app-loading-animation-in-react-native.md
  website/blog/2018-03-05-AWS-app-sync.md
  website/blog/2018-03-22-building-input-accessory-view-for-react-native.md
  website/blog/2018-05-07-using-typescript-with-react-native.md
  website/blog/2019-06-12-react-native-open-source-update.md
  website/blog/2021-04-08-GAAD-March-Accessibility-Issue-Update.md
  website/blog/2021-08-26-many-platform-vision.md
  website/blog/2023-01-12-version-071.md
  website/community/communities.md
  website/community/support.md
  website/contributing/contributing-overview.md
  website/contributing/triaging-github-issues.md
  website/showcase.json
Labels: CLA Signed

#3673 [docs] Update/simplify info around Metro for env setup
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
Labels: Partner, p: Facebook, CLA Signed

#3772 [docs] Add Metro configuration guide, update Metro config references
  docs/metro.md
  docs/ram-bundles-inline-requires.md
  website/sidebars.json
  website/versioned_docs/version-0.72/metro.md
  website/versioned_docs/version-0.72/ram-bundles-inline-requires.md
  website/versioned_sidebars/version-0.72-sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#3782 [docs] Remove static config note in Metro guide, adjust formatting
  docs/metro.md
  website/versioned_docs/version-0.72/metro.md
Labels: Partner, p: Facebook, CLA Signed

#3783 Improving Grammar and Clarity.md
  docs/performance.md
Labels: CLA Signed

#3785 Fix docs for onResponderGrant
  docs/text.md
  docs/view.md
  website/versioned_docs/version-0.65/text.md
  website/versioned_docs/version-0.65/view.md
  website/versioned_docs/version-0.66/text.md
  website/versioned_docs/version-0.66/view.md
  website/versioned_docs/version-0.67/text.md
  website/versioned_docs/version-0.67/view.md
  website/versioned_docs/version-0.68/text.md
  website/versioned_docs/version-0.68/view.md
  website/versioned_docs/version-0.69/text.md
  website/versioned_docs/version-0.69/view.md
  website/versioned_docs/version-0.70/text.md
  website/versioned_docs/version-0.70/view.md
  website/versioned_docs/version-0.71/text.md
  website/versioned_docs/version-0.71/view.md
  website/versioned_docs/version-0.72/text.md
  website/versioned_docs/version-0.72/view.md
Labels: Partner, p: Facebook, CLA Signed

#3786 react-native-gradle-plugin renamed to @react-native/gradle-plugin
  docs/_integration-with-existing-apps-java.md
  docs/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.72/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.72/_integration-with-existing-apps-kotlin.md
Labels: CLA Signed

#3659 Update how-to-build-from-source for 0.72+
  website/contributing/how-to-build-from-source.md
Labels: Partner, p: Facebook, CLA Signed

#3787 Clarify documentation for turbomodules
  docs/the-new-architecture/pillars-turbomodule.md
Labels: CLA Signed

#3700 Update FlatList Optimization Guide for FCs
  docs/optimizing-flatlist-configuration.md
Labels: CLA Signed

#3788 [docs] Add guidance on repo build scripts
  website/contributing/how-to-contribute-code.md
  website/contributing/how-to-open-a-pull-request.md
Labels: :clock1: Waiting on PR, Partner, p: Facebook, CLA Signed

#3790 [docs] add Chain React 2023 playlist link on staying-updated
  website/community/staying-updated.md
Labels: CLA Signed

#3775 docs: iOS backwards compatibility update
  docs/the-new-architecture/backward-compatibility-fabric-components.md
Labels: CLA Signed

#3800 [website] swizzle DocVersionBanner, tweak wording
  website/src/theme/DocVersionBanner/index.js
Labels: Partner, p: expo, CLA Signed

#3805 tweak: improve wordiness on docs about bumping monorepo packages
  website/contributing/release-updating-packages.md
Labels: Partner, Contributor, p: microsoft, CLA Signed

#3806 Fix typo in architecture-glossary.md
  website/architecture/architecture-glossary.md
Labels: CLA Signed

#3808 docs: change js to tsx
  docs/native-components-ios.md
Labels: CLA Signed
