Repository facebook/react-native-website, pull requests merged in 2023-06, with the labels that each got.

#3747 Update _getting-started-macos-ios.md
  docs/_getting-started-macos-ios.md
Labels: CLA Signed

#3754 Update react-native-gradle-plugin.md docs
  docs/react-native-gradle-plugin.md
Labels: CLA Signed

#3742 Add step for bumping packages when doing RC patch
  website/contributing/release-candidate-patch.md
  website/contributing/release-stable-patch.md
Labels: Partner, CLA Signed, p: shopify

#3755 Refactor: Switch to `let` & `const` from `var` in `JS`, `JSX`, `TS` & `TSX` code-blocks
  docs/_integration-with-existing-apps-java.md
  docs/_integration-with-existing-apps-kotlin.md
  docs/building-for-tv.md
  docs/clipboard.md
  docs/images.md
  docs/interactionmanager.md
  docs/native-components-ios.md
  docs/network.md
  website/blog/2016-03-24-introducing-hot-reloading.md
Labels: CLA Signed

#3759 SECURITY: FIX unintended Email protocol resolution
  docs/_getting-started-macos-ios.md
  docs/_integration-with-existing-apps-java.md
  docs/_integration-with-existing-apps-kotlin.md
  docs/_integration-with-existing-apps-objc.md
  docs/_integration-with-existing-apps-swift.md
Labels: CLA Signed

#3767 Clarify Release Crew role timespan and responsibilities
  website/contributing/release-roles-responsibilites.md
Labels: CLA Signed

#3760 Touchups: Use `<kbd>` for specifying Keyboard Keys and Shortcuts
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  docs/_integration-with-existing-apps-java.md
  docs/_integration-with-existing-apps-kotlin.md
  docs/publishing-to-app-store.md
  docs/running-on-device.md
Labels: CLA Signed

#3765 [RN][New Architecture] Update Playbook with 0.72 changes
  docs/new-architecture-app-intro.md
  docs/new-architecture-appendix.md
  docs/new-architecture-library-intro.md
  docs/new-architecture-troubleshooting.md
Labels: Partner, p: Facebook, CLA Signed

#3705 [blog] Add Package Exports blog post
  website/blog/2023-06-21-package-exports-support.md
  website/blog/authors.yml
  website/static/blog/assets/package-exports-rollout.png
Labels: :clock1: Waiting on PR, Partner, p: Facebook, CLA Signed

#3725 Add 0.72 blog post
  website/blog/2023-06-21-0.72-metro-package-exports-symlinks.md
  website/blog/2023-06-21-package-exports-support.md
  website/blog/authors.yml
  website/static/blog/assets/package-exports-rollout.png
Labels: Partner, p: Facebook, CLA Signed

#3702 Update Debugging docs to no longer recommend Remote debugging
  docs/debugging.md
  docs/hermes.md
Labels: :clock1: Waiting on PR, Wait on future Release, Partner, p: expo, CLA Signed

#3776 Upgrade got dependency
  docs/_getting-started-macos-ios.md
  plugins/remark-lint-no-dead-urls/package.json
  website/package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed
