Repository facebook/react-native-website, pull requests merged in 2023-02, with the labels that each got.

#3547 add-link-to-android-disambiguation-dialog-for-duplicate-url-schemes-explanation
  docs/security.md
  website/versioned_docs/version-0.62/security.md
  website/versioned_docs/version-0.63/security.md
  website/versioned_docs/version-0.64/security.md
  website/versioned_docs/version-0.65/security.md
  website/versioned_docs/version-0.66/security.md
  website/versioned_docs/version-0.67/security.md
  website/versioned_docs/version-0.68/security.md
  website/versioned_docs/version-0.69/security.md
  website/versioned_docs/version-0.70/security.md
  website/versioned_docs/version-0.71/security.md
Labels: CLA Signed

#3537 Add `dynamicTypeRamp` documentation
  docs/text.md
Labels: CLA Signed

#3552 change the use of incorrect word
  docs/native-modules-android.md
  website/versioned_docs/version-0.68/native-modules-android.md
  website/versioned_docs/version-0.69/native-modules-android.md
  website/versioned_docs/version-0.70/native-modules-android.md
  website/versioned_docs/version-0.71/native-modules-android.md
Labels: CLA Signed

#3553 rename type and method from GreetingsProps to GreetingProps
  docs/props.md
  website/versioned_docs/version-0.71/props.md
Labels: CLA Signed

#3557 new syntax in native modules android
  docs/native-modules-android.md
Labels: CLA Signed

#3533 Add description about onHoverIn/onHoverOut on Pressable
  docs/pressable.md
  website/versioned_docs/version-0.68/pressable.md
  website/versioned_docs/version-0.69/pressable.md
  website/versioned_docs/version-0.70/pressable.md
  website/versioned_docs/version-0.71/pressable.md
Labels: CLA Signed

#3558 Bump @sideway/formula to address CVE-2023-25166
  package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#3559 Update Migration to the New Architecture section
  docs/new-architecture-app-intro.md
  website/versioned_docs/version-0.71/new-architecture-app-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3561 fix the redirection to open pull request page
  website/contributing/how-to-contribute-code.md
Labels: CLA Signed

#3562 Update hermes.md
  docs/hermes.md
  website/versioned_docs/version-0.71/hermes.md
Labels: CLA Signed

#3564 add onPressIn and onPressOut props on text page
  docs/text.md
  website/versioned_docs/version-0.66/text.md
  website/versioned_docs/version-0.67/text.md
  website/versioned_docs/version-0.68/text.md
  website/versioned_docs/version-0.69/text.md
  website/versioned_docs/version-0.70/text.md
  website/versioned_docs/version-0.71/text.md
Labels: CLA Signed

#3566 Update _getting-started-macos-ios.md
  docs/_getting-started-macos-ios.md
Labels: CLA Signed

#3567 typo in new arch intro docs
  docs/new-architecture-app-intro.md
  website/versioned_docs/version-0.71/new-architecture-app-intro.md
Labels: CLA Signed

#3568 docs: update Codegen types description
  docs/new-architecture-library-intro.md
  website/versioned_docs/version-0.68/new-architecture-library-intro.md
  website/versioned_docs/version-0.69/new-architecture-library-intro.md
  website/versioned_docs/version-0.70/new-architecture-library-intro.md
  website/versioned_docs/version-0.71/new-architecture-library-intro.md
Labels: CLA Signed

#3571 Correct spelling: exisiting -> existing
  docs/_integration-with-existing-apps-java.md
  docs/_integration-with-existing-apps-objc.md
  docs/_integration-with-existing-apps-swift.md
  docs/integration-with-existing-apps.md
  website/versioned_docs/version-0.60/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.60/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.60/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.60/integration-with-existing-apps.md
  website/versioned_docs/version-0.61/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.61/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.61/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.61/integration-with-existing-apps.md
  website/versioned_docs/version-0.62/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.62/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.62/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.62/integration-with-existing-apps.md
  website/versioned_docs/version-0.63/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.63/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.63/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.63/integration-with-existing-apps.md
  website/versioned_docs/version-0.64/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.64/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.64/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.64/integration-with-existing-apps.md
  website/versioned_docs/version-0.65/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.65/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.65/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.65/integration-with-existing-apps.md
  website/versioned_docs/version-0.66/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.66/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.66/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.66/integration-with-existing-apps.md
  website/versioned_docs/version-0.67/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.67/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.67/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.67/integration-with-existing-apps.md
  website/versioned_docs/version-0.68/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.68/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.68/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.68/integration-with-existing-apps.md
  website/versioned_docs/version-0.69/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.69/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.69/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.69/integration-with-existing-apps.md
  website/versioned_docs/version-0.70/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.70/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.70/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.70/integration-with-existing-apps.md
  website/versioned_docs/version-0.71/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.71/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.71/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.71/integration-with-existing-apps.md
Labels: Partner, p: Facebook, CLA Signed

#3570 Update the "Build from source" page
  website/contributing/how-to-build-from-source.md
Labels: :clock1: Waiting on PR, Partner, p: Facebook, CLA Signed

#3578 docs: update links and init command to 0.71
  docs/the-new-architecture/cxx-cxxturbomodules.md
  website/versioned_docs/version-0.71/the-new-architecture/cxx-cxxturbomodules.md
Labels: CLA Signed

#3580 Docs: RN's minimum Node version 14->16
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3574 Specify Explicit React Native Version For Init
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  docs/the-new-architecture/use-app-template.md
  website/versioned_docs/version-0.71/_getting-started-linux-android.md
  website/versioned_docs/version-0.71/_getting-started-macos-android.md
  website/versioned_docs/version-0.71/_getting-started-macos-ios.md
  website/versioned_docs/version-0.71/_getting-started-windows-android.md
  website/versioned_docs/version-0.71/the-new-architecture/use-app-template.md
Labels: Partner, p: Facebook, CLA Signed

#3583 Fix Info block
  docs/the-new-architecture/pillars.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars.md
Labels: Partner, p: Facebook, CLA Signed

#3585 docs: fix app.js/app.tsx references in quickstart
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  docs/getting-started.md
  website/versioned_docs/version-0.71/_getting-started-linux-android.md
  website/versioned_docs/version-0.71/_getting-started-macos-android.md
  website/versioned_docs/version-0.71/_getting-started-macos-ios.md
  website/versioned_docs/version-0.71/_getting-started-windows-android.md
  website/versioned_docs/version-0.71/getting-started.md
Labels: CLA Signed

#3586 Add language alternatives to TM&Fabric guides
  docs/the-new-architecture/pillars-fabric-components.md
  docs/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: Facebook, CLA Signed

#3575 Fix Flow/TypeScript Mismatches in New Architecture Library Intro
  docs/new-architecture-library-intro.md
  website/versioned_docs/version-0.71/new-architecture-library-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3589 Updating dead link for label-action workflow
  website/contributing/bots-reference.md
Labels: CLA Signed

#3581 ci: check if external urls in markdown respond
  docs/network.md
  docs/profiling.md
  docs/typescript.md
  plugins/remark-lint-no-dead-urls/LICENSE
  plugins/remark-lint-no-dead-urls/README.md
  plugins/remark-lint-no-dead-urls/package.json
  plugins/remark-lint-no-dead-urls/src/__tests__/index.js
  plugins/remark-lint-no-dead-urls/src/index.js
  plugins/remark-lint-no-dead-urls/src/lib.js
  website/.remarkrc.mjs
  website/package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#3591 fix: add vertical line in project structure
  docs/the-new-architecture/cxx-cxxturbomodules.md
Labels: CLA Signed

#3590 fix: update android sdk version
  docs/_getting-started-macos-android.md
Labels: CLA Signed

#3594 fix: ruby version link (#3592)
  docs/_getting-started-macos-ios.md
  website/versioned_docs/version-0.70/_getting-started-macos-ios.md
  website/versioned_docs/version-0.71/_getting-started-macos-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3596 docs: remove references to Ruby Version Management
  docs/_getting-started-macos-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3595 fix: Cocoapods -> CocoaPods
  website/react-native-dict.json
  website/versioned_docs/version-0.60/navigation.md
  website/versioned_docs/version-0.61/navigation.md
  website/versioned_docs/version-0.62/navigation.md
  website/versioned_docs/version-0.63/navigation.md
  website/versioned_docs/version-0.64/navigation.md
  website/versioned_docs/version-0.65/navigation.md
  website/versioned_docs/version-0.66/navigation.md
  website/versioned_docs/version-0.67/navigation.md
  website/versioned_docs/version-0.68/_markdown-m1-cocoapods.mdx
  website/versioned_docs/version-0.68/navigation.md
  website/versioned_docs/version-0.69/_markdown-m1-cocoapods.mdx
  website/versioned_docs/version-0.69/navigation.md
  website/versioned_docs/version-0.70/_getting-started-macos-ios.md
  website/versioned_docs/version-0.70/_markdown-m1-cocoapods.mdx
  website/versioned_docs/version-0.70/navigation.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.71/_getting-started-macos-ios.md
  website/versioned_docs/version-0.71/navigation.md
  website/versioned_docs/version-0.71/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.71/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: Facebook, CLA Signed

#3597 fix: case-police use local dictionary
  website/package.json
Labels: Partner, p: Facebook, CLA Signed

#3572 Add docs for `setColorScheme`
  docs/appearance.md
Labels: CLA Signed
