Repository facebook/react-native-website, pull requests merged in 2023-09, with the labels that each got.

#3841 Update bots-reference.md
  website/contributing/bots-reference.md
Labels: CLA Signed

#3840 Update components-and-apis.md
  docs/components-and-apis.md
Labels: CLA Signed

#3839 Add Reactiflux to list of communities
  website/community/communities.md
Labels: CLA Signed

#3764 Sync docs with current status of `upgrade` command.
  docs/upgrading.md
Labels: CLA Signed

#3830 chore: prepare docs for Docusaurus v3 upgrade - 2nd iteration
  docs/native-components-ios.md
  docs/profile-hermes.md
  docs/pushnotificationios.md
  docs/scrollview.md
  docs/touchablenativefeedback.md
  website/architecture/render-pipeline.md
  website/blog/2016-08-19-right-to-left-support-for-react-native-apps.md
  website/blog/2016-12-05-easier-upgrades.md
  website/blog/2021-09-01-preparing-your-app-for-iOS-15-and-android-12.md
  website/versioned_docs/version-0.70/native-components-ios.md
  website/versioned_docs/version-0.70/profile-hermes.md
  website/versioned_docs/version-0.70/pushnotificationios.md
  website/versioned_docs/version-0.70/scrollview.md
  website/versioned_docs/version-0.70/touchablenativefeedback.md
  website/versioned_docs/version-0.71/native-components-ios.md
  website/versioned_docs/version-0.71/profile-hermes.md
  website/versioned_docs/version-0.71/pushnotificationios.md
  website/versioned_docs/version-0.71/scrollview.md
  website/versioned_docs/version-0.71/touchablenativefeedback.md
  website/versioned_docs/version-0.72/native-components-ios.md
  website/versioned_docs/version-0.72/profile-hermes.md
  website/versioned_docs/version-0.72/pushnotificationios.md
  website/versioned_docs/version-0.72/scrollview.md
  website/versioned_docs/version-0.72/touchablenativefeedback.md
  yarn.lock
Labels: CLA Signed

#3843 chore: prepare docs for Docusaurus v3 upgrade - 3rd iteration
  docs/alertios.md
  docs/button.md
  docs/colors.md
  docs/new-architecture-app-intro.md
  docs/the-new-architecture/backward-compatibility-fabric-components.md
  docs/the-new-architecture/backward-compatibility-turbomodules.md
  docs/touchablenativefeedback.md
  website/versioned_docs/version-0.70/alertios.md
  website/versioned_docs/version-0.70/button.md
  website/versioned_docs/version-0.70/colors.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.70/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.70/touchablenativefeedback.md
  website/versioned_docs/version-0.71/alertios.md
  website/versioned_docs/version-0.71/button.md
  website/versioned_docs/version-0.71/colors.md
  website/versioned_docs/version-0.71/new-architecture-app-intro.md
  website/versioned_docs/version-0.71/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.71/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.71/touchablenativefeedback.md
  website/versioned_docs/version-0.72/alertios.md
  website/versioned_docs/version-0.72/button.md
  website/versioned_docs/version-0.72/colors.md
  website/versioned_docs/version-0.72/new-architecture-app-intro.md
  website/versioned_docs/version-0.72/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.72/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.72/touchablenativefeedback.md
Labels: CLA Signed

#3842 docs: transform origin
  docs/transforms.md
Labels: CLA Signed

#3804 docs: Update prop values for textContentType and autoComplete
  docs/textinput.md
Labels: CLA Signed

#3847 Remove out dated caveat about using setTimeout from a headless js task
  docs/headless-js-android.md
  website/versioned_docs/version-0.70/headless-js-android.md
  website/versioned_docs/version-0.71/headless-js-android.md
  website/versioned_docs/version-0.72/headless-js-android.md
Labels: CLA Signed

#3846 Fix syntax on transform examples
  docs/transforms.md
  website/versioned_docs/version-0.70/transforms.md
  website/versioned_docs/version-0.71/transforms.md
  website/versioned_docs/version-0.72/transforms.md
Labels: Partner, p: Facebook, CLA Signed

#3744 Add Brex to the app showcase
  website/showcase.json
  website/static/img/showcase/brex.png
Labels: CLA Signed

#3780 Upgrade React-Native website to Docusaurus v3
  docs/hermes.md
  docs/introduction.md
  plugins/remark-snackplayer/package.json
  plugins/remark-snackplayer/src/index.js
  website/blog/2015-03-26-react-native-bringing-modern-web-techniques-to-mobile.md
  website/blog/2015-09-14-react-native-for-android.md
  website/blog/2015-11-23-making-react-native-apps-accessible.md
  website/blog/2016-03-28-dive-into-react-native-performance.md
  website/blog/2016-04-13-react-native-a-year-in-review.md
  website/blog/2018-03-05-AWS-app-sync.md
  website/blog/2019-06-12-react-native-open-source-update.md
  website/core/DocsRating.js
  website/docusaurus.config.js
  website/package.json
  website/src/css/customTheme.scss
  website/src/theme/MDXComponents/Code.js
  website/src/theme/MDXComponents/InlineCode.js
  website/src/theme/MDXComponents/index.js
  website/versioned_docs/version-0.70/hermes.md
  website/versioned_docs/version-0.70/introduction.md
  website/versioned_docs/version-0.71/hermes.md
  website/versioned_docs/version-0.71/introduction.md
  website/versioned_docs/version-0.72/hermes.md
  website/versioned_docs/version-0.72/introduction.md
  yarn.lock
Labels: CLA Signed

#3850 change file extension to ts in turbo modules creation guide
  docs/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.72/the-new-architecture/pillars-turbomodule.md
Labels: CLA Signed

#3854 Fix link to redirect to standalone react-devtools
  website/versioned_docs/version-0.72/debugging.md
Labels: CLA Signed

#3856 fix(getting started): update Android SDK path in Android Studio
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-windows-android.md
  website/versioned_docs/version-0.70/_getting-started-linux-android.md
  website/versioned_docs/version-0.70/_getting-started-macos-android.md
  website/versioned_docs/version-0.70/_getting-started-windows-android.md
  website/versioned_docs/version-0.71/_getting-started-linux-android.md
  website/versioned_docs/version-0.71/_getting-started-macos-android.md
  website/versioned_docs/version-0.71/_getting-started-windows-android.md
  website/versioned_docs/version-0.72/_getting-started-linux-android.md
  website/versioned_docs/version-0.72/_getting-started-macos-android.md
  website/versioned_docs/version-0.72/_getting-started-windows-android.md
Labels: CLA Signed

#3855 Delist unmaintained Out-of-Tree Platforms
  docs/out-of-tree-platforms.md
  website/versioned_docs/version-0.71/out-of-tree-platforms.md
  website/versioned_docs/version-0.72/out-of-tree-platforms.md
Labels: Partner, p: expo, CLA Signed

#3859 Fix formatting (followup to #3858)
  website/contributing/release-testing.md
Labels: Partner, p: Facebook, CLA Signed
