Repository facebook/react-native-website, pull requests merged in 2023-01, with the labels that each got.

#3494 Add TypeScript blog post and Nick as author
  website/blog/2023-01-03-typescript-first.md
  website/blog/authors.yml
  website/static/blog/assets/typescript-first-new-app.png
Labels: Partner, p: Facebook, CLA Signed

#3490 fix: improve examples for Android Native Modules addListener/removeListeners
  docs/native-modules-android.md
  website/versioned_docs/version-0.65/native-modules-android.md
  website/versioned_docs/version-0.66/native-modules-android.md
  website/versioned_docs/version-0.67/native-modules-android.md
  website/versioned_docs/version-0.68/native-modules-android.md
  website/versioned_docs/version-0.69/native-modules-android.md
  website/versioned_docs/version-0.70/native-modules-android.md
Labels: CLA Signed

#3498 Add @latest when creating library to ensure up-to-date template
  docs/native-modules-setup.md
  website/versioned_docs/version-0.64/native-modules-setup.md
  website/versioned_docs/version-0.65/native-modules-setup.md
  website/versioned_docs/version-0.66/native-modules-setup.md
  website/versioned_docs/version-0.67/native-modules-setup.md
  website/versioned_docs/version-0.68/native-modules-setup.md
  website/versioned_docs/version-0.69/native-modules-setup.md
  website/versioned_docs/version-0.70/native-modules-setup.md
Labels: Partner, Contributor, p: callstack, CLA Signed

#3381 Include window reference for iOS swift projects
  docs/_integration-with-exisiting-apps-swift.md
Labels: CLA Signed

#3488 Remove `findNodeHandle` and `measure*()` New Architecture Migration Steps
  docs/new-architecture-library-intro.md
Labels: Partner, p: Facebook, CLA Signed

#3500 Fixes broken link for a Github maintainer in 2023-01-03 blog
  website/blog/2023-01-03-typescript-first.md
Labels: CLA Signed

#3505 Update diffs in TypeScript path alias instructions
  docs/typescript.md
Labels: Partner, p: Facebook, CLA Signed

#3509 Fixed typo.
  docs/handling-touches.md
Labels: CLA Signed

#3512 Fix typo in animated.md
  docs/animated.md
Labels: CLA Signed

#3507 [Release] Add heuristic on how to manually handle the changelog
  website/contributing/release-branch-cut-and-rc0.md
Labels: Partner, p: Facebook, CLA Signed

#3516 Unbreak broken link on main
  website/versioned_docs/version-0.68/build-speed.md
Labels: Partner, p: Facebook, CLA Signed

#3513 Add 0.71 blog post
  website/blog/2023-01-03-typescript-first.md
  website/blog/2023-01-12-version-071.md
  website/blog/authors.yml
  website/static/blog/assets/ElementInspecting.gif
  website/static/blog/assets/FlexboxGapAfter.png
  website/static/blog/assets/FlexboxGapBefore.png
Labels: Partner, p: Facebook, CLA Signed

#3517 Update getting-started.md
  docs/getting-started.md
  website/versioned_docs/version-0.71/getting-started.md
Labels: CLA Signed

#3514 Feat: Update releasing a minor
  website/contributing/release-stable-minor.md
Labels: Partner, p: Facebook, CLA Signed

#3502 Update react-18-and-react-native.md
  docs/react-18-and-react-native.md
Labels: CLA Signed

#3499 Grammar/typo fix: Add hyphen to title
  docs/platform-specific-code.md
Labels: CLA Signed

#3520 fix errors in keyboard.md
  docs/keyboard.md
  website/versioned_docs/version-0.71/keyboard.md
Labels: CLA Signed

#3522 Replace deprecated `--variant` with `--mode`
  docs/signed-apk-android.md
Labels: CLA Signed

#3518 Update running-on-device.md
  docs/running-on-device.md
Labels: CLA Signed

#3523 Replace deprecated --variant with --mode in 0.71 docs version
  website/versioned_docs/version-0.71/signed-apk-android.md
Labels: CLA Signed

#3524 Fix import in Turbo Native Modules sample code
  docs/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.70/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: Facebook, CLA Signed

#3525 Update pillars-turbomodule.md
  docs/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: callstack, CLA Signed

#3526 Update pillars-codegen.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-codegen.md
Labels: Partner, p: callstack, CLA Signed

#3527 correct artifact codegen script name
  docs/new-architecture-library-ios.md
  docs/the-new-architecture/pillars-codegen.md
  docs/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.71/new-architecture-library-ios.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.71/the-new-architecture/pillars-turbomodule.md
Labels: Partner, p: expo, CLA Signed

#3535 Adding an info box on NVM and zsh to MacOS + iOS
  docs/_getting-started-macos-ios.md
Labels: CLA Signed

#3538 Update headless-js documentation
  docs/headless-js-android.md
Labels: CLA Signed

#3542 [Blogpost] React Native 0.71-RC0 Android outage postmortem
  website/blog/2023-01-27-71rc1-android-outage-postmortem.md
Labels: Partner, p: Facebook, CLA Signed

#3540 Update optimizing-flatlist-configuration.md
  docs/optimizing-flatlist-configuration.md
Labels: CLA Signed

#3543 Clarify docs around DefaultReactNativeHost
  docs/integration-with-android-fragment.md
  website/versioned_docs/version-0.71/integration-with-android-fragment.md
Labels: Partner, p: Facebook, CLA Signed

#3503 Add page to speed up CI builds
  docs/speeding-ci-builds.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#3546 Remove references to pre-release of 71
  website/blog/2023-01-03-typescript-first.md
Labels: Partner, p: Facebook, CLA Signed

#3544 Fix "tsconfig.json" and "babel.config.js" example code
  docs/typescript.md
Labels: CLA Signed
