Repository facebook/react-native-website, pull requests merged in 2024-05, with the labels that each got.

#4103 Remove mention of deprecated Expo upgrade command
  docs/upgrading.md
  website/versioned_docs/version-0.74/upgrading.md
Labels: CLA Signed

#4102 fix: use new doc link from react.dev for ts
  docs/typescript.md
  website/versioned_docs/version-0.74/typescript.md
Labels: CLA Signed

#4106 Update ReactConf Banner
  website/docusaurus.config.js
Labels: Partner, p: Facebook, CLA Signed

#4107 Use startForegroundService instead startService
  docs/headless-js-android.md
  website/versioned_docs/version-0.74/headless-js-android.md
Labels: CLA Signed

#4108 Remove abandoned bug reference from TextInput
  docs/textinput.md
  website/versioned_docs/version-0.74/textinput.md
Labels: CLA Signed

#4112 Oculus -> Meta Quest
  website/showcase.json
  website/src/pages/showcase.js
  website/static/img/showcase/metaquest.png
Labels: Partner, p: Facebook, CLA Signed

#4086 Adds getting started docs with React Native Frameworks
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  docs/_integration-with-existing-apps-java.md
  docs/_integration-with-existing-apps-kotlin.md
  docs/_integration-with-existing-apps-objc.md
  docs/_integration-with-existing-apps-swift.md
  docs/get-started-without-a-framework.md
  docs/getting-started.md
  docs/introduction.md
  docs/set-up-your-environment.md
  docs/typescript.md
  website/architecture/architecture-glossary.md
  website/sidebars.json
  website/src/theme/Badge/index.js
  website/src/theme/Badge/styles.module.css
  website/src/theme/BoxLink/index.js
  website/src/theme/BoxLink/styles.module.css
  website/src/theme/Icon/Android/index.js
  website/src/theme/Icon/Apple/index.js
  website/src/theme/Icon/TV/index.js
  website/src/theme/Icon/Web/index.js
  website/src/theme/PlatformSupport/index.js
  website/src/theme/PlatformSupport/styles.module.css
Labels: CLA Signed

#4115 Backport "Adds getting started docs with React Native Frameworks" to 0.74
  website/versioned_docs/version-0.74/_getting-started-linux-android.md
  website/versioned_docs/version-0.74/_getting-started-macos-android.md
  website/versioned_docs/version-0.74/_getting-started-macos-ios.md
  website/versioned_docs/version-0.74/_getting-started-windows-android.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.74/get-started-without-a-framework.md
  website/versioned_docs/version-0.74/getting-started.md
  website/versioned_docs/version-0.74/introduction.md
  website/versioned_docs/version-0.74/set-up-your-environment.md
  website/versioned_docs/version-0.74/typescript.md
  website/versioned_sidebars/version-0.74-sidebars.json
Labels: CLA Signed

#4117 fix: RN CLI packaga name
  docs/get-started-without-a-framework.md
  website/versioned_docs/version-0.74/get-started-without-a-framework.md
Labels: CLA Signed

#4100 Homepage redesign
  website/src/css/customTheme.scss
  website/src/pages/Home/CallToAction/index.js
  website/src/pages/Home/CallToAction/styles.module.css
  website/src/pages/Home/Community/index.js
  website/src/pages/Home/Community/styles.module.css
  website/src/pages/Home/Framework/index.js
  website/src/pages/Home/Framework/styles.module.css
  website/src/pages/Home/Hero/Devices.js
  website/src/pages/Home/Hero/FloorBackground.js
  website/src/pages/Home/Hero/GridBackground.js
  website/src/pages/Home/Hero/index.js
  website/src/pages/Home/Hero/styles.module.css
  website/src/pages/Home/Logo.js
  website/src/pages/Home/Native/index.js
  website/src/pages/Home/Native/styles.module.css
  website/src/pages/Home/Platforms/FoxFact.js
  website/src/pages/Home/Platforms/index.js
  website/src/pages/Home/Platforms/styles.module.css
  website/src/pages/Home/Watch/index.js
  website/src/pages/Home/Watch/styles.module.css
  website/src/pages/Home/components/Section/index.js
  website/src/pages/Home/components/Section/styles.module.css
  website/src/pages/Home/components/SectionTitle/index.js
  website/src/pages/Home/components/SectionTitle/styles.module.css
  website/src/pages/Home/components/ThemeImage/index.js
  website/src/pages/Home/index.js
  website/src/pages/animations/_dissectionAnimation.js
  website/src/pages/animations/_headerAnimation.js
  website/src/pages/index.js
  website/src/pages/showcase.js
  website/static/img/header_logo.svg
  website/static/img/homepage/cross-platform.svg
  website/static/img/homepage/cta-bg-pattern.png
  website/static/img/homepage/devices-dark.png
  website/static/img/homepage/devices.png
  website/static/img/homepage/dissection-dark.png
  website/static/img/homepage/dissection.png
  website/static/img/homepage/dissection.svg
  website/static/img/homepage/dissection/0.png
  website/static/img/homepage/dissection/1.png
  website/static/img/homepage/dissection/2.png
  website/static/img/homepage/dissection/3.png
  website/static/img/homepage/fb-logo.svg
  website/static/img/homepage/file-based-routing-dark.png
  website/static/img/homepage/file-based-routing.png
  website/static/img/homepage/libraries-dark.png
  website/static/img/homepage/libraries.png
  website/static/img/homepage/phones.png
  website/static/img/homepage/tools-dark.png
  website/static/img/homepage/tools.png
Labels: CLA Signed

#4118 address small issues with new Home page
  website/src/css/index.scss
  website/src/pages/Home/Hero/FloorBackground.js
  website/src/pages/Home/components/SectionTitle/styles.module.css
Labels: Partner, p: expo, CLA Signed

#4120 react conference 2024 is added
  website/community/staying-updated.md
Labels: CLA Signed

#4127 Remove Horizontal Scroll
  website/src/pages/Home/Hero/styles.module.css
Labels: CLA Signed

#4123 Revert React Conf 2024 banner
  website/docusaurus.config.js
Labels: Partner, p: Facebook, CLA Signed

#4128 fix: add missing icons to supported platforms
  website/src/theme/Icon/VisionOS/index.js
  website/src/theme/Icon/Windows/index.js
  website/src/theme/PlatformSupport/index.js
  website/versioned_docs/version-0.74/get-started-without-a-framework.md
Labels: Partner, p: callstack, CLA Signed

#4129 App.js conf 2024 video playlist added
  website/community/staying-updated.md
Labels: CLA Signed

#4126 Fix homepage and environment setup docs styling
  website/src/pages/Home/Hero/Devices.js
  website/src/pages/Home/Hero/styles.module.css
  website/src/pages/Home/Watch/index.js
  website/src/pages/Home/Watch/styles.module.css
  website/src/theme/BoxLink/index.js
  website/src/theme/BoxLink/styles.module.css
  website/static/img/homepage/tools-dark.png
  website/static/img/homepage/tools.png
Labels: CLA Signed
