Repository facebook/react-native-website, pull requests merged in 2024-08, with the labels that each got.

#4171 Fix 404 on _integration-with-existing-apps-swift.md
  docs/_integration-with-existing-apps-swift.md
Labels: Partner, p: Facebook, CLA Signed

#4174 Adding more authors to the website
  website/blog/authors.yml
Labels: Partner, p: Facebook, CLA Signed

#4175 [NewArch] Move the New Arch from Exp to Beta and reword a paragraph
  docs/the-new-architecture/landing-page.md
  website/sidebars.json
  website/versioned_docs/version-0.74/the-new-architecture/landing-page.md
  website/versioned_sidebars/version-0.74-sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4177 Upgrade dependencies. Remove Axios as dependency
  package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#4176 [RN][Blog] Add blogpost for 0.75
  website/blog/2024-08-12-release-0.75.md
  website/static/blog/assets/0.75-android-gaps.png
  website/static/blog/assets/0.75-android-translations.png
  website/static/blog/assets/0.75-deprecation.png
  website/static/blog/assets/0.75-ios-gaps.png
  website/static/blog/assets/0.75-ios-translation.png
  website/static/blog/assets/0.75-rn-directory.png
Labels: Partner, p: Facebook, CLA Signed

#4179 Add reference on how to use Expo SDK 51 w/ 0.75
  website/blog/2024-08-12-release-0.75.md
Labels: Partner, p: Facebook, CLA Signed

#4181 Renamed the versioned sidebar file for 0.75
  website/versioned_sidebars/version-0.75-sidebars.json
Labels: CLA Signed

#4183 Fix typos
  docs/flatlist.md
  docs/linking.md
  docs/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.75/flatlist.md
  website/versioned_docs/version-0.75/linking.md
  website/versioned_docs/version-0.75/optimizing-flatlist-configuration.md
Labels: CLA Signed

#4185 Update 2024-08-12-release-0.75.md
  website/blog/2024-08-12-release-0.75.md
Labels: CLA Signed

#4188 fix typos, backport recent fixes to versioned docs
  docs/_integration-with-existing-apps-java.md
  docs/_integration-with-existing-apps-kotlin.md
  docs/flatlist.md
  docs/flexbox.md
  docs/native-modules-ios.md
  docs/running-on-simulator-ios.md
  docs/scrollview.md
  website/versioned_docs/version-0.70/linking.md
  website/versioned_docs/version-0.70/native-modules-ios.md
  website/versioned_docs/version-0.70/running-on-simulator-ios.md
  website/versioned_docs/version-0.71/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.71/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.71/flatlist.md
  website/versioned_docs/version-0.71/flexbox.md
  website/versioned_docs/version-0.71/linking.md
  website/versioned_docs/version-0.71/native-modules-ios.md
  website/versioned_docs/version-0.71/running-on-simulator-ios.md
  website/versioned_docs/version-0.71/scrollview.md
  website/versioned_docs/version-0.72/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.72/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.72/flatlist.md
  website/versioned_docs/version-0.72/flexbox.md
  website/versioned_docs/version-0.72/linking.md
  website/versioned_docs/version-0.72/native-modules-ios.md
  website/versioned_docs/version-0.72/network.md
  website/versioned_docs/version-0.72/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.72/running-on-simulator-ios.md
  website/versioned_docs/version-0.72/scrollview.md
  website/versioned_docs/version-0.73/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.73/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.73/flatlist.md
  website/versioned_docs/version-0.73/flexbox.md
  website/versioned_docs/version-0.73/linking.md
  website/versioned_docs/version-0.73/native-modules-ios.md
  website/versioned_docs/version-0.73/network.md
  website/versioned_docs/version-0.73/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.73/running-on-simulator-ios.md
  website/versioned_docs/version-0.73/scrollview.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.74/flatlist.md
  website/versioned_docs/version-0.74/flexbox.md
  website/versioned_docs/version-0.74/linking.md
  website/versioned_docs/version-0.74/native-modules-ios.md
  website/versioned_docs/version-0.74/network.md
  website/versioned_docs/version-0.74/optimizing-flatlist-configuration.md
  website/versioned_docs/version-0.74/running-on-simulator-ios.md
  website/versioned_docs/version-0.74/scrollview.md
  website/versioned_docs/version-0.75/_integration-with-existing-apps-java.md
  website/versioned_docs/version-0.75/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.75/flatlist.md
  website/versioned_docs/version-0.75/flexbox.md
  website/versioned_docs/version-0.75/native-modules-ios.md
  website/versioned_docs/version-0.75/network.md
  website/versioned_docs/version-0.75/running-on-simulator-ios.md
  website/versioned_docs/version-0.75/scrollview.md
Labels: Partner, p: expo, CLA Signed

#4190 Remove PropTypes from `native-components-ios.md`
  docs/native-components-ios.md
  website/versioned_docs/version-0.75/native-components-ios.md
Labels: Partner, p: Facebook, CLA Signed

#4191 Remove PropTypes from `native-components-android.md`
  docs/native-components-android.md
  website/versioned_docs/version-0.75/native-components-android.md
Labels: Partner, p: Facebook, CLA Signed

#4192 Remove PropTypes from `performance.md`
  docs/performance.md
  website/versioned_docs/version-0.75/performance.md
Labels: Partner, p: Facebook, CLA Signed

#4193 Delete `custom-webview-*.md`
  docs/custom-webview-android.md
  docs/custom-webview-ios.md
Labels: Partner, p: Facebook, CLA Signed

#4194 Delete `progressviewios.md`
  docs/progressviewios.md
  website/blog/2023-06-21-0.72-metro-package-exports-symlinks.md
Labels: Partner, p: Facebook, CLA Signed

#4195 Delete `slider.md`
  docs/slider.md
Labels: Partner, p: Facebook, CLA Signed

#4187 update Docusaurus, fix swizzled components, correct authors data, UI tweaks
  website/blog/2016-08-12-react-native-meetup-san-francisco.md
  website/blog/2016-09-08-exponent-talks-unraveling-navigation.md
  website/blog/2016-10-25-0.36-headless-js-the-keyboard-api-and-more.md
  website/blog/2016-11-08-introducing-button-yarn-and-a-public-roadmap.md
  website/blog/2017-08-30-react-native-monthly-3.md
  website/blog/2017-09-21-react-native-monthly-4.md
  website/blog/2018-01-18-implementing-twitters-app-loading-animation-in-react-native.md
  website/blog/2019-03-01-react-native-open-source-update.md
  website/blog/2019-05-01-react-native-at-f8-and-podcast.md
  website/blog/2019-06-12-react-native-open-source-update.md
  website/blog/2020-07-06-version-0.63.md
  website/blog/2020-07-17-react-native-principles.md
  website/blog/2021-03-08-GAAD-React-Native-Accessibility.md
  website/blog/2021-03-12-version-0.64.md
  website/blog/2021-04-08-GAAD-March-Accessibility-Issue-Update.md
  website/blog/2021-05-20-GAAD-One-Year-Later.md
  website/blog/2021-08-26-many-platform-vision.md
  website/blog/2021-08-30-react-native-is-hiring-managers.md
  website/blog/authors.yml
  website/core/PlatformTag.js
  website/docusaurus.config.js
  website/package.json
  website/src/css/customTheme.scss
  website/src/theme/Blog/Components/Author/index.js
  website/src/theme/Blog/Components/Author/styles.module.css
  website/src/theme/DocItem/Footer/index.js
  website/src/theme/DocVersionBanner/index.js
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#4199 Add re-watch banner for React Conf Keynote 2024
  website/docusaurus.config.js
Labels: Partner, p: Facebook, CLA Signed

#4202 docs: Update running-on-device.md for iOS to include mention about USB-C cables
  docs/running-on-device.md
Labels: CLA Signed
