Repository facebook/react-native-website, pull requests merged in 2024-06, with the labels that each got.

#4133 Add java_home env var for macos
  docs/_getting-started-macos-android.md
  website/versioned_docs/version-0.74/_getting-started-macos-android.md
Labels: CLA Signed

#4135 fix: update windows icon
  website/src/theme/Icon/Windows/index.js
Labels: Partner, p: callstack, CLA Signed

#4139 [docs] Retitle native debugging guide
  docs/debugging-native-code.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4143 Migrate to GitHub Actions from CircleCI
  .github/workflows/pre-merge.yml
Labels: CLA Signed

#4146 Remove CircleCI setup
  .circleci/config.yml
Labels: Partner, p: Facebook, CLA Signed

#4148 Mention React Native visionOS in OOT platforms page
  docs/out-of-tree-platforms.md
Labels: Partner, p: callstack, CLA Signed

#4152 [Blogpost] Use a framework to build React Native apps
  website/blog/2024-06-25-use-a-framework-to-build-react-native-apps.md
Labels: Partner, p: Facebook, CLA Signed
