Repository facebook/react-native-website, pull requests merged in 2024-09, with the labels that each got.

#4206 docs: add resizeMultiplier to Image props
  docs/image.md
Labels: Partner, p: Facebook, CLA Signed

#4211 [0.75][main] Getting started: Bump documented Node.js minimum to 18.18
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  website/versioned_docs/version-0.75/_getting-started-linux-android.md
  website/versioned_docs/version-0.75/_getting-started-macos-android.md
  website/versioned_docs/version-0.75/_getting-started-macos-ios.md
  website/versioned_docs/version-0.75/_getting-started-windows-android.md
Labels: Partner, p: Facebook, CLA Signed

#4207 Update the screenshots in getting started page
  website/static/docs/assets/GettingStartedXcodeCommandLineTools.png
Labels: CLA Signed

#4212 docs: fix render pipeline typo, tweak wording slightly
  website/architecture/render-pipeline.md
Labels: CLA Signed

#4214 Add several Github social links to authors
  website/blog/authors.yml
Labels: Partner, p: Facebook, CLA Signed

#4217 Add guidance on deps to the contributing guide
  website/contributing/contributing-overview.md
  website/contributing/how-to-open-a-pull-request.md
Labels: Partner, p: Facebook, CLA Signed

#4205 docs: clarify the JDK update steps on MacOS
  docs/_getting-started-macos-android.md
Labels: CLA Signed

#4218 Improve ccache instructions Fixes #4215
  docs/build-speed.md
  website/versioned_docs/version-0.74/build-speed.md
  website/versioned_docs/version-0.75/build-speed.md
Labels: CLA Signed

#4220 Bump transitive deps: express, serve-static, send
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#4222 Fix `interpolate()` link on Animated docs
  docs/animated.md
Labels: Partner, p: Facebook, CLA Signed

#4223 fix incorrect font after the latest Docusaurus update
  website/src/css/customTheme.scss
Labels: Partner, p: expo, CLA Signed

#4219 Add GitHub prettier check
  website/.prettierignore
  website/package.json
  website/src/css/customTheme.scss
Labels: CLA Signed

#4224 Update Eli White's role from EM to SWE
  website/blog/authors.yml
Labels: Partner, p: Facebook, CLA Signed

#4228 Simplify root npm scripts
  README.md
  package.json
Labels: Partner, p: Facebook, CLA Signed

#4230 refactor: move examples to functional components
  docs/handling-touches.md
Labels: CLA Signed

#4229 Fully revamp the 'Integrating with existing apps' page for Android
  docs/_integration-with-existing-apps-java.md
  docs/_integration-with-existing-apps-kotlin.md
  docs/integration-with-existing-apps.md
  website/static/docs/assets/EmbeddedAppAndroidVideo.gif
Labels: Partner, p: Facebook, CLA Signed

#4233 docs: Removes unused import in Native Modules example in native-modules-ios.md
  docs/native-modules-ios.md
Labels: CLA Signed

#4231 update examples to use cross-platform SafeAreaView
  docs/accessibilityinfo.md
  docs/actionsheetios.md
  docs/activityindicator.md
  docs/alert.md
  docs/animated.md
  docs/animatedvaluexy.md
  docs/animations.md
  docs/appstate.md
  docs/backhandler.md
  docs/button.md
  docs/clipboard.md
  docs/dimensions.md
  docs/drawerlayoutandroid.md
  docs/easing.md
  docs/flatlist.md
  docs/flexbox.md
  docs/image-style-props.md
  docs/image.md
  docs/imagebackground.md
  docs/inputaccessoryview.md
  docs/interactionmanager.md
  docs/keyboard.md
  docs/layout-props.md
  docs/layoutanimation.md
  docs/modal.md
  docs/panresponder.md
  docs/permissionsandroid.md
  docs/pixelratio.md
  docs/platform.md
  docs/platformcolor.md
  docs/pressable.md
  docs/refreshcontrol.md
  docs/scrollview.md
  docs/sectionlist.md
  docs/settings.md
  docs/shadow-props.md
  docs/share.md
  docs/statusbar.md
  docs/stylesheet.md
  docs/switch.md
  docs/systrace.md
  docs/text-style-props.md
  docs/text.md
  docs/textinput.md
  docs/toastandroid.md
  docs/touchablehighlight.md
  docs/touchablenativefeedback.md
  docs/touchableopacity.md
  docs/touchablewithoutfeedback.md
  docs/transforms.md
  docs/usecolorscheme.md
  docs/usewindowdimensions.md
  docs/vibration.md
  docs/view-style-props.md
  docs/view.md
  docs/virtualizedlist.md
  plugins/remark-snackplayer/src/index.js
  scripts/lint-examples/package.json
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#4237 docs: fix small typos, in `ViewStyle`, `ViewToken`, `Text` docs
  docs/text.md
  docs/view-style-props.md
  docs/viewtoken.md
Labels: CLA Signed
