Repository facebook/react-native-website, pull requests merged in 2024-04, with the labels that each got.

#4069 Update optimizing-javascript-loading.md to remove class syntax
  docs/optimizing-javascript-loading.md
  website/versioned_docs/version-0.70/ram-bundles-inline-requires.md
  website/versioned_docs/version-0.71/ram-bundles-inline-requires.md
  website/versioned_docs/version-0.72/ram-bundles-inline-requires.md
  website/versioned_docs/version-0.73/ram-bundles-inline-requires.md
Labels: CLA Signed

#4072 Upgrade to Docusaurus v3.2
  docs/profile-hermes.md
  docs/shadow-props.md
  website/blog/2023-01-27-71rc1-android-outage-postmortem.md
  website/contributing/how-to-contribute-code.md
  website/docusaurus.config.js
  website/package.json
  website/src/css/customTheme.scss
  website/versioned_docs/version-0.70/profile-hermes.md
  website/versioned_docs/version-0.70/shadow-props.md
  website/versioned_docs/version-0.71/profile-hermes.md
  website/versioned_docs/version-0.71/shadow-props.md
  website/versioned_docs/version-0.72/profile-hermes.md
  website/versioned_docs/version-0.72/shadow-props.md
  website/versioned_docs/version-0.73/profile-hermes.md
  website/versioned_docs/version-0.73/shadow-props.md
  yarn.lock
Labels: CLA Signed

#4077 Remove unmaintained Keystore libraries
  docs/security.md
Labels: CLA Signed

#4080 Update state.md to new react website
  docs/state.md
  website/versioned_docs/version-0.72/state.md
  website/versioned_docs/version-0.73/state.md
Labels: CLA Signed

#4076 Update _integration-with-existing-apps-swift.md
  docs/_integration-with-existing-apps-objc.md
  docs/_integration-with-existing-apps-swift.md
  website/static/docs/assets/react-native-existing-app-integration-ios-before.png
Labels: CLA Signed

#4081 Fix punctuation in render pipeline: change `'“yellow“` to `'yellow'`
  website/architecture/render-pipeline.md
Labels: p: software mansion, Partner, CLA Signed

#4082 [android] 'native-modules-android' & 'native-components-android' docs consistency
  docs/native-components-android.md
  docs/native-modules-android.md
  website/versioned_docs/version-0.73/native-components-android.md
  website/versioned_docs/version-0.73/native-modules-android.md
Labels: CLA Signed

#4084 remove "New" tag from pages existing for a while
  website/src/css/customTheme.scss
Labels: Partner, p: expo, CLA Signed

#4043 Add 0.74 announcement post
  website/blog/2024-04-22-release-0.74.md
  website/static/blog/assets/0.74-align-content.png
  website/static/blog/assets/0.74-android-app-size.jpg
  website/static/blog/assets/0.74-row-reverse-after.png
  website/static/blog/assets/0.74-row-reverse-before.png
  website/static/blog/assets/0.74-static-example.png
Labels: Partner, p: Facebook, CLA Signed

#4091 Fix broken link on website
  website/versioned_docs/version-0.74/profile-hermes.md
Labels: Partner, p: Facebook, CLA Signed

#4088 Update X follow button and footer link
  website/docusaurus.config.js
  website/src/css/index.scss
  website/src/pages/index.js
Labels: Partner, p: Facebook, CLA Signed

#4093 [RN][NewArch] Fix website New Arch documentation
  website/versioned_docs/version-0.74/new-architecture-app-intro.md
  website/versioned_docs/version-0.74/new-architecture-appendix.md
  website/versioned_docs/version-0.74/new-architecture-intro.md
  website/versioned_docs/version-0.74/new-architecture-library-android.md
  website/versioned_docs/version-0.74/new-architecture-library-intro.md
  website/versioned_docs/version-0.74/new-architecture-library-ios.md
  website/versioned_docs/version-0.74/new-architecture-troubleshooting.md
  website/versioned_docs/version-0.74/react-native-gradle-plugin.md
  website/versioned_docs/version-0.74/the-new-architecture/_markdown_beta_ts_support.mdx
  website/versioned_docs/version-0.74/the-new-architecture/_markdown_native_deprecation.mdx
  website/versioned_docs/version-0.74/the-new-architecture/backward-compatibility-fabric-components.md
  website/versioned_docs/version-0.74/the-new-architecture/backward-compatibility-turbomodules.md
  website/versioned_docs/version-0.74/the-new-architecture/backward-compatibility.md
  website/versioned_docs/version-0.74/the-new-architecture/cxx-custom-types.md
  website/versioned_docs/version-0.74/the-new-architecture/cxx-cxxturbomodules.md
  website/versioned_docs/version-0.74/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.74/the-new-architecture/pillars-codegen.md
  website/versioned_docs/version-0.74/the-new-architecture/pillars-fabric-components.md
  website/versioned_docs/version-0.74/the-new-architecture/pillars-turbomodule.md
  website/versioned_docs/version-0.74/the-new-architecture/pillars.md
  website/versioned_docs/version-0.74/the-new-architecture/use-app-template.md
  website/versioned_docs/version-0.74/the-new-architecture/why.md
  website/versioned_sidebars/version-0.74-sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4089 Fix grammatical error in platform-specific-code.md
  docs/platform-specific-code.md
Labels: CLA Signed

#4095 [blog] Update 0.74 post with info on Flipper removal, extended attribution
  website/blog/2024-04-22-release-0.74.md
Labels: Partner, p: Facebook, CLA Signed

#4096 [docs] Update 0.74 versioned docs
  website/blog/2024-04-22-release-0.74.md
  website/versioned_docs/version-0.74/_getting-started-linux-android.md
  website/versioned_docs/version-0.74/_getting-started-macos-android.md
  website/versioned_docs/version-0.74/_getting-started-macos-ios.md
  website/versioned_docs/version-0.74/_getting-started-windows-android.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.74/flexbox.md
  website/versioned_docs/version-0.74/interactionmanager.md
  website/versioned_docs/version-0.74/intro-react.md
  website/versioned_docs/version-0.74/javascript-environment.md
  website/versioned_docs/version-0.74/layout-props.md
  website/versioned_docs/version-0.74/native-components-android.md
  website/versioned_docs/version-0.74/native-modules-android.md
  website/versioned_docs/version-0.74/native-modules-ios.md
  website/versioned_docs/version-0.74/optimizing-javascript-loading.md
  website/versioned_docs/version-0.74/platform-specific-code.md
  website/versioned_docs/version-0.74/platform.md
  website/versioned_docs/version-0.74/pushnotificationios.md
  website/versioned_docs/version-0.74/security.md
  website/versioned_docs/version-0.74/shadow-props.md
  website/versioned_docs/version-0.74/state.md
  website/versioned_docs/version-0.74/text-style-props.md
  website/versioned_docs/version-0.74/text.md
  website/versioned_docs/version-0.74/view-style-props.md
  website/versioned_docs/version-0.74/virtualizedlist.md
Labels: Partner, p: Facebook, CLA Signed

#4098 [blog] Adjust Flipper wording + links in 0.74 post
  website/blog/2024-04-22-release-0.74.md
Labels: Partner, p: Facebook, CLA Signed

#4097 feat: add iOS, Android tags into platform-specific
  docs/platform-specific-code.md
  website/versioned_docs/version-0.74/platform-specific-code.md
Labels: CLA Signed
