Repository facebook/react-native-website, pull requests merged in 2024-12, with the labels that each got.

#4376 docs(accessibility): document large content viewer support on iOS
  website/versioned_docs/version-0.76/accessibility.md
Labels: CLA Signed

#4160 Small update to Animations docs
  docs/animations.md
Labels: Partner, p: Facebook, CLA Signed

#4074 Update accessibilityIgnoresInvertColors in TouchableWithoutFeedback
  docs/touchablewithoutfeedback.md
Labels: CLA Signed

#4377 Enable Docusaurus native CSS transitions
  website/src/css/customTheme.scss
  website/src/css/index.scss
Labels: CLA Signed

#4375 Add packageManager field to package.json for Yarn version specification
  package.json
Labels: CLA Signed

#4382 Enable caching on pre-merge jobs
  .github/workflows/pre-merge.yml
Labels: Partner, p: Facebook, CLA Signed

#4366 [gha] tweaks for the pre-merge workflows
  .github/workflows/pre-merge.yml
Labels: Partner, p: expo, CLA Signed

#4381 Migrate codebase to TypeScript and update configurations
  .eslintrc.json
  .prettierrc.json
  docs/_fabric-native-components.jsx
  docs/_turbo-native-modules-components.jsx
  plugins/remark-lint-no-dead-urls/package.json
  plugins/remark-snackplayer/package.json
  website/core/DocsRating.tsx
  website/core/PlatformTag.tsx
  website/core/PrismTheme.ts
  website/core/TableRowWithCodeBlock.tsx
  website/core/TabsConstants.tsx
  website/core/VerticalTable.tsx
  website/docusaurus.config.js
  website/docusaurus.config.ts
  website/package.json
  website/src/css/customTheme.scss
  website/src/pages/Home/CallToAction/index.tsx
  website/src/pages/Home/Community/index.tsx
  website/src/pages/Home/Framework/index.tsx
  website/src/pages/Home/Hero/Devices.tsx
  website/src/pages/Home/Hero/FloorBackground.tsx
  website/src/pages/Home/Hero/GridBackground.tsx
  website/src/pages/Home/Hero/index.tsx
  website/src/pages/Home/Logo.tsx
  website/src/pages/Home/Native/index.tsx
  website/src/pages/Home/Platforms/FoxFact.tsx
  website/src/pages/Home/Platforms/index.tsx
  website/src/pages/Home/Watch/index.tsx
  website/src/pages/Home/components/Section/index.tsx
  website/src/pages/Home/components/SectionTitle/index.tsx
  website/src/pages/Home/components/ThemeImage/index.tsx
  website/src/pages/Home/index.tsx
  website/src/pages/index.tsx
  website/src/pages/showcase.tsx
  website/src/pages/versions.tsx
  website/src/theme/Badge/index.tsx
  website/src/theme/Blog/Components/Author/index.tsx
  website/src/theme/BlogSidebar/Desktop/index.d.ts
  website/src/theme/BlogSidebar/Desktop/index.tsx
  website/src/theme/BlogSidebar/Mobile/index.d.ts
  website/src/theme/BlogSidebar/Mobile/index.tsx
  website/src/theme/BoxLink/index.tsx
  website/src/theme/DocItem/Footer/index.tsx
  website/src/theme/DocVersionBanner/index.tsx
  website/src/theme/Icon/Android/index.tsx
  website/src/theme/Icon/Apple/index.tsx
  website/src/theme/Icon/ExternalLink/index.tsx
  website/src/theme/Icon/TV/index.tsx
  website/src/theme/Icon/VisionOS/index.tsx
  website/src/theme/Icon/Web/index.tsx
  website/src/theme/Icon/Windows/index.tsx
  website/src/theme/MDXComponents/Code.tsx
  website/src/theme/MDXComponents/InlineCode.tsx
  website/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
  website/src/theme/PlatformSupport/index.tsx
  website/tsconfig.json
  website/versioned_docs/version-0.76/_fabric-native-components.jsx
  website/versioned_docs/version-0.76/_turbo-native-modules-components.jsx
  yarn.lock
Labels: CLA Signed

#4384 Update Prettier to v3 and eslint mdx to support mdx 3
  docs/other-debugging-methods.md
  docs/timers.md
  package.json
  website/blog/2017-03-13-idx-the-existential-function.md
  website/src/css/customTheme.scss
  website/versioned_docs/version-0.70/debugging.md
  website/versioned_docs/version-0.70/timers.md
  website/versioned_docs/version-0.71/debugging.md
  website/versioned_docs/version-0.71/timers.md
  website/versioned_docs/version-0.72/debugging.md
  website/versioned_docs/version-0.72/timers.md
  website/versioned_docs/version-0.73/other-debugging-methods.md
  website/versioned_docs/version-0.73/timers.md
  website/versioned_docs/version-0.74/other-debugging-methods.md
  website/versioned_docs/version-0.74/timers.md
  website/versioned_docs/version-0.75/other-debugging-methods.md
  website/versioned_docs/version-0.75/timers.md
  website/versioned_docs/version-0.76/other-debugging-methods.md
  website/versioned_docs/version-0.76/timers.md
  yarn.lock
Labels: CLA Signed

#4385 Remove deprecated babel-eslint dependency
  package.json
  yarn.lock
Labels: CLA Signed

#4386 Refactor sidebar configuration to TypeScript
  website/docusaurus.config.ts
  website/sidebars.json
  website/sidebars.ts
  website/sidebarsArchitecture.json
  website/sidebarsArchitecture.ts
  website/sidebarsCommunity.json
  website/sidebarsCommunity.ts
  website/sidebarsContributing.json
  website/sidebarsContributing.ts
Labels: CLA Signed

#4392 Disable 'no-broken-external-links' Remark Rule to Optimize CI Performance by 92%
  website/.remarkrc.mjs
  website/package.json
  yarn.lock
Labels: CLA Signed

#4396 Update X handle for huntie
  website/blog/authors.yml
Labels: Partner, p: Facebook, CLA Signed

#4383 Enhance .gitignore files for better exclusion of unnecessary files
  .gitignore
Labels: CLA Signed

#4388 [RN][Codegen] Add docs for advanced iOS usage
  docs/the-new-architecture/using-codegen.md
  website/versioned_docs/version-0.76/the-new-architecture/using-codegen.md
Labels: Partner, p: Facebook, CLA Signed

#4402 [RN][NewArch] Add danger block for C++ TurboModule
  docs/the-new-architecture/pure-cxx-modules.md
  website/versioned_docs/version-0.76/the-new-architecture/pure-cxx-modules.md
Labels: Partner, p: Facebook, CLA Signed

#4408 Fix typos in Fabric Native Components Introduction
  docs/fabric-native-components-android.md
  docs/fabric-native-components-ios.md
  website/versioned_docs/version-0.76/fabric-native-components-android.md
  website/versioned_docs/version-0.76/fabric-native-components-ios.md
Labels: CLA Signed

#4404 fix(logic): Fix bug where deleteValue function was removing the wrong…
  docs/turbo-native-modules.md
Labels: CLA Signed

#4405 Update turbo-native-modules-android.md
  docs/turbo-native-modules-android.md
Labels: CLA Signed

#4407 Fix Codegen specification in Fabric Native Components Introduction
  docs/fabric-native-components.md
Labels: CLA Signed

#4393 Finish glob and fs-extra async implementation
  scripts/lint-examples/package.json
  scripts/lint-examples/src/lintExamples.js
  sync-api-docs/extractDocsFromRN.js
  sync-api-docs/package.json
  website/image-check.js
  website/package.json
  yarn.lock
Labels: CLA Signed

#4394 Fix some markdown files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  STYLEGUIDE.md
  plugins/remark-lint-no-dead-urls/README.md
  plugins/remark-snackplayer/README.md
  scripts/lint-examples/README.md
Labels: CLA Signed
