Repository facebook/react-native-website, pull requests merged in 2024-01, with the labels that each got.

#3966 fix table header appearance in dark mode
  website/src/css/customTheme.scss
Labels: Partner, p: expo, CLA Signed

#3973 Update react-native-gradle-plugin.md
  docs/react-native-gradle-plugin.md
Labels: CLA Signed

#3970 fix(#3969): overflow table heading text in TextInput section
  website/versioned_docs/version-0.73/textinput.md
Labels: CLA Signed

#3960 Fix some typos in the docs
  docs/images.md
Labels: CLA Signed

#3796 Update barStyle enum prop description on StatusBar component
  docs/statusbar.md
Labels: CLA Signed

#3745 add logical border radius props
  docs/view-style-props.md
Labels: CLA Signed

#3685 Update textinput.md
  docs/textinput.md
Labels: CLA Signed

#3551 docs: update grammar and inaccuracies in accessiblity page
  docs/accessibility.md
Labels: CLA Signed

#3976 Give the CircleCI machines more memory
  .circleci/config.yml
Labels: Partner, p: Facebook, CLA Signed

#3975 backport few of latest landed OSS PRs to versioned docs
  website/react-native-dict.json
  website/versioned_docs/version-0.70/images.md
  website/versioned_docs/version-0.71/images.md
  website/versioned_docs/version-0.72/accessibility.md
  website/versioned_docs/version-0.72/images.md
  website/versioned_docs/version-0.72/view-style-props.md
  website/versioned_docs/version-0.73/accessibility.md
  website/versioned_docs/version-0.73/images.md
  website/versioned_docs/version-0.73/statusbar.md
  website/versioned_docs/version-0.73/view-style-props.md
Labels: Partner, p: expo, CLA Signed

#3971 Revise documentation for scrollEventThrottle
  docs/animations.md
  docs/scrollview.md
  website/versioned_docs/version-0.70/scrollview.md
  website/versioned_docs/version-0.71/scrollview.md
  website/versioned_docs/version-0.72/scrollview.md
  website/versioned_docs/version-0.73/scrollview.md
Labels: Partner, p: Facebook, CLA Signed

#3982 [docs] Remove "Speeding Up CI Builds" guide
  docs/speeding-ci-builds.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#3983 remove community packages references from useWindowDimensions
  docs/usewindowdimensions.md
  website/versioned_docs/version-0.70/usewindowdimensions.md
  website/versioned_docs/version-0.71/usewindowdimensions.md
  website/versioned_docs/version-0.72/usewindowdimensions.md
  website/versioned_docs/version-0.73/usewindowdimensions.md
Labels: CLA Signed

#3981 Add a note about color scheme flickering on iOS between light and dark modes
  docs/appearance.md
  website/versioned_docs/version-0.70/appearance.md
  website/versioned_docs/version-0.71/appearance.md
  website/versioned_docs/version-0.72/appearance.md
  website/versioned_docs/version-0.73/appearance.md
Labels: CLA Signed

#3974 Update Codegen Docs
  docs/new-architecture-appendix.md
  docs/new-architecture-library-intro.md
  docs/the-new-architecture/pillars-codegen.md
Labels: Partner, p: Facebook, CLA Signed

#3958 Update "Building for TV" with link to TV repo
  docs/building-for-tv.md
  website/versioned_docs/version-0.70/building-for-tv.md
  website/versioned_docs/version-0.71/building-for-tv.md
  website/versioned_docs/version-0.72/building-for-tv.md
Labels: CLA Signed

#3988 [docs] Update Setting up development environment guide
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  docs/_getting-started-windows-android.md
  website/versioned_docs/version-0.70/_getting-started-linux-android.md
  website/versioned_docs/version-0.70/_getting-started-macos-android.md
  website/versioned_docs/version-0.70/_getting-started-macos-ios.md
  website/versioned_docs/version-0.70/_getting-started-windows-android.md
  website/versioned_docs/version-0.71/_getting-started-linux-android.md
  website/versioned_docs/version-0.71/_getting-started-macos-android.md
  website/versioned_docs/version-0.71/_getting-started-macos-ios.md
  website/versioned_docs/version-0.71/_getting-started-windows-android.md
  website/versioned_docs/version-0.72/_getting-started-linux-android.md
  website/versioned_docs/version-0.72/_getting-started-macos-android.md
  website/versioned_docs/version-0.72/_getting-started-macos-ios.md
  website/versioned_docs/version-0.72/_getting-started-windows-android.md
  website/versioned_docs/version-0.73/_getting-started-linux-android.md
  website/versioned_docs/version-0.73/_getting-started-macos-android.md
  website/versioned_docs/version-0.73/_getting-started-macos-ios.md
  website/versioned_docs/version-0.73/_getting-started-windows-android.md
Labels: CLA Signed

#3989 Update required Xcode version to 14.1
  docs/_getting-started-macos-ios.md
Labels: CLA Signed

#3990 Fix bad link in 2022-07-08-hermes-as-the-default.md
  website/blog/2022-07-08-hermes-as-the-default.md
Labels: CLA Signed

#3992 Adapt tsc command for yarn and npm
  docs/typescript.md
Labels: CLA Signed

#3995 Update testing instructions for Android
  website/contributing/how-to-run-and-write-tests.md
Labels: Partner, p: Facebook, CLA Signed

#3997 Add missing "object"
  docs/the-new-architecture/why.md
Labels: CLA Signed

#3999 Include missing import promise statements
  docs/native-modules-android.md
  website/versioned_docs/version-0.70/native-modules-android.md
  website/versioned_docs/version-0.71/native-modules-android.md
  website/versioned_docs/version-0.72/native-modules-android.md
  website/versioned_docs/version-0.73/native-modules-android.md
Labels: CLA Signed

#4002 Add minimal Debugging expectations to release testing guide
  website/contributing/release-testing.md
Labels: Partner, p: Facebook, CLA Signed

#4000 Update release instructions for changelog generator
  website/contributing/release-branch-cut-and-rc0.md
  website/contributing/release-stable-patch.md
Labels: Partner, p: Facebook, CLA Signed
