Repository facebook/react-native-website, pull requests merged in 2024-03, with the labels that each got.

#4012 Update PushNotificationIOS docs for 0.74
  docs/pushnotificationios.md
Labels: Partner, p: Facebook, CLA Signed

#4020 Update Xcode recommendation to use latest
  docs/_getting-started-macos-ios.md
  website/versioned_docs/version-0.70/_getting-started-macos-ios.md
  website/versioned_docs/version-0.71/_getting-started-macos-ios.md
  website/versioned_docs/version-0.72/_getting-started-macos-ios.md
  website/versioned_docs/version-0.73/_getting-started-macos-ios.md
Labels: Partner, p: Facebook, CLA Signed

#3998 Rework the New Architecture Section
  docs/the-new-architecture/landing-page.md
  website/sidebars.json
  website/src/css/index.scss
  website/static/_redirects
  website/static/img/new-architecture/async-on-layout.gif
  website/static/img/new-architecture/legacy-renderer.gif
  website/static/img/new-architecture/react18-renderer.gif
  website/static/img/new-architecture/sync-use-layout-effect.gif
  website/static/img/new-architecture/with-transitions.gif
  website/static/img/new-architecture/without-transitions.gif
  website/versioned_docs/version-0.70/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.71/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.72/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.73/the-new-architecture/landing-page.md
  website/versioned_sidebars/version-0.70-sidebars.json
  website/versioned_sidebars/version-0.71-sidebars.json
  website/versioned_sidebars/version-0.72-sidebars.json
  website/versioned_sidebars/version-0.73-sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4028 add Twitter link to '@ReactNative' to maintain consistency with other '@ReactNative' references
  website/contributing/contributing-overview.md
Labels: CLA Signed

#4030 Migrate inline requires + RAM bundles docs to new "optimizing JS loading" guide
  docs/optimizing-javascript-loading.md
  docs/ram-bundles-inline-requires.md
  website/sidebars.json
  website/static/_redirects
Labels: Partner, p: Facebook, CLA Signed

#4041 Remove release documentation
  website/blog/2022-03-15-an-update-on-the-new-architecture-rollout.md
  website/contributing/release-branch-cut-and-rc0.md
  website/contributing/release-candidate-patch.md
  website/contributing/release-dependencies.md
  website/contributing/release-faq.md
  website/contributing/release-roles-responsibilites.md
  website/contributing/release-stable-minor.md
  website/contributing/release-stable-patch.md
  website/contributing/release-testing.md
  website/contributing/release-troubleshooting.md
  website/contributing/release-updating-packages.md
  website/contributing/updating-upgrade-helper.md
  website/sidebarsContributing.json
  website/static/_redirects
Labels: Partner, p: Facebook, CLA Signed

#4042 Add alan, alfonso for authors for 0.74 post
  website/blog/authors.yml
Labels: Partner, p: Facebook, CLA Signed

#4035 Remove `listKey` as it's no longer needed in RN 0.71+
  docs/virtualizedlist.md
  website/versioned_docs/version-0.71/virtualizedlist.md
  website/versioned_docs/version-0.72/virtualizedlist.md
  website/versioned_docs/version-0.73/virtualizedlist.md
Labels: Partner, p: callstack, CLA Signed

#4045 [docs] fix a missing word typo in the new architecture landing page
  docs/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.70/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.71/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.72/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.73/the-new-architecture/landing-page.md
Labels: CLA Signed

#4039 Add a new `Platform.isVision` property (React Native 0.74.x)
  docs/platform.md
Labels: Partner, p: callstack, CLA Signed

#4046 Add info block about moved docs for New Architecture
  docs/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.70/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.71/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.72/the-new-architecture/landing-page.md
  website/versioned_docs/version-0.73/the-new-architecture/landing-page.md
Labels: Partner, p: Facebook, CLA Signed

#4048 Cats should not drink dairy milk
  docs/intro-react.md
Labels: CLA Signed

#4050 Update virtualizedlist.md
  docs/virtualizedlist.md
  website/versioned_docs/version-0.72/virtualizedlist.md
  website/versioned_docs/version-0.73/virtualizedlist.md
Labels: CLA Signed

#4055 Open twitter url in new tab
  website/src/pages/index.js
Labels: CLA Signed

#4033 Add cursor style prop
  docs/view-style-props.md
Labels: :clock1: Waiting on PR, Partner, p: microsoft, CLA Signed

#2786 rename mistyped sample js file
  docs/native-modules-ios.md
  website/versioned_docs/version-0.70/native-modules-ios.md
  website/versioned_docs/version-0.71/native-modules-ios.md
  website/versioned_docs/version-0.72/native-modules-ios.md
  website/versioned_docs/version-0.73/native-modules-ios.md
Labels: CLA Signed

#4057 chore: changed href to the new react.dev site
  website/docusaurus.config.js
Labels: CLA Signed

#4066 Add ReactConf 2024 Banner
  website/docusaurus.config.js
Labels: Partner, p: Facebook, CLA Signed

#4067 fix: broken yogalayout link references
  docs/flexbox.md
  docs/layout-props.md
  website/architecture/architecture-glossary.md
  website/versioned_docs/version-0.70/flexbox.md
  website/versioned_docs/version-0.70/layout-props.md
  website/versioned_docs/version-0.71/flexbox.md
  website/versioned_docs/version-0.71/layout-props.md
  website/versioned_docs/version-0.72/flexbox.md
  website/versioned_docs/version-0.72/layout-props.md
  website/versioned_docs/version-0.73/flexbox.md
  website/versioned_docs/version-0.73/layout-props.md
Labels: CLA Signed

#4044 Draft 0.74 Release Notes Yoga Snippet
  website/blog/2024-04-15-0.74-post.md
  website/static/blog/assets/0.74-align-content.png
  website/static/blog/assets/0.74-row-reverse-after.png
  website/static/blog/assets/0.74-row-reverse-before.png
Labels: Partner, p: Facebook, CLA Signed

#4070 Bump weekly downloads to 2 million
  website/community/overview.md
Labels: Partner, p: Facebook, CLA Signed

#4068 Fill out position static snippet for 0.74
  website/blog/2024-04-15-0.74-post.md
  website/static/blog/assets/0.74-static-example.png
  website/static/blog/assets/0.74-zindex-example.png
Labels: Partner, p: Facebook, CLA Signed

#3959 Update InteractionManager Documentation To Remove Notes About React Native Web Support
  docs/interactionmanager.md
  website/versioned_docs/version-0.70/interactionmanager.md
  website/versioned_docs/version-0.71/interactionmanager.md
  website/versioned_docs/version-0.72/interactionmanager.md
  website/versioned_docs/version-0.73/interactionmanager.md
Labels: CLA Signed

#4073 Update staying-updated.md
  website/community/staying-updated.md
Labels: CLA Signed
