Repository facebook/react-native-website, pull requests merged in 2024-10, with the labels that each got.

#4232 Fully revamp the 'Integration with an Android Fragment' page
  docs/integration-with-android-fragment.md
  website/static/docs/assets/EmbeddedAppAndroidFragmentVideo.gif
Labels: Partner, p: Facebook, CLA Signed

#4239 [iOS] Rewrite the guide to integrate with Brownfield apps
  docs/_integration-with-existing-apps-ios.md
  docs/_integration-with-existing-apps-kotlin.md
  docs/_integration-with-existing-apps-objc.md
  docs/_integration-with-existing-apps-swift.md
  docs/integration-with-existing-apps.md
  website/core/TabsConstants.js
  website/static/docs/assets/EmbeddedAppIOSVideo.gif
  website/static/docs/assets/disable-sandboxing.png
Labels: Partner, p: Facebook, CLA Signed

#4235 Update docs related to position to account for static
  docs/flexbox.md
  docs/layout-props.md
  scripts/lint-examples/package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#4244 Remove banner on build speed to update to 0.71
  docs/build-speed.md
  website/versioned_docs/version-0.71/build-speed.md
  website/versioned_docs/version-0.72/build-speed.md
  website/versioned_docs/version-0.73/build-speed.md
  website/versioned_docs/version-0.74/build-speed.md
  website/versioned_docs/version-0.75/build-speed.md
Labels: Partner, p: Facebook, CLA Signed

#4243 chore: move native component and module docs to legacy
  docs/animations.md
  docs/communication-android.md
  docs/communication-ios.md
  docs/intro-react-native-components.md
  docs/legacy/direct-manipulation.md
  docs/legacy/local-library-setup.md
  docs/legacy/native-components-android.md
  docs/legacy/native-components-ios.md
  docs/legacy/native-modules-android.md
  docs/legacy/native-modules-intro.md
  docs/legacy/native-modules-ios.md
  docs/legacy/native-modules-setup.md
  docs/more-resources.md
  website/sidebars.json
  website/static/_redirects
Labels: Partner, p: Facebook, CLA Signed

#4246 Remove React 18 and React Native
  docs/react-18-and-react-native.md
  website/blog/2022-06-21-version-069.md
  website/static/_redirects
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#4249 chore: hermes, remove legacy debugging + old config
  docs/hermes.md
Labels: Partner, p: Facebook, CLA Signed

#4245 [docs] Update LogBox guide for RNDT, disambiguate ignore/filter behaviour
  docs/debugging.md
  website/static/docs/assets/debugging-logbox-076.jpg
Labels: Partner, p: Facebook, CLA Signed

#4240 docs: fix incorrect information about webp support in the source prop of React Native's Image component
  docs/image.md
Labels: CLA Signed

#4257 Add documentation for `none` resizeMethod
  docs/image.md
Labels: Partner, p: Facebook, CLA Signed

#4258 Remove CircleCI status from README
  README.md
Labels: Partner, p: Facebook, CLA Signed

#4251 [NA] Move Codegen Docs back
  docs/the-new-architecture/codegen-cli.md
  docs/the-new-architecture/using-codegen.md
  docs/the-new-architecture/what-is-codegen.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4260 [Docs][NA] Remove the New Architecture Landing page
  docs/the-new-architecture/landing-page.md
  website/blog/2022-09-05-version-070.md
  website/sidebars.json
  website/static/_redirects
  website/versioned_docs/version-0.70/build-speed.md
Labels: Partner, p: Facebook, CLA Signed

#4037 Remove: Profile Hermes section
  docs/profile-hermes.md
  website/sidebars.json
Labels: Wait on future Release, Partner, p: Facebook, CLA Signed

#4267 Fix MDX double `<p>` tags
  docs/appregistry.md
  docs/debugging-native-code.md
  docs/linking.md
  docs/permissionsandroid.md
  docs/pushnotificationios.md
  website/blog/2020-07-06-version-0.63.md
  website/versioned_docs/version-0.70/appregistry.md
  website/versioned_docs/version-0.70/debugging.md
  website/versioned_docs/version-0.70/linking.md
  website/versioned_docs/version-0.70/permissionsandroid.md
  website/versioned_docs/version-0.70/pushnotificationios.md
  website/versioned_docs/version-0.71/appregistry.md
  website/versioned_docs/version-0.71/debugging.md
  website/versioned_docs/version-0.71/linking.md
  website/versioned_docs/version-0.71/permissionsandroid.md
  website/versioned_docs/version-0.71/pushnotificationios.md
  website/versioned_docs/version-0.72/appregistry.md
  website/versioned_docs/version-0.72/linking.md
  website/versioned_docs/version-0.72/native-debugging.md
  website/versioned_docs/version-0.72/permissionsandroid.md
  website/versioned_docs/version-0.72/pushnotificationios.md
  website/versioned_docs/version-0.73/appregistry.md
  website/versioned_docs/version-0.73/linking.md
  website/versioned_docs/version-0.73/native-debugging.md
  website/versioned_docs/version-0.73/permissionsandroid.md
  website/versioned_docs/version-0.73/pushnotificationios.md
  website/versioned_docs/version-0.74/appregistry.md
  website/versioned_docs/version-0.74/linking.md
  website/versioned_docs/version-0.74/native-debugging.md
  website/versioned_docs/version-0.74/permissionsandroid.md
  website/versioned_docs/version-0.74/pushnotificationios.md
  website/versioned_docs/version-0.75/appregistry.md
  website/versioned_docs/version-0.75/debugging-native-code.md
  website/versioned_docs/version-0.75/linking.md
  website/versioned_docs/version-0.75/permissionsandroid.md
  website/versioned_docs/version-0.75/pushnotificationios.md
Labels: CLA Signed

#4259 Update Performance Overview to Reflect High Refresh Rate Displays Issue #4062
  docs/performance.md
Labels: CLA Signed

#4155 docs: remove outdated tv docs
  docs/building-for-tv.md
  website/versioned_docs/version-0.70/building-for-tv.md
  website/versioned_docs/version-0.71/building-for-tv.md
  website/versioned_docs/version-0.72/building-for-tv.md
  website/versioned_docs/version-0.73/building-for-tv.md
  website/versioned_docs/version-0.74/building-for-tv.md
  website/versioned_docs/version-0.75/building-for-tv.md
Labels: CLA Signed

#4261 [docs] Remove references to Chrome profiler from Profiling guide
  docs/profiling.md
Labels: Partner, p: Facebook, CLA Signed

#4254 [Docs] Add Guide to Write C++ TM
  docs/the-new-architecture/pure-cxx-modules.md
  website/sidebars.json
  website/static/docs/assets/AddFilesToXcode1.png
  website/static/docs/assets/AddFilesToXcode2.png
  website/static/docs/assets/CxxGuideAndroidVideo.gif
  website/static/docs/assets/CxxGuideIOSVideo.gif
  website/static/docs/assets/CxxTMGuideXcodeProject.png
Labels: Partner, p: Facebook, CLA Signed

#4271 [NA] Move the landing page to the Architecture section
  website/architecture/architecture-overview.md
  website/architecture/landing-page.md
  website/blog/2022-09-05-version-070.md
  website/sidebarsArchitecture.json
  website/static/_redirects
  website/versioned_docs/version-0.70/build-speed.md
Labels: Partner, p: Facebook, CLA Signed

#4269 [RN][Docs] Add guide on custom types in C++
  docs/the-new-architecture/custom-cxx-types.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4281 Update modal.md
  docs/modal.md
Labels: Partner, p: Facebook, CLA Signed

#4280 Android typo
  website/architecture/landing-page.md
Labels: CLA Signed

#4285 docs: Fixed wrong platform reference
  docs/the-new-architecture/pure-cxx-modules.md
Labels: CLA Signed

#4274 Extract Module to Library
  docs/the-new-architecture/create-module-library.md
  website/sidebars.json
  website/static/docs/assets/what-library.png
Labels: Partner, p: Facebook, CLA Signed

#4197 typo: initWithURL -> initWithBundleURL
  website/versioned_docs/version-0.70/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.71/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.72/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.73/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-objc.md
  website/versioned_docs/version-0.75/_integration-with-existing-apps-objc.md
Labels: CLA Signed

#4286 [Docs][NA] Add measurements and Direct Manipulation
  docs/the-new-architecture/direct-manipulation.md
  docs/the-new-architecture/layout-measurements.md
  website/sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4287 fix: minor issue on how-to-open-a-pull-request.md
  website/contributing/how-to-open-a-pull-request.md
Labels: CLA Signed

#4283 Turbo Native Modules - Documentation ported from reactwg
  docs/_turbo-native-modules-components.jsx
  docs/appendix.md
  docs/fabric-native-modules-android.md
  docs/fabric-native-modules-ios.md
  docs/fabric-native-modules.md
  docs/native-platforms.md
  docs/the-new-architecture/codegen-cli.md
  docs/the-new-architecture/pure-cxx-modules.md
  docs/the-new-architecture/using-codegen.md
  docs/turbo-native-modules-android.md
  docs/turbo-native-modules-ios.md
  docs/turbo-native-modules.md
  website/docusaurus.config.js
  website/sidebars.json
  website/src/css/customTheme.scss
  website/static/docs/assets/turbo-native-modules/turbo-native-modules-android.mp4
  website/static/docs/assets/turbo-native-modules/turbo-native-modules-android.webm
  website/static/docs/assets/turbo-native-modules/turbo-native-modules-ios.mp4
  website/static/docs/assets/turbo-native-modules/turbo-native-modules-ios.webm
  website/static/docs/assets/turbo-native-modules/xcode/1.webp
  website/static/docs/assets/turbo-native-modules/xcode/2.webp
  website/static/docs/assets/turbo-native-modules/xcode/3.webp
  website/static/docs/assets/turbo-native-modules/xcode/4.webp
  website/static/docs/assets/turbo-native-modules/xcode/5.webp
  website/static/docs/assets/turbo-native-modules/xcode/6.webp
Labels: Partner, p: Facebook, CLA Signed

#4275 [docs] Add React Native DevTools guide, update related info
  docs/debugging.md
  docs/linking.md
  docs/other-debugging-methods.md
  docs/performance.md
  docs/react-devtools.md
  docs/react-native-devtools.md
  docs/running-on-device.md
  docs/usecolorscheme.md
  website/sidebars.json
  website/static/_redirects
  website/static/docs/assets/debugging-dev-menu-076.jpg
  website/static/docs/assets/debugging-reconnect-menu.jpg
  website/static/docs/assets/debugging-rndt-console.jpg
  website/static/docs/assets/debugging-rndt-sources-paused-with-device.jpg
  website/static/docs/assets/debugging-rndt-welcome.jpg
  website/versioned_docs/version-0.73/debugging.md
  website/versioned_docs/version-0.74/debugging.md
Labels: Partner, p: Facebook, CLA Signed

#4292 docs: Fix typos in multiple docs
  docs/flexbox.md
  docs/image.md
  docs/stylesheet.md
  website/versioned_docs/version-0.70/image.md
  website/versioned_docs/version-0.71/image.md
  website/versioned_docs/version-0.72/image.md
  website/versioned_docs/version-0.73/image.md
  website/versioned_docs/version-0.74/image.md
  website/versioned_docs/version-0.75/image.md
  website/versioned_docs/version-0.75/stylesheet.md
Labels: CLA Signed

#4289 Add deprecation note for Statusbar backgroundcolor prop
  docs/statusbar.md
Labels: Partner, p: Facebook, CLA Signed

#4288 Add Fabric Native Component Guide
  docs/_fabric-native-components.jsx
  docs/appendix.md
  docs/fabric-native-components-android.md
  docs/fabric-native-components-ios.md
  docs/fabric-native-components.md
  docs/fabric-native-modules-android.md
  docs/fabric-native-modules-ios.md
  docs/fabric-native-modules.md
  docs/native-platforms.md
  docs/turbo-native-modules.md
  website/sidebars.json
  website/static/docs/assets/fabric-native-component-app-android.png
  website/static/docs/assets/fabric-native-component-app-ios.png
  website/static/docs/assets/fabric-native-components/1.webp
  website/static/docs/assets/fabric-native-components/2.webp
  website/static/docs/assets/fabric-native-components/3.webp
  website/static/docs/assets/fabric-native-components/4.webp
  website/static/docs/assets/webview-android.webp
  website/static/docs/assets/webview-ios.webp
Labels: Partner, p: Facebook, CLA Signed

#4279 feat: 0.76 Release Blog Post
  website/blog/2024-10-23-release-0.76-new-architecture.md
  website/blog/2024-10-23-the-new-architecture-is-here.md
  website/blog/authors.yml
  website/package.json
  website/src/css/customTheme.scss
  website/static/blog/assets/0.76-boxshadow-example.png
  website/static/blog/assets/0.76-bridge-diagram.png
  website/static/blog/assets/0.76-directory.png
  website/static/blog/assets/0.76-filter-example.png
  website/static/blog/assets/0.76-react-native-devtools.jpg
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#4296 [blog] Fix bullets and re-expand RNDT section in 0.76 post
  website/blog/2024-10-23-release-0.76-new-architecture.md
Labels: Partner, p: Facebook, CLA Signed

#4298 Fix typo
  website/blog/2024-10-23-the-new-architecture-is-here.md
Labels: CLA Signed

#4299 Update 2024-10-23-release-0.76-new-architecture.md
  website/blog/2024-10-23-release-0.76-new-architecture.md
Labels: CLA Signed

#4301 Update 2024-10-23-the-new-architecture-is-here.md
  website/blog/2024-10-23-the-new-architecture-is-here.md
Labels: CLA Signed

#4300 Update what-is-codegen.md
  docs/the-new-architecture/what-is-codegen.md
Labels: CLA Signed

#4302 Remove react-tweet
  website/package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#4303 Add redirect to landing page
  website/static/_redirects
Labels: Partner, p: Facebook, CLA Signed

#4297 [docs] Fix debugging /docs/next/ redirects following 0.76 cut
  website/static/_redirects
Labels: Partner, p: Facebook, CLA Signed

#4310 Fix typos/grammar in pure-cxx-modules.md
  docs/the-new-architecture/pure-cxx-modules.md
Labels: CLA Signed

#4314 fix: double colon in 2024-10-23-release-0.76-new-architecture.md
  website/blog/2024-10-23-release-0.76-new-architecture.md
Labels: CLA Signed

#4307 Update 2024-10-23-release-0.76-new-architecture.md
  website/blog/2024-10-23-release-0.76-new-architecture.md
Labels: CLA Signed

#4312 Update react-native-devtools.md
  docs/react-native-devtools.md
Labels: CLA Signed

#4313 docs: Add missing VS Code screenshot in Create a library
  docs/the-new-architecture/create-module-library.md
  website/static/docs/assets/turbo-native-modules/c++visualstudiocode.webp
  website/versioned_docs/version-0.76/the-new-architecture/create-module-library.md
Labels: CLA Signed

#4305 update banner
  website/docusaurus.config.js
Labels: Partner, p: Facebook, CLA Signed

#4309 [docs] Update troubleshooting.md to replace dead link
  docs/troubleshooting.md
Labels: CLA Signed

#4284 chore: suggest adding flag in Podfile instead of console
  website/architecture/landing-page.md
Labels: CLA Signed

#4248 Add selectionHandleColor prop on TextInput
  docs/textinput.md
  website/versioned_docs/version-0.74/textinput.md
  website/versioned_docs/version-0.75/textinput.md
  website/versioned_docs/version-0.76/textinput.md
Labels: CLA Signed

#4317 fix: WebViewNativeComponent typo extension to ts
  docs/the-new-architecture/using-codegen.md
Labels: CLA Signed

#4316 Update _integration-with-existing-apps-kotlin.md
  docs/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.76/_integration-with-existing-apps-kotlin.md
Labels: CLA Signed

#4319 Fix broken banner in home page
  website/docusaurus.config.js
Labels: Partner, p: Facebook, CLA Signed

#4315 chore: fix typos, grammar, and formatting in Fabric components guide
  docs/fabric-native-components-android.md
  docs/fabric-native-components-ios.md
  docs/fabric-native-components.md
Labels: CLA Signed

#4200 Remove ref in render antipattern in animated docs
  docs/animated.md
  docs/animatedvalue.md
  docs/animations.md
  docs/easing.md
  docs/interactionmanager.md
  docs/transforms.md
  website/versioned_docs/version-0.70/easing.md
  website/versioned_docs/version-0.70/interactionmanager.md
  website/versioned_docs/version-0.71/animated.md
  website/versioned_docs/version-0.71/animatedvalue.md
  website/versioned_docs/version-0.71/animations.md
  website/versioned_docs/version-0.71/easing.md
  website/versioned_docs/version-0.71/interactionmanager.md
  website/versioned_docs/version-0.72/animated.md
  website/versioned_docs/version-0.72/animatedvalue.md
  website/versioned_docs/version-0.72/animations.md
  website/versioned_docs/version-0.72/easing.md
  website/versioned_docs/version-0.72/interactionmanager.md
  website/versioned_docs/version-0.73/animated.md
  website/versioned_docs/version-0.73/animatedvalue.md
  website/versioned_docs/version-0.73/animations.md
  website/versioned_docs/version-0.73/easing.md
  website/versioned_docs/version-0.73/interactionmanager.md
  website/versioned_docs/version-0.73/transforms.md
  website/versioned_docs/version-0.74/animated.md
  website/versioned_docs/version-0.74/animatedvalue.md
  website/versioned_docs/version-0.74/animations.md
  website/versioned_docs/version-0.74/interactionmanager.md
  website/versioned_docs/version-0.74/transforms.md
  website/versioned_docs/version-0.75/animated.md
  website/versioned_docs/version-0.75/animatedvalue.md
  website/versioned_docs/version-0.75/animations.md
  website/versioned_docs/version-0.75/interactionmanager.md
  website/versioned_docs/version-0.75/transforms.md
  website/versioned_docs/version-0.76/animated.md
  website/versioned_docs/version-0.76/animatedvalue.md
  website/versioned_docs/version-0.76/animations.md
  website/versioned_docs/version-0.76/easing.md
  website/versioned_docs/version-0.76/interactionmanager.md
  website/versioned_docs/version-0.76/transforms.md
Labels: Partner, p: Facebook, CLA Signed

#4321 Fix broken examples in Animated API docs
  docs/animations.md
  website/versioned_docs/version-0.71/animations.md
  website/versioned_docs/version-0.72/animations.md
  website/versioned_docs/version-0.73/animations.md
  website/versioned_docs/version-0.74/animations.md
  website/versioned_docs/version-0.75/animations.md
  website/versioned_docs/version-0.76/animations.md
Labels: Partner, p: Facebook, CLA Signed

#4322 docs: Fix link for debugging native code
  docs/debugging.md
Labels: CLA Signed

#4323 docs: fix typo in architecture landing page
  website/architecture/landing-page.md
Labels: CLA Signed

#4324 [NA] Bring back layout measurement and direct manipulation
  website/sidebars.json
  website/versioned_sidebars/version-0.76-sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4325 Update spelling and formatting for codegen docs
  docs/the-new-architecture/using-codegen.md
  docs/the-new-architecture/what-is-codegen.md
  website/versioned_docs/version-0.76/the-new-architecture/using-codegen.md
  website/versioned_docs/version-0.76/the-new-architecture/what-is-codegen.md
Labels: Partner, p: Facebook, CLA Signed

#4326 Update cache control to reflect Android support
  docs/image.md
  docs/images.md
Labels: Partner, p: Facebook, CLA Signed
