Repository facebook/react-native-website, pull requests merged in 2025-01, with the labels that each got.

#4415 Update Docusaurus config with type assertions for plugins
  website/docusaurus.config.ts
Labels: CLA Signed

#4414 Fix typos in documentation
  docs/legacy/native-modules-intro.md
  docs/scrollview.md
  docs/the-new-architecture/create-module-library.md
  docs/the-new-architecture/layout-measurements.md
  docs/the-new-architecture/using-codegen.md
  docs/upgrading.md
  website/blog/2018-11-01-oss-roadmap.md
  website/versioned_docs/version-0.70/custom-webview-android.md
  website/versioned_docs/version-0.70/custom-webview-ios.md
  website/versioned_docs/version-0.70/native-modules-intro.md
  website/versioned_docs/version-0.70/profiling.md
  website/versioned_docs/version-0.70/scrollview.md
  website/versioned_docs/version-0.70/upgrading.md
  website/versioned_docs/version-0.71/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.71/custom-webview-android.md
  website/versioned_docs/version-0.71/custom-webview-ios.md
  website/versioned_docs/version-0.71/native-modules-intro.md
  website/versioned_docs/version-0.71/profiling.md
  website/versioned_docs/version-0.71/scrollview.md
  website/versioned_docs/version-0.71/upgrading.md
  website/versioned_docs/version-0.72/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.72/custom-webview-android.md
  website/versioned_docs/version-0.72/custom-webview-ios.md
  website/versioned_docs/version-0.72/native-modules-intro.md
  website/versioned_docs/version-0.72/profiling.md
  website/versioned_docs/version-0.72/scrollview.md
  website/versioned_docs/version-0.72/upgrading.md
  website/versioned_docs/version-0.73/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.73/custom-webview-android.md
  website/versioned_docs/version-0.73/custom-webview-ios.md
  website/versioned_docs/version-0.73/native-modules-intro.md
  website/versioned_docs/version-0.73/profiling.md
  website/versioned_docs/version-0.73/scrollview.md
  website/versioned_docs/version-0.73/upgrading.md
  website/versioned_docs/version-0.74/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.74/custom-webview-android.md
  website/versioned_docs/version-0.74/custom-webview-ios.md
  website/versioned_docs/version-0.74/native-modules-intro.md
  website/versioned_docs/version-0.74/profiling.md
  website/versioned_docs/version-0.74/scrollview.md
  website/versioned_docs/version-0.74/upgrading.md
  website/versioned_docs/version-0.75/_integration-with-existing-apps-swift.md
  website/versioned_docs/version-0.75/custom-webview-android.md
  website/versioned_docs/version-0.75/custom-webview-ios.md
  website/versioned_docs/version-0.75/native-modules-intro.md
  website/versioned_docs/version-0.75/profiling.md
  website/versioned_docs/version-0.75/scrollview.md
  website/versioned_docs/version-0.75/upgrading.md
  website/versioned_docs/version-0.76/fabric-native-components-android.md
  website/versioned_docs/version-0.76/fabric-native-components-ios.md
  website/versioned_docs/version-0.76/legacy/native-modules-intro.md
  website/versioned_docs/version-0.76/profiling.md
  website/versioned_docs/version-0.76/scrollview.md
  website/versioned_docs/version-0.76/the-new-architecture/create-module-library.md
  website/versioned_docs/version-0.76/the-new-architecture/layout-measurements.md
  website/versioned_docs/version-0.76/the-new-architecture/using-codegen.md
  website/versioned_docs/version-0.76/upgrading.md
Labels: CLA Signed

#4411 Update border radius styles for consistency improvements
  website/src/css/customTheme.scss
Labels: CLA Signed

#4413 Make table border thicker and easier to see
  website/src/css/customTheme.scss
Labels: CLA Signed

#4418 Add codeblock language as title remark plugin
  plugins/remark-codeblock-language-as-title/README.md
  plugins/remark-codeblock-language-as-title/package.json
  plugins/remark-codeblock-language-as-title/src/index.js
  plugins/remark-lint-no-dead-urls/package.json
  plugins/remark-snackplayer/package.json
  website/docusaurus.config.ts
  yarn.lock
Labels: CLA Signed

#4417 Fix duplicate imports in Integration with Existing Apps
  docs/_integration-with-existing-apps-ios.md
  website/versioned_docs/version-0.76/_integration-with-existing-apps-ios.md
Labels: CLA Signed

#4419 Update XML code block syntax in documentation
  docs/headless-js-android.md
  website/versioned_docs/version-0.70/headless-js-android.md
  website/versioned_docs/version-0.71/headless-js-android.md
  website/versioned_docs/version-0.72/headless-js-android.md
  website/versioned_docs/version-0.73/headless-js-android.md
  website/versioned_docs/version-0.74/headless-js-android.md
  website/versioned_docs/version-0.75/headless-js-android.md
  website/versioned_docs/version-0.76/headless-js-android.md
Labels: CLA Signed

#4420 Change default language from 'jsx' to 'tsx' in Docusaurus config
  website/docusaurus.config.ts
Labels: CLA Signed

#4427 Fix integration with existing apps URLs
  docs/_integration-with-existing-apps-ios.md
  docs/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.76/_integration-with-existing-apps-kotlin.md
Labels: Partner, p: Facebook, CLA Signed

#4412 Update colors for table of contents to be more in line with the theme
  website/src/css/customTheme.scss
Labels: CLA Signed

#4431 Better contrast for component grid component header
  website/src/css/customTheme.scss
Labels: CLA Signed

#4432 fixed: kotlin SoLoader.init params to fix "library 'libhermes_executor.so' not found
  docs/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.76/_integration-with-existing-apps-kotlin.md
Labels: CLA Signed

#4433 Enhance component grid link clickability for better usability
  website/src/css/customTheme.scss
Labels: CLA Signed

#4428 Add missing syntax highlighting in Integration with Existing Apps
  docs/_integration-with-existing-apps-ios.md
  docs/_integration-with-existing-apps-kotlin.md
  website/versioned_docs/version-0.76/_integration-with-existing-apps-ios.md
  website/versioned_docs/version-0.76/_integration-with-existing-apps-kotlin.md
Labels: CLA Signed

#4438 fix(docs): typo in hermes docs
  docs/hermes.md
Labels: CLA Signed

#4440 Box sizing documentation
  docs/layout-props.md
Labels: Partner, p: Facebook, CLA Signed

#4439 [RN][NewArch] Remove danger block for Pure C++ TurboModule
  docs/the-new-architecture/pure-cxx-modules.md
  website/versioned_docs/version-0.76/the-new-architecture/pure-cxx-modules.md
Labels: CLA Signed

#4434 Add documentation for disableKeyboardShortcuts prop in TextInput
  docs/textinput.md
Labels: CLA Signed

#4446 add prop Modal.navigationBarTranslucent
  docs/modal.md
Labels: Partner, p: Facebook, CLA Signed

#4444 Add filter documentation
  docs/dropshadowvalue.md
  docs/view-style-props.md
  website/sidebars.ts
  website/versioned_docs/version-0.76/dropshadowvalue.md
  website/versioned_docs/version-0.76/view-style-props.md
  website/versioned_sidebars/version-0.76-sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4448 Fixes typo: period in the middle of a sentence. Further clarifies the paragraph's meaning.
  docs/linking.md
Labels: CLA Signed

#4449 Add missing syntax highlighting in View
  docs/view.md
  website/versioned_docs/version-0.70/view.md
  website/versioned_docs/version-0.71/view.md
  website/versioned_docs/version-0.72/view.md
  website/versioned_docs/version-0.73/view.md
  website/versioned_docs/version-0.74/view.md
  website/versioned_docs/version-0.75/view.md
  website/versioned_docs/version-0.76/view.md
Labels: CLA Signed

#4436 [RN][Blog] Release Blogpost for 0.77
  website/blog/2025-01-21-version-0.77.md
  website/blog/authors.yml
  website/static/blog/assets/0.77-blend-mode.png
  website/static/blog/assets/0.77-border-box.png
  website/static/blog/assets/0.77-display-contents-1.png
  website/static/blog/assets/0.77-display-contents-2.gif
  website/static/blog/assets/0.77-display-contents-3.gif
  website/static/blog/assets/0.77-outline-props.png
  website/static/blog/assets/0.77-swift-upgrade-helper.png
Labels: Partner, p: Facebook, CLA Signed

#4454 fix: give credit to Oskar for Swift template
  website/blog/2025-01-21-version-0.77.md
Labels: Partner, p: callstack, CLA Signed

#4447 Add instructions for custom logging in native modules
  docs/debugging-native-code.md
Labels: CLA Signed

#4459 Update yarn-deduplicate
  package.json
  yarn.lock
Labels: CLA Signed

#4463 fix(Modal): remove non-existent prop
  website/versioned_docs/version-0.76/modal.md
Labels: CLA Signed

#4464 Add box shadow documentation
  docs/boxshadowvalue.md
  docs/shadow-props.md
  docs/view-style-props.md
  website/sidebars.ts
  website/versioned_docs/version-0.76/boxshadowvalue.md
  website/versioned_docs/version-0.76/shadow-props.md
  website/versioned_docs/version-0.76/view-style-props.md
  website/versioned_docs/version-0.77/boxshadowvalue.md
  website/versioned_docs/version-0.77/shadow-props.md
  website/versioned_docs/version-0.77/view-style-props.md
  website/versioned_sidebars/version-0.76-sidebars.json
  website/versioned_sidebars/version-0.77-sidebars.json
Labels: Partner, p: Facebook, CLA Signed

#4467 Update turbo-native-modules-android.md
  docs/fabric-native-components-android.md
  docs/turbo-native-modules-android.md
  website/versioned_docs/version-0.76/fabric-native-components-android.md
  website/versioned_docs/version-0.76/turbo-native-modules-android.md
  website/versioned_docs/version-0.77/fabric-native-components-android.md
  website/versioned_docs/version-0.77/turbo-native-modules-android.md
Labels: CLA Signed
