Repository facebook/react-native-website, pull requests merged in 2025-05, with the labels that each got.

#4597 [RNW]Fix missing license in css files
  website/src/theme/Blog/Components/Author/styles.module.css
  website/src/theme/DocItem/Footer/styles.module.css
Labels: Partner, p: Facebook, CLA Signed

#4596 [RNW][Deps] Bump babel dependencies to solve vulnerability issues
  scripts/lint-examples/package.json
  yarn.lock
Labels: Partner, p: Facebook, CLA Signed

#4605 Remove outdated entries in React Native showcase
  website/showcase.json
Labels: Partner, CLA Signed, p: Infinite Red

#4601 Tweak TypeScript guide
  docs/typescript.md
  website/versioned_docs/version-0.79/typescript.md
Labels: Partner, p: Facebook, CLA Signed

#4609 [blog] Add breaking change notice/info for 0.79 resolution changes
  website/blog/2025-04-08-react-native-0.79.md
Labels: Partner, p: Facebook, CLA Signed

#4604 override in the swift code
  docs/linking.md
Labels: CLA Signed

#4617 Add display: 'contents'
  docs/layout-props.md
  website/versioned_docs/version-0.77/layout-props.md
  website/versioned_docs/version-0.78/layout-props.md
  website/versioned_docs/version-0.79/layout-props.md
Labels: CLA Signed

#4619 Add targetevent to sidebar
  website/sidebars.ts
Labels: Partner, p: Facebook, CLA Signed

#4607 Docusaurus 3.8
  website/docusaurus.config.ts
  website/package.json
  website/src/css/customTheme.scss
  yarn.lock
Labels: CLA Signed

#4623 Add targetevent to current versioned doc
  website/versioned_docs/version-0.79/targetevent.md
Labels: Partner, p: Facebook, CLA Signed

#4622 Add targetevent to sidebar
  website/sidebars.ts
Labels: Partner, p: Facebook, CLA Signed
