Repository facebook/react-native-website, pull requests merged in 2025-06, with the labels that each got.

#4530 TextInput: document `inputAccessoryViewButtonLabel` prop
  docs/textinput.md
  website/versioned_docs/version-0.77/textinput.md
  website/versioned_docs/version-0.78/textinput.md
Labels: CLA Signed

#4630 [scripts] LLMS: skip non-existing yet URLs instead of failing
  scripts/generate-llms-txt.js
Labels: Partner, p: expo, CLA Signed

#4626 Add I18nManager docs
  docs/i18nmanager.md
  website/sidebars.ts
Labels: CLA Signed

#4642 Fix small typo in the documentation
  docs/the-new-architecture/create-module-library.md
Labels: CLA Signed

#4632 [blog] Moving Towards a Stable JavaScript API
  website/blog/2025-06-09-moving-towards-a-stable-javascript-api.md
  website/blog/authors.yml
  website/static/blog/assets/0.80-js-stable-api-appjs.jpg
Labels: Partner, p: Facebook, CLA Signed

#4591 [docs] Performance: update outdated info
  docs/performance.md
Labels: Partner, CLA Signed, p: Infinite Red

#4656 Reword accessible prop in accessiblity guide
  docs/accessibility.md
  docs/view.md
  website/versioned_docs/version-0.78/accessibility.md
  website/versioned_docs/version-0.78/view.md
  website/versioned_docs/version-0.79/accessibility.md
  website/versioned_docs/version-0.79/view.md
  website/versioned_docs/version-0.80/accessibility.md
  website/versioned_docs/version-0.80/view.md
Labels: Partner, p: Facebook, CLA Signed

#4658 Add allowSwipeDismissal documentation
  docs/modal.md
Labels: :clock1: Waiting on PR, Partner, p: callstack, CLA Signed

#4665 docs: update turbo-native-modules-android.md
  website/versioned_docs/version-0.80/turbo-native-modules-android.md
Labels: CLA Signed

#4666 misc(docs): add missing curly bracket
  docs/turbo-native-modules-ios.md
Labels: CLA Signed
