Repository facebook/react-native-website, pull requests merged in 2025-03, with the labels that each got.

#4525 [RN][iOS] Update Module Registration
  docs/the-new-architecture/pure-cxx-modules.md
  docs/the-new-architecture/using-codegen.md
  docs/turbo-native-modules-ios.md
Labels: Partner, p: Facebook, CLA Signed

#4519 Document `enableBundleCompression`
  docs/react-native-gradle-plugin.md
Labels: Partner, p: Facebook, CLA Signed

#4527 docs: replace usage of react-native-fast-image
  website/versioned_docs/version-0.78/optimizing-flatlist-configuration.md
Labels: CLA Signed

#4521 Enable yarn cache in GitHub Actions workflow
  .github/workflows/pre-merge.yml
Labels: CLA Signed

#4532 Fix heading in codegen-cli.md
  docs/the-new-architecture/codegen-cli.md
Labels: Partner, p: Facebook, CLA Signed

#4531 Have column reverse below column instead of on the diagonal
  docs/flexbox.md
  website/versioned_docs/version-0.78/flexbox.md
Labels: CLA Signed

#4538 add youtube playlist for Chain React 2024
  website/community/staying-updated.md
Labels: CLA Signed

#4533 Update link to MainActivity.kt file
  website/versioned_docs/version-0.78/_integration-with-existing-apps-kotlin.md
Labels: CLA Signed

#4539 TextInput: update `numberOfLines` section
  docs/textinput.md
Labels: p: software mansion, Partner, p: Facebook, CLA Signed

#4541 address table mobile overflow, tweak appearance
  website/src/css/customTheme.scss
Labels: Partner, p: expo, CLA Signed

#4544 Update subtle color variables for improved contrast
  website/src/css/customTheme.scss
Labels: CLA Signed
