Repository facebook/react-native-website, pull requests merged in 2025-09, with the labels that each got.

#4757 convert quote blocks to admonitions, cleanup removed APIs pages
  docs/accessibilityinfo.md
  docs/actionsheetios.md
  docs/alertios.md
  docs/animated.md
  docs/appearance.md
  docs/appregistry.md
  docs/asyncstorage.md
  docs/backhandler.md
  docs/checkbox.md
  docs/clipboard.md
  docs/datepickerandroid.md
  docs/datepickerios.md
  docs/dimensions.md
  docs/dynamiccolorios.md
  docs/get-started-without-a-framework.md
  docs/image.md
  docs/imagepickerios.md
  docs/keyboard.md
  docs/keyboardavoidingview.md
  docs/layout-props.md
  docs/modal.md
  docs/optimizing-flatlist-configuration.md
  docs/platformcolor.md
  docs/pressable.md
  docs/progressbarandroid.md
  docs/pushnotificationios.md
  docs/refreshcontrol.md
  docs/safeareaview.md
  docs/scrollview.md
  docs/sectionlist.md
  docs/segmentedcontrolios.md
  docs/set-up-your-environment.md
  docs/settings.md
  docs/statusbarios.md
  docs/stylesheet.md
  docs/text.md
  docs/textinput.md
  docs/timepickerandroid.md
  docs/toastandroid.md
  docs/touchablehighlight.md
  docs/touchablenativefeedback.md
  docs/touchableopacity.md
  docs/touchablewithoutfeedback.md
  docs/transforms.md
  docs/vibration.md
  docs/virtualizedlist.md
Labels: Partner, p: expo, CLA Signed

#4755 align admonitions style with react.dev
  website/src/css/customTheme.scss
Labels: Partner, p: expo, CLA Signed

#4760 Update Fresco to 3.6.0 to fix Android 16KB page issue
  docs/image.md
  website/versioned_docs/version-0.77/image.md
  website/versioned_docs/version-0.78/image.md
  website/versioned_docs/version-0.79/image.md
  website/versioned_docs/version-0.80/image.md
  website/versioned_docs/version-0.81/image.md
Labels: CLA Signed

#4769 Update the required Node.js version to 20.19.4 for React Native v0.81 and later
  docs/_getting-started-linux-android.md
  docs/_getting-started-macos-android.md
  docs/_getting-started-macos-ios.md
  website/versioned_docs/version-0.81/_getting-started-linux-android.md
  website/versioned_docs/version-0.81/_getting-started-macos-android.md
  website/versioned_docs/version-0.81/_getting-started-macos-ios.md
Labels: CLA Signed

#4785 Initial docs for globals
  docs/global-AbortController.md
  docs/global-AbortSignal.md
  docs/global-Blob.md
  docs/global-File.md
  docs/global-FileReader.md
  docs/global-FormData.md
  docs/global-Headers.md
  docs/global-Request.md
  docs/global-Response.md
  docs/global-URL.md
  docs/global-URLSearchParams.md
  docs/global-WebSocket.md
  docs/global-XMLHttpRequest.md
  docs/global-__DEV__.md
  docs/global-alert.md
  docs/global-cancelAnimationFrame.md
  docs/global-cancelIdleCallback.md
  docs/global-clearInterval.md
  docs/global-clearTimeout.md
  docs/global-console.md
  docs/global-fetch.md
  docs/global-global.md
  docs/global-navigator.md
  docs/global-performance.md
  docs/global-process.md
  docs/global-queueMicrotask.md
  docs/global-requestAnimationFrame.md
  docs/global-requestIdleCallback.md
  docs/global-self.md
  docs/global-setInterval.md
  docs/global-setTimeout.md
  docs/global-window.md
  website/sidebars.ts
Labels: Partner, p: Facebook, CLA Signed

#4791 Extract experimental API warning to a separate file
  docs/_experimental-api-warning.mdx
  docs/accessibility.md
  docs/view.md
  docs/virtualview.md
Labels: Partner, p: Facebook, CLA Signed

#4787 update page status emojis in versioned docs
  website/versioned_docs/version-0.77/alertios.md
  website/versioned_docs/version-0.77/asyncstorage.md
  website/versioned_docs/version-0.77/checkbox.md
  website/versioned_docs/version-0.77/clipboard.md
  website/versioned_docs/version-0.77/datepickerandroid.md
  website/versioned_docs/version-0.77/datepickerios.md
  website/versioned_docs/version-0.77/imagepickerios.md
  website/versioned_docs/version-0.77/progressbarandroid.md
  website/versioned_docs/version-0.77/pushnotificationios.md
  website/versioned_docs/version-0.77/segmentedcontrolios.md
  website/versioned_docs/version-0.77/statusbarios.md
  website/versioned_docs/version-0.77/timepickerandroid.md
  website/versioned_docs/version-0.78/alertios.md
  website/versioned_docs/version-0.78/asyncstorage.md
  website/versioned_docs/version-0.78/checkbox.md
  website/versioned_docs/version-0.78/clipboard.md
  website/versioned_docs/version-0.78/datepickerandroid.md
  website/versioned_docs/version-0.78/datepickerios.md
  website/versioned_docs/version-0.78/imagepickerios.md
  website/versioned_docs/version-0.78/progressbarandroid.md
  website/versioned_docs/version-0.78/pushnotificationios.md
  website/versioned_docs/version-0.78/segmentedcontrolios.md
  website/versioned_docs/version-0.78/statusbarios.md
  website/versioned_docs/version-0.78/timepickerandroid.md
  website/versioned_docs/version-0.79/alertios.md
  website/versioned_docs/version-0.79/asyncstorage.md
  website/versioned_docs/version-0.79/checkbox.md
  website/versioned_docs/version-0.79/clipboard.md
  website/versioned_docs/version-0.79/datepickerandroid.md
  website/versioned_docs/version-0.79/datepickerios.md
  website/versioned_docs/version-0.79/imagepickerios.md
  website/versioned_docs/version-0.79/progressbarandroid.md
  website/versioned_docs/version-0.79/pushnotificationios.md
  website/versioned_docs/version-0.79/segmentedcontrolios.md
  website/versioned_docs/version-0.79/statusbarios.md
  website/versioned_docs/version-0.79/timepickerandroid.md
  website/versioned_docs/version-0.80/alertios.md
  website/versioned_docs/version-0.80/asyncstorage.md
  website/versioned_docs/version-0.80/checkbox.md
  website/versioned_docs/version-0.80/clipboard.md
  website/versioned_docs/version-0.80/datepickerandroid.md
  website/versioned_docs/version-0.80/datepickerios.md
  website/versioned_docs/version-0.80/imagepickerios.md
  website/versioned_docs/version-0.80/progressbarandroid.md
  website/versioned_docs/version-0.80/pushnotificationios.md
  website/versioned_docs/version-0.80/segmentedcontrolios.md
  website/versioned_docs/version-0.80/statusbarios.md
  website/versioned_docs/version-0.80/timepickerandroid.md
  website/versioned_docs/version-0.81/alertios.md
  website/versioned_docs/version-0.81/asyncstorage.md
  website/versioned_docs/version-0.81/checkbox.md
  website/versioned_docs/version-0.81/clipboard.md
  website/versioned_docs/version-0.81/datepickerandroid.md
  website/versioned_docs/version-0.81/datepickerios.md
  website/versioned_docs/version-0.81/imagepickerios.md
  website/versioned_docs/version-0.81/progressbarandroid.md
  website/versioned_docs/version-0.81/pushnotificationios.md
  website/versioned_docs/version-0.81/segmentedcontrolios.md
  website/versioned_docs/version-0.81/statusbarios.md
  website/versioned_docs/version-0.81/timepickerandroid.md
Labels: Partner, p: expo, CLA Signed

#4799 fix script generating llms.txt
  scripts/generate-llms-txt.js
Labels: Partner, p: expo, CLA Signed

#4804 update Shopify showcase description
  website/src/pages/showcase.tsx
Labels: CLA Signed

#4811 switch workflows and Netlify setup to use Node 22
  .github/workflows/pre-merge.yml
  netlify.toml
  package.json
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#4809 docs: Android `minimumFontScale` props added
  docs/text.md
  website/versioned_docs/version-0.77/text.md
  website/versioned_docs/version-0.78/text.md
  website/versioned_docs/version-0.79/text.md
  website/versioned_docs/version-0.80/text.md
  website/versioned_docs/version-0.81/text.md
Labels: CLA Signed
