Repository facebook/react-native-website, pull requests merged in 2025-04, with the labels that each got.

#4537 bump lint stack, update configs, fix new warnings
  .alexrc.js
  docs/text.md
  package.json
  website/.remarkrc.mjs
  website/blog/2024-10-23-the-new-architecture-is-here.md
  website/package.json
  website/src/css/customTheme.scss
  website/src/pages/Home/Hero/styles.module.css
  website/src/pages/Home/Platforms/styles.module.css
  website/src/pages/Home/components/Section/styles.module.css
  website/versioned_docs/version-0.70/text.md
  website/versioned_docs/version-0.71/text.md
  website/versioned_docs/version-0.72/text.md
  website/versioned_docs/version-0.73/text.md
  website/versioned_docs/version-0.74/text.md
  website/versioned_docs/version-0.75/text.md
  website/versioned_docs/version-0.76/text.md
  website/versioned_docs/version-0.77/text.md
  website/versioned_docs/version-0.78/text.md
  yarn.lock
Labels: Partner, p: expo, CLA Signed

#4555 [RN][Releases] Add Blogpost for 0.79
  docs/build-speed.md
  website/blog/2025-04-08-react-native-0.79.md
  website/static/blog/assets/0.79-metro-startup-comparison.gif
  website/static/docs/assets/gradle-config-caching.gif
Labels: Partner, p: Facebook, CLA Signed

#4559 Update 2025-04-08-react-native-0.79.md
  website/blog/2025-04-08-react-native-0.79.md
Labels: CLA Signed

#4560 Add React Conf announcement bar
  website/docusaurus.config.ts
Labels: Partner, p: Facebook, CLA Signed

#4562 [RN][Doc] Update brownfield to match the new Podfile
  docs/_integration-with-existing-apps-ios.md
  website/versioned_docs/version-0.78/_integration-with-existing-apps-ios.md
Labels: Partner, p: Facebook, CLA Signed

#4557 [RN][NativeModules] Refactor the advanced topic section
  docs/the-new-architecture/advanced-topics-modules.md
  website/sidebars.ts
Labels: Partner, p: Facebook, CLA Signed

#4563 [RN][Doc] Passing initial props to iOS views
  docs/_integration-with-existing-apps-ios.md
  website/static/docs/assets/brownfield-with-initial-props.png
Labels: Partner, p: Facebook, CLA Signed

#4558 [RN][iOS] Add guide on Native Modules in Swift
  docs/the-new-architecture/advanced-topics-modules.md
  docs/the-new-architecture/turbo-modules-with-swift.md
  website/static/docs/assets/BridgingHeader.png
Labels: Partner, p: Facebook, CLA Signed

#4561 [RN][Doc] Add guide on TurboModule that can emit events
  docs/the-new-architecture/advanced-topics-modules.md
  docs/the-new-architecture/native-modules-custom-events.md
  website/static/docs/assets/turbo-native-modules-events-android.gif
  website/static/docs/assets/turbo-native-modules-events-ios.gif
Labels: Partner, p: Facebook, CLA Signed

#4568 [RN][Docs] Refactor the Advanced Topics of the Component
  docs/the-new-architecture/advanced-topics-components.md
  docs/the-new-architecture/advanced-topics-modules.md
  website/sidebars.ts
Labels: Partner, p: Facebook, CLA Signed

#4554 Improve `Platform.select` description
  website/versioned_docs/version-0.78/platform.md
Labels: CLA Signed

#4572 Remove platform distinction on snapToAlignment
  docs/scrollview.md
  website/versioned_docs/version-0.70/scrollview.md
  website/versioned_docs/version-0.71/scrollview.md
  website/versioned_docs/version-0.72/scrollview.md
  website/versioned_docs/version-0.73/scrollview.md
  website/versioned_docs/version-0.74/scrollview.md
  website/versioned_docs/version-0.75/scrollview.md
  website/versioned_docs/version-0.76/scrollview.md
  website/versioned_docs/version-0.77/scrollview.md
  website/versioned_docs/version-0.78/scrollview.md
Labels: Partner, p: Facebook, CLA Signed

#4576 Add the Versioning Policy page for React Native
  website/contributing/contributing-overview.md
  website/contributing/versioning-policy.md
  website/sidebarsContributing.ts
Labels: Partner, p: Facebook, CLA Signed

#4540 FabricNativeComponents: Update codegen imports
  docs/fabric-native-components.md
Labels: Wait on future Release, p: software mansion, Partner, p: Facebook, CLA Signed

#4593 fix: override getTaskConfig method signature
  docs/headless-js-android.md
Labels: CLA Signed

#4592 Add AccessibilityAction documentation for "expand" and "collapse"
  docs/accessibility.md
Labels: Partner, p: Facebook, CLA Signed

#4594 chore: add bluesky link
  website/docusaurus.config.ts
Labels: CLA Signed

#4580 Update the JSON provided in the modification of the package.json file step
  docs/the-new-architecture/pure-cxx-modules.md
  website/versioned_docs/version-0.79/the-new-architecture/pure-cxx-modules.md
Labels: CLA Signed

#4590 Add script for generating `llms.txt`
  .gitignore
  scripts/generate-llms-txt.js
  website/package.json
Labels: Partner, p: callstack, CLA Signed
